### ISSUE TITLE
Create live Storybook demo MDX component

### ISSUE THREAD

**Issue by mattrosno** [carbon-design-system/carbon-platform#1010]
**Summary**

Design spec: https://www.figma.com/file/Cs94zXOUUEizXNdDz263OA/Component-demo?node-id=114%3A169975

**Functionality**

This can be achieved through a new MDX component with props to control embed width and the variants to include in the embed. The variants prop likely needs to be an array where each item has a display name and a URL.

The URL for each demo embed needs to be of this format so it's a "canvas-only" embed:

https://react.carbondesignsystem.com/iframe.html?id=components-button--default

Then, in the embed caption, the link to the full demo would take this format:

https://react.carbondesignsystem.com/?path=/story/components-button--default

(Replace `iframe.html?id=` with `?path=/story/`.)

The first demo in the array would get shown by default.

**Documentation**

We'll need to document how Storybook should be configured (e.g. use a theme switcher that puts `globals=theme:g10` as a query string parameter, component placement justification in a story, etc.)

Consider opening a separate issue to determine if we need to use an existing Carbon Storybook configuration package, or create a new one.

**Acceptance criteria**

- [ ] Render the caption that links out to the full demo
- [ ] Demo window sizes
  - [ ] 8 and 12 columns
  - [ ] Fixed height based on number of columns
- [ ] Theme switcher
  - [ ] Dropdown that updates `globals=theme:g10`
  - [ ] Background
- [ ] Variant switcher
  - [ ] Dropdown
  - [ ] Data bind
  - [ ] Edge cases for many variants

**Comment by mattrosno** [comment]
What happens if there's no indexed live demos? In that scenario, I think we can omit the `Live demo` heading.

What happens if we have just a static image as a "Demo"? We should consider, in a separate issue, adding `asset.docs.overviewPath` to the schema that gets used after the dashboard, before the standardized content below the dashboard. That way, the overview markdown file can have a "Demo" heading followed by a markdown image.

**Comment by alisonjoseph** [comment]
Demo exploration branch -- https://github.com/carbon-design-system/carbon-platform/blob/demo-explorations-763/services/web-app/pages/samples/demo/index.mdx
