### ISSUE TITLE
Thumbnails hover bugs

### ISSUE THREAD

**Issue by mattrosno** [carbon-design-system/carbon-platform#1027]
**Steps to reproduce**

<img width="319" alt="image" src="https://user-images.githubusercontent.com/1691245/179558586-8ee84c2f-44c2-4849-8a4e-b0c8730afd7a.png">

<img width="316" alt="image" src="https://user-images.githubusercontent.com/1691245/179558669-17d76b0d-88d2-4b14-86b5-0a8ef3ca8532.png">

<img width="315" alt="image" src="https://user-images.githubusercontent.com/1691245/179558890-baae884c-789c-4d98-b007-ae18e6270fcc.png">

<img width="311" alt="image" src="https://user-images.githubusercontent.com/1691245/179559456-ca797a36-8d8b-4041-b2e9-4439d608a42a.png">

<img width="313" alt="image" src="https://user-images.githubusercontent.com/1691245/179559503-65d6dab1-a258-4282-894d-14442adef460.png">

Should all of these have white outlines?

<img width="313" alt="image" src="https://user-images.githubusercontent.com/1691245/179558806-30e4f76a-5088-4513-9ebe-6d0738ed0a24.png">

This one's white background doesn't extend low enough.

<img width="311" alt="image" src="https://user-images.githubusercontent.com/1691245/179559002-62c526a5-6edb-4d43-abf5-308776bd3840.png">

<img width="315" alt="image" src="https://user-images.githubusercontent.com/1691245/179559067-35acf469-885b-467f-8ec3-ecb6bf3bed12.png">

**Comment by mattrosno** [comment]
FYI @andreancardona @kingtraceyj

**Comment by mattrosno** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-624ca8ad03d709001dc542bf/issues/carbon-design-system/carbon-platform/1027?planning-poker) with ZenHub @aubrey-oneal @kingtraceyj

**Comment by jeanservaas** [comment]
@mattrosno @andreancardona 

Here are the updates for these. I noticed figma is a little different than Sketch if you're using symbols, even though you can't see the canvas around vectors, Figma exports it as white, so I had to break apart some symbols. Hope this works.

[thumb_hover_bugs.zip](https://github.com/carbon-design-system/carbon-platform/files/9339253/thumb_hover_bugs.zip)

**Comment by mattrosno** [comment]
@jeanservaas doing this now.

**Comment by mattrosno** [comment]
@jeanservaas page header is good. Action bar needs fixed. I see you shared page header in that zip, not action bar.

**Comment by jeanservaas** [comment]
Here's action bar @mattrosno 


[missing_thumbs.zip](https://github.com/carbon-design-system/carbon-platform/files/9374488/missing_thumbs.zip)

**Comment by jeanservaas** [comment]
@mattrosno here's the security filter panel pattern

[filter-panel.svg.zip](https://github.com/carbon-design-system/carbon-platform/files/9375788/filter-panel.svg.zip)

**Comment by mattrosno** [comment]
@jeanservaas new tag set still looks like this:
<img width="467" alt="image" src="https://user-images.githubusercontent.com/1691245/185483431-22698a9e-9aa1-491b-a5be-286205f29106.png">

Tag wall still:
<img width="366" alt="image" src="https://user-images.githubusercontent.com/1691245/185483579-cfe1cbb0-42bb-49a5-a659-d06f149ad8a4.png">

Status wall is all white hover background:
<img width="353" alt="image" src="https://user-images.githubusercontent.com/1691245/185483678-9f99c5f7-8c64-4160-8af5-f8568b07ce37.png">

**Comment by jeanservaas** [comment]
aight, i hope these work

[thumbs_revised_2.zip](https://github.com/carbon-design-system/carbon-platform/files/9377511/thumbs_revised_2.zip)
