### ISSUE TITLE
[Left nav]: The L1 retains select state when user collapses and expands L1

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/carbon-platform#1030]
**Description**

L1 Top levels should not have a select state until an L2 is selected and you happen to collapse the L1. THen it should have the section to indicate an item “inside” that L1 is active

**Steps to reproduce**

Click on an L2 item inside an L1 and then collapse that L1 and expand it again. The L2 will lose its select state (it’s the page you’re currently on) and the L1 will retain the select state instead of it being on the L2 you’re on.

![ezgif com-gif-maker-5](https://user-images.githubusercontent.com/32881239/179705334-060cb859-b7e1-47e5-82b5-4c7a6136c403.gif)

**Comment by francinelucca** [comment]
> @francinelucca You’re right. I should have made the issue in the Carbon System repo. Can you move this issue?

https://github.com/carbon-design-system/carbon/issues/11840

**Comment by mjabbink** [comment]
Thanks for moving @francinelucca!

**Comment by francinelucca** [comment]
Closing here as not planned, expecting this to be addressed in carbon upstream
