### ISSUE TITLE
Remove defaults for asset docs paths

### ISSUE THREAD

**Issue by francinelucca** [carbon-design-system/carbon-platform#1035]
**Summary**

The schema currently defines that Asset docs will have default values; If we set defaults the only way we can know if a tab should be rendered is:
- request all those pages (currently five) when rending a single page (asset details or any of the tab) and seeing if they actually exist, this would dramatically increase the amount of network requests and decrease page load time since these are loaded dynamically.
OR
- Request all tab pages when obtaining library assets content, which will result in 5x call per asset per library...
OR
- We could render all the tabs which would result in a large amount of 404 pages since there's no guarantees that the default content actually exists

If we make asset doc paths non-defaults, we enforce the library subscribers to define the docs that they do have and their paths and we can safely render tabs if the key is present in the asset schema without having to do any additional checks.

**Job stories**

What value will this deliver?

1. When I  go into an asset detail page, I want the page to load in a reasonable time and I want to see all the tabs that are available accurately, so I can see all the information that is available to me

**Acceptance criteria**

What requirements must be met to complete this request?

1. Documentation is updated to not show asset docs with default values
2. Schemas are updated to not show asset docs with default values
3. Inheritance still works as expected, regardless of if Docs are supplied or not

**Comment by mattrosno** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-624c3fc8b7972e001130fef7/issues/carbon-design-system/carbon-platform/1035?planning-poker) with ZenHub @alisonjoseph @andreancardona @francinelucca @jdharvey-ibm

**Comment by mattrosno** [comment]
We're keeping defaults, and going to add 1 API call (tree endpoint?) to check for the existence of the defaults, so we know which page tabs to render.
