### ISSUE TITLE
Update side nav items

### ISSUE THREAD

**Issue by mattrosno** [carbon-design-system/carbon-platform#1037]
**Design**

- [x] Specify page header background color and pictogram for Libraries and Design kits catalogs, if those are to not be black with no pictogram

**Dev**

- [x] Move Accessibility and Content into a Guidelines item beneath Elements
<img width="254" alt="image" src="https://user-images.githubusercontent.com/1691245/180289504-9fecc302-2b7b-4582-8a8c-7b05bb509e15.png">

- [x] Move Libraries into the Catalogs section and put Components, Functions, Patterns, Templates under Assets
<img width="256" alt="image" src="https://user-images.githubusercontent.com/1691245/180289677-395228b5-1f8f-46af-96ea-73e5728b8748.png">

- [x] Update the page header to "Data visualization" (no capital V)
<img width="1020" alt="image" src="https://user-images.githubusercontent.com/1691245/180290159-48f6f05d-3b94-43c5-b31f-ff18feeb75f3.png">

- [x] Move FAQ and Content as the last two items in About Carbon section
<img width="255" alt="image" src="https://user-images.githubusercontent.com/1691245/180291018-f36cb41f-4589-4d15-bf33-2a0675ad0f75.png">

- [x] Update "Asset catalog" to "Asset catalogs" (plural) on the home page
<img width="638" alt="image" src="https://user-images.githubusercontent.com/1691245/180293590-7449222c-f484-43db-9308-50ba1cf185f1.png">

**Comment by mattrosno** [comment]
@kingtraceyj @aubrey-oneal do we need to update that second "Data visualization" to "Charts" in the side nav? I see how that works for this example, but what about the generic pattern where we have more collections that have their own pages?

The pattern of duplicating the collection name in both the parent and first item seems to hold up better. If we go with this approach renaming the first item to "Charts", does that mean we'd have to have two names for every collection going forward?

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/1691245/180292188-6d6ad95f-1e3d-42e2-98e8-17749e810dd6.png">

**Comment by mattrosno** [comment]
@kingtraceyj please review.

**Comment by kingtraceyj** [comment]
Design issue for library and catalog headers: https://github.com/carbon-design-system/carbon-platform/issues/1056

Redline (Not currently finished): https://www.figma.com/file/1HS6qRdl4GVY27iiBJWLnU/Banner_Specs?node-id=0%3A1

**Comment by alisonjoseph** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-624c3fc8b7972e001130fef7/issues/carbon-design-system/carbon-platform/1037?planning-poker) with ZenHub @andreancardona @francinelucca @jdharvey-ibm

**Comment by jeanservaas** [comment]
@mattrosno I kind of agree with this... the idea being, that we want to see the name of the collection on that leadspace. 

If we go with Data Viz > Charts... there's no scalable naming formula there. So say, Cloud components is a Collection... what would the name of the first child item be then in that instance? @aubrey-oneal makes a good point that we need to look at other Collections, but I think here we have two clear choices.

1) to get the name of the Collection in the leadspace

2) to follow the current convention and just have that first category be called something more generic like "Catalog"

Notice on the current site, we never have the name "Data Viz" in the leadspace

<img width="930" alt="image" src="https://user-images.githubusercontent.com/43144260/181769195-2487f743-e9d2-48cc-91b2-8c38d5ab0f04.png">
