### ISSUE TITLE
Add anchor links to library detail page

### ISSUE THREAD

**Issue by mattrosno** [carbon-design-system/carbon-platform#1038]
Redline: https://www.figma.com/file/K6HobXD4KXUIdkLrVjUzwK/LibraryDetail_CarbonReact?node-id=0%3A1

- [x] There will always be at minimum one anchor link for "Dashboard"
- [x] Add anchor links as necessary for pages (e.g. there should be no "Contributors" anchor link if there's no "Contributors" heading on the page.)

See red highlight:
<img width="1771" alt="image" src="https://user-images.githubusercontent.com/1691245/180294714-1e749262-3515-4dfe-a940-8137f73c42e6.png">

**Comment by mattrosno** [comment]
@kingtraceyj please review.

**Comment by alisonjoseph** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-624c3fc8b7972e001130fef7/issues/carbon-design-system/carbon-platform/1038?planning-poker) with ZenHub @andreancardona @francinelucca @jdharvey-ibm

**Comment by alisonjoseph** [comment]
@mattrosno if there is just the dashboard, we probably shouldn't show just one anchor link, that would be weird, no?

**Comment by mattrosno** [comment]
@kingtraceyj thoughts on @alisonjoseph's above question?
