### ISSUE TITLE
Add related libraries to library dashboard

### ISSUE THREAD

**Issue by mattrosno** [carbon-design-system/carbon-platform#1039]
Redline: https://www.figma.com/file/K6HobXD4KXUIdkLrVjUzwK/LibraryDetail_CarbonReact?node-id=0%3A1

- [x] If a library is part of a group (defined in `/web-app/data/libraries.mjs`, comma-separate the other libraries and show the display name of each
- [x] Don't include a library if it's `noIndex: true`, because that would be shown below in the Resources section if its inherited
- [x] If the library isn't part of a group, show `–` (just like how we handle assets dashboard if there are no "Tags")

This is so we can cross-link libraries that (should) have the same components, but build with different JavaScript libraries.

See red highlight:
<img width="1771" alt="image" src="https://user-images.githubusercontent.com/1691245/180295133-d1c531da-4b51-4a48-b37a-e6b4caa3d036.png">

**Comment by mattrosno** [comment]
@kingtraceyj please review.

**Comment by jeanservaas** [comment]
Just make sure to look at the card spec for margins and spacing... you need to make that line width wider under "related libraries" 

Note: this is a grab from the Component asset redline... but it's the same right margin... see that the line width can go wider
<img width="569" alt="image" src="https://user-images.githubusercontent.com/43144260/181608751-7b1d0bf8-ec1b-4938-952c-20d7bcec9af1.png">

**Comment by alisonjoseph** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-624c3fc8b7972e001130fef7/issues/carbon-design-system/carbon-platform/1039?planning-poker) with ZenHub @andreancardona @francinelucca @jdharvey-ibm
