### ISSUE TITLE
Add design kit link to detail pages

### ISSUE THREAD

**Issue by mattrosno** [carbon-design-system/carbon-platform#1041]
Redline: https://www.figma.com/file/K6HobXD4KXUIdkLrVjUzwK/LibraryDetail_CarbonReact?node-id=0%3A1

For both library and asset dashboards:

- [x] Label: "Design files"
- [x] Link: "View compatible kits"
- [x] Link takes you to the design kits page for that library

Since libraries always have a design kits page, even if empty, we can safely link to it in both dashboards without conditional logic.

See red highlight:
<img width="1727" alt="image" src="https://user-images.githubusercontent.com/1691245/180297005-8669f47b-4109-4c34-b567-4cde5317c01e.png">

**Comment by mattrosno** [comment]
@kingtraceyj please review.

**Comment by alisonjoseph** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-624c3fc8b7972e001130fef7/issues/carbon-design-system/carbon-platform/1041?planning-poker) with ZenHub @andreancardona @francinelucca @jdharvey-ibm
