### ISSUE TITLE
Update library and asset dashboard primary buttons

### ISSUE THREAD

**Issue by mattrosno** [carbon-design-system/carbon-platform#1042]
Redline: https://www.figma.com/file/K6HobXD4KXUIdkLrVjUzwK/LibraryDetail_CarbonReact?node-id=0%3A1

- [x] The button for both library and asset dashboard primary button should read "View library assets"

See red highlight:
<img width="1771" alt="image" src="https://user-images.githubusercontent.com/1691245/180320011-79dccd40-3043-412a-8e42-30b67c1b1b46.png">

**Comment by mattrosno** [comment]
@aubrey-oneal @kingtraceyj I see the design spec has "View all library assets". Is the "all" necessary? For example, the design kit link says "View compatible kits" not "View all compatible kits".

**Comment by alisonjoseph** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-624c3fc8b7972e001130fef7/issues/carbon-design-system/carbon-platform/1042?planning-poker) with ZenHub @andreancardona @francinelucca @jdharvey-ibm
