### ISSUE TITLE
Update asset dashboard frameworks and tags

### ISSUE THREAD

**Issue by mattrosno** [carbon-design-system/carbon-platform#1049]
Redline: https://www.figma.com/file/vtmHnw9ACgnksFg7ZvEsZC/Component_asset_page_redline?node-id=0%3A1

- [x] Add inline icon next to framework
- [x] If "Design only", don't include an icon (because there is no icon for that)
- [x] Add "Other frameworks", with values coming from library's group matching by asset `id`
- [x] If no other frameworks, do an en dash like when we have no tags
- [x] Remove tags from asset dashboard

See red highlight:
<img width="1771" alt="image" src="https://user-images.githubusercontent.com/1691245/180498761-bea28eb2-2ad5-4ad8-9e69-6c4518f3e9d9.png">

**Comment by mattrosno** [comment]
@kingtraceyj please review.

**Comment by mattrosno** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-624c3fc8b7972e001130fef7/issues/carbon-design-system/carbon-platform/1049?planning-poker) with ZenHub @andreancardona @francinelucca @jdharvey-ibm

**Comment by kingtraceyj** [comment]
Looks good.

Not a blocker but a heads up—after talking with Jeannie and systems squad, design needs to create framework icons that are on the grid to make sure that icons are sized evenly. 

design issue: https://github.com/carbon-design-system/carbon-platform/issues/1057

**Comment by alisonjoseph** [comment]
@kingtraceyj will just use the icons we have now, then when new ones are available we can just replace what we have.
