### ISSUE TITLE
Move external docs link to secondary button

### ISSUE THREAD

**Issue by mattrosno** [carbon-design-system/carbon-platform#1050]
Redline: https://www.figma.com/file/vtmHnw9ACgnksFg7ZvEsZC/Component_asset_page_redline?node-id=0%3A1

For both the library and asset dashboards, if the library or asset has `externalDocsUrl`:

- [x] Button should say "View library docs" and "View asset docs"
- [x] See redline for secondary button across breakpoints (sm - xl)

See red highlight:
<img width="1727" alt="image" src="https://user-images.githubusercontent.com/1691245/180499466-5dc2ff27-7df7-4faa-85fa-f11323fd9679.png">

**Comment by mattrosno** [comment]
@kingtraceyj please review. Are you cool with "View external docs" instead of "View library docs" and "View asset docs"? This is coming from the `externalDocsUrl` schema key; we currently call this "external" in the link; it'd be nice to keep it saying "external" so library and asset maintainers know how that link it set in the schema.

**Comment by mattrosno** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-624c3fc8b7972e001130fef7/issues/carbon-design-system/carbon-platform/1050?planning-poker) with ZenHub @andreancardona @francinelucca @jdharvey-ibm

**Comment by kingtraceyj** [comment]
@mattrosno "View external docs" is fine. Where would the "View library docs" link to? The PAL docs?

**Comment by mattrosno** [comment]
@kingtraceyj yes, we use external docs to link to the PAL sites, to JSDoc sites, etc. Over time, as we index more docs content, we'll be able to remove the external docs button for most libraries and assets.

**Comment by kingtraceyj** [comment]
Yeah. Then I think "View library docs" makes the most sense as well.

**Comment by mattrosno** [comment]
@kingtraceyj okay, I updated the task to:

>Button should say "View library docs" and "View asset docs"

My point was that the schema uses `externalDocsUrl` for "Absolute URL to externally-hosted documentation". Our UI doesn't have to exactly match the wording of the schema, but by omitting "external" from the button text, it isn't as straight forward that a value set in `externalDocsUrl` shows up in "View library docs", but we can update our schema documentation to help inform maintainers of where `externalDocsUrl` shows up in the interface.
