### ISSUE TITLE
Make entire library name clickable in asset dashboard

### ISSUE THREAD

**Issue by mattrosno** [carbon-design-system/carbon-platform#1051]
Redline: https://www.figma.com/file/vtmHnw9ACgnksFg7ZvEsZC/Component_asset_page_redline?node-id=51%3A1664

- [x] Make the library name and version all clickable as one anchor

See red highlight:
<img width="324" alt="image" src="https://user-images.githubusercontent.com/1691245/180500639-0fb59ee8-58f5-4a0b-915c-6ad87a68dfb1.png">

**Comment by mattrosno** [comment]
@kingtraceyj please review.

**Comment by mattrosno** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-624c3fc8b7972e001130fef7/issues/carbon-design-system/carbon-platform/1051?planning-poker) with ZenHub @andreancardona @francinelucca @jdharvey-ibm

**Comment by kingtraceyj** [comment]
Looks good!
