### ISSUE TITLE
Library and design kit catalog colors

### ISSUE THREAD

**Issue by kingtraceyj** [carbon-design-system/carbon-platform#1056]
Now that libraries and design kits have moved to the catalog section, they will need unique colors to differentiate them from other assets.

**Comment by kingtraceyj** [comment]
figma: https://www.figma.com/file/1HS6qRdl4GVY27iiBJWLnU/Banner_Specs?node-id=0%3A1

could potentially use teal 20 for either category.

brand is bringing in some yellow. do they use yellow 20 at all?

**Comment by kingtraceyj** [comment]
Libraries will be Cool gray 20 with `<FileBackup />` icon

![image](https://user-images.githubusercontent.com/20582179/181632755-e5728d8e-96dd-425c-8530-b3298a8cdfad.png)


Design kits will be Teal 20 with `< ArtTools_01 />` icon

![image](https://user-images.githubusercontent.com/20582179/181632801-7da17f5b-4de2-46bd-ad38-c61f4e307a26.png)

**Comment by mattrosno** [comment]
@kingtraceyj is this just for catalogs, or all library pages like:

https://next.carbondesignsystem.com/libraries/carbon-react
https://next.carbondesignsystem.com/libraries/carbon-react/latest/assets
https://next.carbondesignsystem.com/libraries/carbon-react/latest/pages/tutorial/overview

**Comment by kingtraceyj** [comment]
@mattrosno this will be for all library pages.

**Comment by mattrosno** [comment]
@kingtraceyj if all pages in a library by default look like this:
<img width="1392" alt="image" src="https://user-images.githubusercontent.com/1691245/185009214-f26b2cc4-46c6-4e31-b287-2013ef05d64a.png">

But assets in a library have their own colors like this:
<img width="1392" alt="image" src="https://user-images.githubusercontent.com/1691245/185009269-fcd8ca02-9ebc-4837-a35f-7e60ef522949.png">

Does that mean design kits in a library looks like this?
<img width="1392" alt="image" src="https://user-images.githubusercontent.com/1691245/185009312-8715dc06-bac7-40d8-b8d8-ed964f65c016.png">

**Comment by kingtraceyj** [comment]
@mattrosno good question, we should keep the gray header for the design kit page that is within the library side nav.
