### ISSUE TITLE
Update framework icons

### ISSUE THREAD

**Issue by kingtraceyj** [carbon-design-system/carbon-platform#1057]
we need to update framework icons for resource and mini cards to the IBM  grid so that they all have the same visual weight.

icons needed for dashboard as well sized like status indicators.

**Comment by mattrosno** [comment]
Here are the docs for how we add or update custom icons (not coming from Carbon): https://github.com/carbon-design-system/carbon-platform/blob/main/docs/packages-icons.md

**Comment by kingtraceyj** [comment]
- move icons from sketch to figma
- double check size and grid alignment

**Comment by kingtraceyj** [comment]
first batch submitted to brand: https://github.ibm.com/brand/ui-icons/issues/178

will update issue with finalized figma file that includes icons not submitted to brand.

**Comment by kingtraceyj** [comment]
Figma file: https://www.figma.com/file/dTdBnT1kNCnRUFTnU4RaIj/Platform-icons?node-id=0%3A1

This file is very similar to our sketch file. It does not contain any updates I made for brand purposes. It could take brand up to a month to approve the icons or ask for revisions. I recommend not updating any icons until brand approves or requests changes to minimize updates. Once approved, I will update this Figma file with the official svgs. Even after approval it does take some time for these to end up in the repo, so we can decide then whether or not to update our repo or wait until they are publicly available.

If you do not see an icon or pictogram that was in the previous sketch file, that is because the icon or pictogram is now available in the IBM icons or pictograms. Reach out if you can't find it!
