### ISSUE TITLE
Library side nav visual fixes

### ISSUE THREAD

**Issue by kingtraceyj** [carbon-design-system/carbon-platform#1059]
There are 2 visual bugs in the library side nav. Redlines for library (LHN is on the left side of file)

Hover state should be a link style:
![image.png](https://images.zenhubusercontent.com/579a6affe40e5714b16cabd9/61a372bd-84e5-4372-9f99-a30deb1e16c0)

add 8px padding under the Library Name and version bottom rule (above the assets button):
![image.png](https://images.zenhubusercontent.com/579a6affe40e5714b16cabd9/7f6b0fda-6117-4c25-bca9-f8911c780dd5)

**Comment by mattrosno** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-624c3fc8b7972e001130fef7/issues/carbon-design-system/carbon-platform/1059?planning-poker) with ZenHub @andreancardona @francinelucca @jdharvey-ibm
