### ISSUE TITLE
Page tabs container is offset by one scrollbar-width

### ISSUE THREAD

**Issue by jdharvey-ibm** [carbon-design-system/carbon-platform#1078]
**Description**

When viewing a page with a page tabs component on it, if the page's content has a scrollbar, it pushes the tabs container over to the left by the width of a scrollbar.

<img width="1038" alt="image" src="https://user-images.githubusercontent.com/51208233/181604823-387f9d68-aaff-42b1-a295-bbe9400c34ec.png">

<img width="1500" alt="image" src="https://user-images.githubusercontent.com/51208233/181605515-6aa78925-eb68-4c1f-9d53-1516f85dee32.png">

![Image from iOS](https://user-images.githubusercontent.com/51208233/181604888-bd8f5d51-59b0-480d-b935-91a25dbfdbdd.jpg)

**Steps to reproduce**

Example page: https://next.carbondesignsystem.com/elements/accessibility/overview
Windows - should be visible without extra config
Mac - Go into "settings -> general -> show scroll bars" and set it to "always".

Tried both Chrome and Edge on Mac, and Edge on Windows.

**Comment by mattrosno** [comment]
I'd check out how we use `--scrollbar-width` to offset scroll bar widths. Maybe that will help.

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/1691245/181629959-124b4920-3ca2-41fe-ae9b-d86ad1e46823.png">
