### ISSUE TITLE
Storybook Sass compile error

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon-platform#1079]
![image](https://user-images.githubusercontent.com/2753488/181619823-dd9b337f-4f00-42e8-ab05-5319c9024491.png)

**Comment by mattrosno** [comment]
I'd look at `services/web-app/.storybook/main.js`. We'll probably have to add a `config.resolve` to handle the `~` in `@use` statements. Or, don't use `~` and use a path to that file in the use statements.

**Comment by mattrosno** [comment]
@alisonjoseph ah! Nevermind. I see you just did the later in that PR.
