### ISSUE TITLE
Create landing page illustrations

### ISSUE THREAD

**Issue by aubrey-oneal** [carbon-design-system/carbon-platform#1095]
This sprint we are updating our landing page, which has brought about the need for additional illustration work. 

Prototype
https://www.figma.com/file/xjGZCRt3G7S0EXO7Bt4Vtq/v1_Landing_page_revisions?node-id=0%3A1

Illustrations needed:

- [ ] How Carbon Works illustration. This should help people understand that the page will introduce them to the ecosystem and give some definitions. Perhaps imagery of a network?
- [ ] Carbon React feature card. We have an old illustration that uses black. Can we make this lighter (i.e. color scheme of data visualization.)
- [ ] IBM Web Components feature card. This is new. Perhaps it could point towards the editorial/content nature of these components.
- [ ] Roadmap illustration. @jeanservaas will make this image based on the previous roadmap illustrations.

**Comment by jeanservaas** [comment]
@thyhmdo 

A few things to consider that we discussed with @mjabbink 

1. All the illustrations on the page will need to work together in harmony (with the hero image as well), so it will be easier to start assessing illustration styles once we start seeing things together. It will also help us to keep things very simple...i.e. maybe the library illustrations have a bit more detail but the 'How Carbon Works' image is much more abstract...so people don't get overloaded.

For instance something like this could work for the How Carbon Works image... as something too diagrammatic might be really messy in conjunction with the hero images and the library images.

<img width="551" alt="image" src="https://user-images.githubusercontent.com/43144260/182212803-c21a83d5-4d67-4780-bb07-f42532b9545e.png">

We did talk about something more in this direction too for the How Carbon Works (more of an expressive network), which could work but again, might get too busy:
<img width="1134" alt="image" src="https://user-images.githubusercontent.com/43144260/182213333-2424920a-72c8-4255-a706-bcc5cc6a500b.png">


2. It might help actually to start with the library illustrations and then work back to the How Carbon works illustration depending on what you come up with. Right now, we want to move away from the black of the Carbon React library image... and frankly, the white of the Carbon for ibm.com image... wondering if we can use something other than stark color contrast to differentiate these libraries... maybe we don't even show the component illustrations at all.
