### ISSUE TITLE
Convert MDX components in web-app to `mdx-components` package

### ISSUE THREAD

**Issue by jdharvey-ibm** [carbon-design-system/carbon-platform#1103]
🦖@alisonjoseph
🐳 @francinelucca 
🐯@jdharvey-ibm
🐢 @andreancardona 

## Markdown components

- [x] h1: H1 🐳 
- [x] h2: H2 🐳 
- [x] h3: H3 🐳 
- [x] h4: H4 🐳 
- [x] h5: H5 🐳 
- [x] h6: H6 🐳 
- [x] p: P 🐳 
- [x] ol: OL 🐢 
- [x] li: LI 🐢 
- [x] #1457
- [x] a: Link 🐳 
- [x] blockquote: Blockquote 🐳
- [x] table: PageTable 🐳 
- [x] pre: Code 🐳 -- ⚠️ SB `[Object object]` issue

##  Core Carbon components

Q: Why are these here? Why are the carbon components as-is not sufficient to host our carbon documentation and other MDX? Can these be removed in favor of the base carbon components?

- [x] AccordionItem
- [x] Button
- [x] StructuredListWrapper
- [x] StructuredListHead
- [x] StructuredListRow
- [x] StructuredListCell
- [x] StructuredListBody
- [x] UnorderedList
- [x] ListItem
- [x] Tag

## Gatsby theme components

- [x] Accordion 🦖
- [x] AnchorLink 🐯
- [x] AnchorLinks 🐯
- [x] ArtDirection 🦖
- [x] ArticleCard  🐳🐢
- [x] Aside 🦖
- [x] AutolinkHeader 🐳 
- [x] Caption 🦖
- [x] CardGroup 🦖
- [x] ColorBlock🐯
- [x] Column 🦖
- [x] DoDont 🦖
- [x] DoDontRow 🦖
- [x] Divider 🦖
- [x] GifPlayer 🐳 
- [x] Grid 🦖
- [x] ImageWrapper 🐳 
- [x] InlineNotification 🐢
- [x] MiniCard 🐳🐢
- [x] PageDescription 🐳 
- [x] Preview 🐢 
- [x] Profile 🐳 
- [x] ResourceCard 🐳  
- [x] Row 🦖
- [x] StorybookDemo 🦖 -- ⚠️ lint error needs fixing -- Fixed!
- [x] Tab 🐯
- [x] Tabs 🐯
- [x] Title🐯
- [x] Video🐯

### Internal Components
- [x] ColorGrid 🐢 
- [x] ColorPalette 🐢 
- [ ] StatusIndicatorTable -- ⚠️ need help with '/status-icon' svgs import
- [x] TypeScaleTable 🦖
- [x] TypeWeight 🦖

### Deferred
-  img: Image -- ⚠️ Deferred
- Image -- ⚠️ Deferred
- MdxIcon 🐳  -- ⚠️ Deferred

### Convert to js pages (https://github.com/carbon-design-system/carbon-platform/issues/1446)
- ColorTokenTable 
- Glossary
- IconLibrary
-  PictogramLibrary -
- TypesetStyle

**Comment by alisonjoseph** [comment]
> Why are these here? Why are the carbon components as-is not sufficient to host our carbon documentation and other MDX? Can these be removed in favor of the base carbon components?

These are just using the core Carbon components without modification, they are imported into the components file so they can be using within any mdx file without importing at the top. (required currently to import some mdx files direct from the Carbon website). Is there a better way to make certain core components easily available for use?

**Comment by jdharvey-ibm** [comment]
@alisonjoseph Okay awesome. I think with some of this remote mdx work we're doing, we'll be able to keep that no-need-to-import behavior and wrap up things even more concisely in the mdx-components package (by just re-exporting some of the carbon components as an esmodule).

**Comment by alisonjoseph** [comment]
Question, do we want customized site-specific mdx components in this package? For example the following components are specific to the core Carbon docs, and wouldn't be easily reused. If we do want them in here perhaps we can categorize them differently in the storybook?


- ColorGrid
- ColorTokenTable
- Glossary
- IconLibrary
- PictogramLibrary
- StatusIndicatorTable
- TypeScaleTable
- TypeSetStyle
- TypeWeight

**Comment by francinelucca** [comment]
My thought is we probably don't need them to be available to everyone so I wouldn't put them on mdx-components off the bat. 
Unless there's a technical constraint in which ALL components rendered by mdx remote pages need to live in the mdx-components package, then I guess we'd have no choice since we'll use them for our own remote pages. 
@jdharvey-ibm is there a constraint to do that?

**Comment by jdharvey-ibm** [comment]
@francinelucca @alisonjoseph Ideally we *would* have all of the components that are rendered via MDX included in the mdx-components package. That enables us to do things like offload the rendering of the MDX to a separate service so we can cache things asynchronously.

It might not make sense from a user perspective to have these ancillary components in the storybook as well, since we wouldn't really expect others to use them, but from a Platform technical perspective, that'll be super beneficial to have them all in that package.

I like the idea of having them be in a separate category in the storybook, or we could even have a separate storybook build altogether which hides them in the one that is hosted on platform.carbondesignsystem.com.

**Comment by alisonjoseph** [comment]
@jdharvey-ibm that makes sense to bring them over then, What about an "Internal" category in storybook for those components? Adding another separate storybook seems like adding unnecessary complexity.

**Comment by jdharvey-ibm** [comment]
@alisonjoseph That'd be perfect!

**Comment by francinelucca** [comment]
I'm confused as to what component we mean by "MdxWrapper" , is that the `MdxPage` ? that seems like it has a lot of dependencies with the web app 🤔  (nav data, exceptions, pageheaders...)

**Comment by alisonjoseph** [comment]
@francinelucca did we rename MdxWrapper, I don't see it anymore. If its the page, then I think that stays in the web-app.
