### ISSUE TITLE
Update indexed library descriptions

### ISSUE THREAD

**Issue by aubrey-oneal** [carbon-design-system/carbon-platform#1109]
Update library descriptions based on 'Final' column in the following airtable: https://airtable.com/shrdwElZNyJdGtZkS/tblE2Y75BfY0Z0T2O

These descriptions should show up as the same in both the library catalog and library overview page. Some of the Carbon configs that needed updated.

- [x] https://github.com/carbon-design-system/carbon-charts/blob/master/packages/angular/carbon.yml#L5
- [x] https://github.com/carbon-design-system/carbon-charts/blob/master/packages/core/carbon.yml#L5
- [x] https://github.com/carbon-design-system/carbon-charts/blob/master/packages/react/carbon.yml#L5
- [x] https://github.com/carbon-design-system/carbon-charts/blob/master/packages/svelte/carbon.yml#L5
- [x] https://github.com/carbon-design-system/carbon-charts/blob/master/packages/vue/carbon.yml#L5
- [x] https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/packages/react/carbon.yml#L5
- [x] https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/packages/web-components/carbon.yml#L5
- [x] https://github.com/carbon-design-system/carbon/blob/main/packages/react/carbon.yml#L4

**Comment by mattrosno** [comment]
@andreancardona do you think you'll be able to take this on this week? If so, let's estimate it and move it to the sprint backlog pipeline. If not, can you remove it from sprint 22 and move it to ready for estimates pipeline?

**Comment by mattrosno** [comment]
@andreancardona @aubrey-oneal I'll take this issue.
