### ISSUE TITLE
Navigable elements in left-nav are not anchor links

### ISSUE THREAD

**Issue by jdharvey-ibm** [carbon-design-system/carbon-platform#1124]
**Description**

I noticed when trying to middle click a left-nav link to open it in a new tab, that the navigation elements in the nav are not anchor links, but are instead `div`s inside of `li`s.

I haven't looked into the code, but I think what might need to happen is that if a tree node has no "items" (i.e. it is a leaf node), it should instead be rendered as an anchor.

**Comment by mattrosno** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-624c3fc8b7972e001130fef7/issues/carbon-design-system/carbon-platform/1124?planning-poker) with ZenHub @alisonjoseph @andreancardona @francinelucca @jdharvey-ibm

**Comment by mattrosno** [comment]
See if we can fix in `nav-tree.js` or if not, or if there isn't an upstream component prop to set the element, then open an issue in the `carbon` repo for the request.

**Comment by alisonjoseph** [comment]
We should be able to render anything in the TreeNode label, not just text. So adding the link there instead of "onClick" should fix this.
