### ISSUE TITLE
Dropdown style overrides need fixing

### ISSUE THREAD

**Issue by mattrosno** [carbon-design-system/carbon-platform#1125]
**Description**

I'm seeing broken dropdown overrides in the assets table:
<img width="575" alt="image" src="https://user-images.githubusercontent.com/1691245/183736947-7b9f3b0d-dcda-4a00-838e-9e14f3139604.png">

It should look like this:
<img width="488" alt="image" src="https://user-images.githubusercontent.com/1691245/183737042-0760d415-5886-45e8-a9da-4647be8cb12d.png">

Same with catalog sort:
<img width="364" alt="image" src="https://user-images.githubusercontent.com/1691245/183737144-fe0e5748-86c2-4df8-838a-61eedfb5d099.png">

It should look like this:
<img width="406" alt="image" src="https://user-images.githubusercontent.com/1691245/183737203-7d19a5a8-8a5f-4672-ac09-10c229d04459.png">

This could be happening in other places too; I didn't exhaustively search for all dropdowns in the web app.

**Steps to reproduce**

I'm not seeing this on production. I'm seeing it on localhost.

**Comment by mattrosno** [comment]
@carbon-design-system/carbon-platform-devs can somebody recreate / confirm this bug?

**Comment by francinelucca** [comment]
confirm! I can see this locally, not in prod, maybe we introduced it this sprint? we can do a test deployment to test 👀

**Comment by alisonjoseph** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-624c3fc8b7972e001130fef7/issues/carbon-design-system/carbon-platform/1125?planning-poker) with ZenHub @andreancardona @francinelucca @jdharvey-ibm
