### ISSUE TITLE
Code component has a dark background

### ISSUE THREAD

**Issue by francinelucca** [carbon-design-system/carbon-platform#1129]
See http://localhost:3000/mdx#code
![image](https://user-images.githubusercontent.com/40550942/184218744-7fe617e0-9569-4402-a307-1123968e7b6c.png)

**Comment by kingtraceyj** [comment]
i was also noticing this this morning in the schema page: https://next.carbondesignsystem.com/contributing/schema#stable-version

![image](https://user-images.githubusercontent.com/20582179/185149272-4953752e-b786-4980-946d-c3f1dc94ccd0.png)

**Comment by mattrosno** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-624c3fc8b7972e001130fef7/issues/carbon-design-system/carbon-platform/1129?planning-poker) with ZenHub @alisonjoseph @andreancardona @francinelucca @jdharvey-ibm

**Comment by francinelucca** [comment]
Need to move this out of review/Qa, should it go to backlog or estimates? 🤔 @mattrosno

**Comment by mattrosno** [comment]
@francinelucca I put it back in the backlog. Top of the list as a v1 issue.
