### ISSUE TITLE
Library Sidenav visual error when scrollbar: always setting set

### ISSUE THREAD

**Issue by francinelucca** [carbon-design-system/carbon-platform#1147]
**Description**

Tell us more about the problem that you're running into. What did you see? What did you expect to
see?

When scrollbars are always visible, the inner navigation of the library sidenav looks askew

<img width="1521" alt="image" src="https://user-images.githubusercontent.com/40550942/185171132-11eb6afe-aa4e-43f1-8af8-2aea2291a73f.png">

**Steps to reproduce**

Steps to reproduce

Example page: https://next.carbondesignsystem.com/libraries/carbon-react/latest
Mac - Go into "settings -> general -> show scroll bars" and set it to "always".

**Comment by jdharvey-ibm** [comment]
Fix should be to set this to `overflow: auto` instead of `scroll`
<img width="196" alt="image" src="https://user-images.githubusercontent.com/51208233/185182655-91aad6eb-0cc5-45a8-87be-bd2721e4f38e.png">
