### ISSUE TITLE
Catalog filter dropdown line

### ISSUE THREAD

**Issue by kingtraceyj** [carbon-design-system/carbon-platform#1153]
The current filter has the second line only extending half way down the filter: 
![Screen Shot 2022-08-18 at 9 26 50 AM](https://user-images.githubusercontent.com/20582179/185421511-c53701ff-d9f6-4be3-aa90-a33b4eac65ab.png)

it should extend the length of the filter with 32px `$spacing-07`:
![image](https://user-images.githubusercontent.com/20582179/185421929-9a6bf6d1-7174-4d22-aba3-71ef0073d570.png)

**Comment by mattrosno** [comment]
At different breakpoints, add spacer elements as necessary.

**Comment by mattrosno** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-624c3fc8b7972e001130fef7/issues/carbon-design-system/carbon-platform/1153?planning-poker) with ZenHub @alisonjoseph @andreancardona @francinelucca @jdharvey-ibm
