### ISSUE TITLE
Icon color in Library assets table

### ISSUE THREAD

**Issue by kingtraceyj** [carbon-design-system/carbon-platform#1154]
Change the icon color in the Library assets table (last column) from interactive to `$icon-primary`

Current: 
![image](https://user-images.githubusercontent.com/20582179/185422677-aed1bbf3-b9a6-48fd-b0ae-b2a44c0a9ebe.png)

Desired:
![image](https://user-images.githubusercontent.com/20582179/185422842-d7c87dc2-98a2-4d39-8e4f-bb57ddfd64e5.png)

**Comment by francinelucca** [comment]
is this a duplicate of #1139 ?

**Comment by mattrosno** [comment]
Duplicate.
