### ISSUE TITLE
Components which render an iframe should be sandboxed and not allow arbitrary prop drilling/spreading

### ISSUE THREAD

**Issue by jdharvey-ibm** [carbon-design-system/carbon-platform#1172]
- [x] The `Preview` component should be updated to only allow specific props to be set on the resulting iframe and not spread incoming props via `{...props}`.
- [x] The iframe rendered by the `Preview` component should have a `sandbox` attribute set with the provided below. This value should not be overridable via props.
- [x] The iframe rendered by the `StorybookDemo` component should have a `sandbox` attribute set with the provided below. This value should not be overridable via props.
- [x] The iframe rendered by the `Video` component should have a `sandbox` attribute set with the provided below. This value should not be overridable via props.

### Props to consider for iframe

- height
- title
- src

## Sandbox attribute

`sandbox="allow-forms allow-scripts"`

Reference: https://www.w3schools.com/tags/att_iframe_sandbox.asp

**Comment by alisonjoseph** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-624c3fc8b7972e001130fef7/issues/carbon-design-system/carbon-platform/1172?planning-poker) with ZenHub @francinelucca @jdharvey-ibm

**Comment by alisonjoseph** [comment]
@jdharvey-ibm codesandbox embeds don't seem to work without `sandbox="allow-same-origin"`

**Comment by jdharvey-ibm** [comment]
Okay allow-same-origin is safe to add. I had a bad understanding of what allow-same-origin was doing. I was thinking it allowed the embedded content to be treated as though it was coming from the same origin as the parent, but it instead allows requests from within the iframe to be treated as though they are coming from the site *the iframe is actually displaying*. (e.g. a vimeo iframe making a request to vimeo.com to get data about the embedded video).

**Comment by alisonjoseph** [comment]
Thanks @jdharvey-ibm
