### ISSUE TITLE
Add GH token to prod deployment

### ISSUE THREAD

**Issue by jdharvey-ibm** [carbon-design-system/carbon-platform#1175]
We're not currently using a GH token on prod. We should add one created under the carbon-bot account with no oauth scopes selected and add it to the running app env on code engine.

**Comment by alisonjoseph** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-624c3fc8b7972e001130fef7/issues/carbon-design-system/carbon-platform/1175?planning-poker) with ZenHub @francinelucca @jdharvey-ibm

**Comment by jdharvey-ibm** [comment]
Added to the prod deployment.
