### ISSUE TITLE
Web-App: component catalog, broken filter by "Community" 

### ISSUE THREAD

**Issue by francinelucca** [carbon-design-system/carbon-platform#1204]
**Description**

Tell us more about the problem that you're running into. What did you see? What did you expect to
see?

We definitely have assets that are community maintained indexed, yet when we filter by community it's coming up as zero results.

*  Consider doing something like this for libraries to guarantee every lib has a maintainer https://github.com/carbon-design-system/carbon-platform/blob/main/services/web-app/data/design-kits.js#L155
* Given ^, consider refatoring/cleaning up this logic since maintainer will be guaranteed https://github.com/carbon-design-system/carbon-platform/blob/main/services/web-app/components/asset-catalog-item/asset-catalog-item.js#L56 (56-60)

**Steps to reproduce**

How do we reproduce the error? Please be as specific as you can.

1. https://next.carbondesignsystem.com/assets/components?maintainer[]=community, notice no results

**Comment by mattrosno** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-624c3fc8b7972e001130fef7/issues/carbon-design-system/carbon-platform/1204?planning-poker) with Zenhub @alisonjoseph @andreancardona @francinelucca @jdharvey-ibm
