### ISSUE TITLE
Investigate global wrapper component for page padding-top

### ISSUE THREAD

**Issue by jdharvey-ibm** [carbon-design-system/carbon-platform#1215]
Looks like we lost the correct padding at the top of the page when switching from mdx to js page. Wondering if we should move this style to a global wrapper, although may add incorrect spacing to other pages if we do that. Can probably look at that in a different issue unless its an easy fix.

![Screen Shot 2022-09-01 at 9 56 19 AM](https://user-images.githubusercontent.com/2753488/187946150-2101a2d9-3239-4ac4-b22e-536fde8b6251.png)

![Screen Shot 2022-09-01 at 9 58 20 AM](https://user-images.githubusercontent.com/2753488/187946385-6f75d445-d4a0-402b-b7a8-1d18e4af80e6.png)

Everything else is running / working great!

_Originally posted by @alisonjoseph in https://github.com/carbon-design-system/carbon-platform/pull/1205#pullrequestreview-1093558542_

**Comment by mattrosno** [comment]
Here's an example with 3 different elements contributing to the top spacing: https://next.carbondesignsystem.com/libraries/carbon-react/latest/assets/accordion/style

**Comment by alisonjoseph** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-624c3fc8b7972e001130fef7/issues/carbon-design-system/carbon-platform/1215?planning-poker) with Zenhub @andreancardona @francinelucca @jdharvey-ibm
