### ISSUE TITLE
Web App: Asset tabs without valid source NullPointer

### ISSUE THREAD

**Issue by francinelucca** [carbon-design-system/carbon-platform#1219]
**Description**

Tell us more about the problem that you're running into. What did you see? What did you expect to
see?

<img width="1045" alt="image" src="https://user-images.githubusercontent.com/40550942/188193476-544844d2-5b80-4c5e-8b2c-1b066d9bc6d7.png">
<img width="1224" alt="image" src="https://user-images.githubusercontent.com/40550942/188195706-9f68d14f-a8ad-4686-b275-8b5544367b65.png">

Offending line , FIX: optional chaining
<img width="842" alt="image" src="https://user-images.githubusercontent.com/40550942/188192064-ee62eba1-636d-4aed-96a1-ec5de9f3d63f.png">

**Steps to reproduce**

How do we reproduce the error? Please be as specific as you can.

1. Find a page with an import statement or anything that will result in a full page error
2. render it as an asset page tab
3. see error

**Comment by francinelucca** [comment]
@mattrosno v1? 😳

**Comment by mattrosno** [comment]
Since this breaks the full page, let's try to fix it for v1.

**Comment by alisonjoseph** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-624c3fc8b7972e001130fef7/issues/carbon-design-system/carbon-platform/1219?planning-poker) with Zenhub @andreancardona @francinelucca @jdharvey-ibm

**Comment by francinelucca** [comment]
look into title, description and keyword ability to be undefined
