### ISSUE TITLE
Research prod load times

### ISSUE THREAD

**Issue by francinelucca** [carbon-design-system/carbon-platform#1223]
**Description**

Tell us more about the problem that you're running into. What did you see? What did you expect to
see?

Some pages taking 20+ seconds to load, look into reproducing locally and adding some logs to see exactly where the issue is an potentially remediate

<img width="1250" alt="image" src="https://user-images.githubusercontent.com/40550942/188748726-3ae2e6b7-ad43-4e1c-8ec7-7c1efa19052c.png">

*** this is NOT a github token issue
<img width="210" alt="image" src="https://user-images.githubusercontent.com/40550942/188748434-f8df5ba1-dbfb-4afd-8a6f-e4415a7f4c06.png">

**Steps to reproduce**

How do we reproduce the error? Please be as specific as you can.

https://next.carbondesignsystem.com/libraries/carbon-react/latest/assets/accordion

**Comment by francinelucca** [comment]
@mattrosno added to v1, that ok? I intend to work on this tomorrow

**Comment by mattrosno** [comment]
@francinelucca sounds great, thank you.

**Comment by francinelucca** [comment]
Confirmed can reproduce locally with `npm run start:proxy`
<img width="1103" alt="image" src="https://user-images.githubusercontent.com/40550942/188980107-8f2b5f80-f1fb-4e99-bf09-0ccb861853cc.png">

**Comment by francinelucca** [comment]
10s to get libraryData, 59s to get other frameworks 🤔 
<img width="1334" alt="image" src="https://user-images.githubusercontent.com/40550942/188995779-2d9a06fa-03a7-4f7b-9279-2f4a3f9c7315.png">

**Comment by francinelucca** [comment]
5s to getLibraryData, 49s to get other frameworks (on second load)
<img width="1248" alt="image" src="https://user-images.githubusercontent.com/40550942/188995995-6516e36a-9cf2-4025-964e-7984e1f77f1f.png">

**Comment by francinelucca** [comment]
This issue can be replicated by running a local docker build and then running a container
1 - `CARBON_RUN_MODE=STANDARD node packages/micromanage docker --build @carbon-platform/web-app`
2 - `docker run --env CARBON_RUN_MODE=DEV --env GITHUB_TOKEN=[TOKEN_HERE] -p 8080:8080 us.icr.io/carbon-platform/web-app:0.2.35`

**Comment by francinelucca** [comment]
Update: it was confirmed that the extra load time is due to `getOtherAssetFrameworks` having to resolve the design kit references (which we weren't caching) everytime the page loads and for every library (if a library belongs to a group with 5 other libraries, that's 5 libraries * amount of references in carbon.yml). Merged in #1203 and deployed and see a reduction in load time from ~30s to ~3s in prod.

3s is still higher than where we'd want it to be.

Next steps: adding a considerable amount of logs and using `withTrace` function in #1243 to further investigate delay times in prod.

**Comment by mattrosno** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-624c3fc8b7972e001130fef7/issues/carbon-design-system/carbon-platform/1223?planning-poker) with Zenhub @alisonjoseph @andreancardona @francinelucca @jdharvey-ibm
