### ISSUE TITLE
Refactor community assets section of current Carbon website

### ISSUE THREAD

**Issue by kingtraceyj** [carbon-design-system/carbon-platform#1234]
Currently the Carbon website [Community index section](https://carbondesignsystem.com/community/component-index/) is out of date. We would like to update this to reflect our new carbon platform 

- Remove current content from community index—out of date and not needed. 
- Point user to [Carbon platform](https://next.carbondesignsystem.com/) in the community index 
- Review community asset content to see what content needs to be changed or removed

**Comment by kingtraceyj** [comment]
Figma: https://www.figma.com/file/nwqobPLCIzp2O6CTprT4zh/CommunityAssets?node-id=1%3A3160

**Comment by kingtraceyj** [comment]
@jeanservaas @aubrey-oneal

**Comment by aagonzales** [comment]
Final designs here:
https://www.figma.com/file/nwqobPLCIzp2O6CTprT4zh/CommunityAssets?node-id=23%3A796

## Changes

**Overview**
- Update content
- Add notification
- Add image

**Community index**
- Remove the index component and all functionality on the "Community index" tab
- Remove the tab "Contribute a component" and delete its content 
- Add new content, notifications and tiles

**Patterns**
- Add notification

**Domain Guidance**
- No changes need atm

**Comment by mattrosno** [comment]
@aagonzales I created a cross-linked a dev issue to make this happen.
