### ISSUE TITLE
Link to Carbon platform from current Carbon website

### ISSUE THREAD

**Issue by kingtraceyj** [carbon-design-system/carbon-platform#1235]
Once we launch v1, we need to link to the [new Platform](https://next.carbondesignsystem.com/) from our [current carbon website](https://carbondesignsystem.com/)

Callout designs discussed for the current Carbon website:
- Banner
- Tile
- Homepage callout

Since we are not completely replacing PALs just yet and nothing is being deprecated, the callout does not need to be too flashy. We will also be replacing the community index with platform information #1234 

Related: #447

**Comment by kingtraceyj** [comment]
https://github.com/carbon-design-system/carbon-website/issues/3146

**Comment by aagonzales** [comment]
[Figma file](https://www.figma.com/file/H3kWgBYKdMzov7LIZ1BlHa/Next-crosslinks?node-id=1%3A7738) with exploration.

**Comment by mattrosno** [comment]
@kingtraceyj is this something that we want to get done in carbon-website repo prior to 9/30? If so, let's add this to the v1.0 release to properly track it.

**Comment by aagonzales** [comment]
@mattrosno @alisonjoseph Here are the two dev issues to complete this complete this issue. They need an estimate and assignee. There is a banner for both the Main and Next homepages to link across.

- Main homepage banner: https://github.com/carbon-design-system/carbon-platform/issues/1365
- Next homepage banner: https://github.com/carbon-design-system/carbon-website/issues/3179

**Comment by aagonzales** [comment]
Both banners have been deployed!
