### ISSUE TITLE
Add hover state to homepage content

### ISSUE THREAD

**Issue by kingtraceyj** [carbon-design-system/carbon-platform#1246]
We should add a hover state to Start designing and Start developing to show interaction:
![image](https://user-images.githubusercontent.com/20582179/189376373-f2232237-162e-4247-bd98-73b985728068.png)

Purple hover: #7822fb

Blue hover: #0043ce (link-primary-hover)

IDL hover colors: https://carbon-elements.netlify.app/colors/examples/preview/

**Comment by mattrosno** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-624c3fc8b7972e001130fef7/issues/carbon-design-system/carbon-platform/1246?planning-poker) with Zenhub @alisonjoseph @andreancardona @francinelucca @jdharvey-ibm
