### ISSUE TITLE
Replace ALL straight quotes with apostrophe and curly quotes +

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/carbon-platform#1249]
https://next.carbondesignsystem.com/contributing/schema

- [ ] Replace single straight quote with an apostrophe throughout the page

- [ ] Replace hyphen (-) with an en dash (–) 

make en dash
<img width="243" alt="Screen Shot 2022-09-09 at 12 38 59 PM" src="https://user-images.githubusercontent.com/32881239/189412325-0c945a6c-bf48-45ef-967d-97400310c416.png">

Should be apostrophes

<img width="258" alt="Screen Shot 2022-09-09 at 12 38 10 PM" src="https://user-images.githubusercontent.com/32881239/189412540-f243cc59-0788-419d-8133-d8aaa6af3f12.png">
<img width="207" alt="Screen Shot 2022-09-09 at 12 38 15 PM" src="https://user-images.githubusercontent.com/32881239/189412543-316fecc0-b4a4-4d44-8076-c6b28219fcd5.png">
<img width="290" alt="Screen Shot 2022-09-09 at 12 38 33 PM" src="https://user-images.githubusercontent.com/32881239/189412544-0db35bde-75b6-47f3-a89c-6b97b23a9ddc.png">
<img width="253" alt="Screen Shot 2022-09-09 at 12 38 42 PM" src="https://user-images.githubusercontent.com/32881239/189412545-8453bf76-a6f4-4666-b43e-2f6c6f426459.png">
<img width="308" alt="Screen Shot 2022-09-09 at 12 39 06 PM" src="https://user-images.githubusercontent.com/32881239/189412546-e1bdf505-4428-411d-9c4b-5cff0ed0dcd7.png">

**Comment by alisonjoseph** [comment]
Quotes will be addressed in https://github.com/carbon-design-system/carbon-platform/issues/721 - need to update hyphen to en-dash
