### ISSUE TITLE
Use apostrophe

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/carbon-platform#1250]
https://next.carbondesignsystem.com/libraries/carbon-components-angular

<img width="548" alt="Screen Shot 2022-09-09 at 3 09 59 PM" src="https://user-images.githubusercontent.com/32881239/189435203-d44071bd-2c75-4a86-86c1-2069a0aab1ed.png">

<img width="662" alt="Screen Shot 2022-09-09 at 3 10 02 PM" src="https://user-images.githubusercontent.com/32881239/189435207-c40a1e45-39e0-4463-948b-586d80d3a63e.png">

**Comment by mjabbink** [comment]
here too. Probably in all cases where there’s “Carbon’s”
https://next.carbondesignsystem.com/libraries/carbon-react

**Comment by mjabbink** [comment]
It’s also in the small text on the [Libraries ](https://next.carbondesignsystem.com/libraries)page

<img width="311" alt="Screen Shot 2022-09-09 at 3 14 56 PM" src="https://user-images.githubusercontent.com/32881239/189435917-bd5a19cc-b7d4-4f86-b11a-63ed14ea91a2.png">
<img width="354" alt="Screen Shot 2022-09-09 at 3 15 04 PM" src="https://user-images.githubusercontent.com/32881239/189435918-b9998253-7078-4384-ab40-4b72c52f7b4a.png">

**Comment by mjabbink** [comment]
Here
https://next.carbondesignsystem.com/libraries/ibm-cloud-cognitive

<img width="368" alt="Screen Shot 2022-09-09 at 3 16 49 PM" src="https://user-images.githubusercontent.com/32881239/189436164-700cd283-c6b2-4722-8069-eeb1a5112cca.png">

<img width="360" alt="Screen Shot 2022-09-09 at 3 17 11 PM" src="https://user-images.githubusercontent.com/32881239/189436167-dbd9cb1b-0c99-473c-ba7f-9a5dee96de95.png">

**Comment by kingtraceyj** [comment]
tracking straight quote bugs in this #1378 design issue that will be globally resolved in #721
