### ISSUE TITLE
Replace straight w/ apostrophes and remove italics

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/carbon-platform#1251]
https://next.carbondesignsystem.com/guidelines/content/overview

- [ ]  Replace single straight quotes w/ apostrophes. THroughout page.

- [ ] Remove italics (see below)

<img width="436" alt="Screen Shot 2022-09-09 at 3 49 05 PM" src="https://user-images.githubusercontent.com/32881239/189443038-0479564d-9449-4cb6-a37c-7621ada5a188.png">

<img width="171" alt="Screen Shot 2022-09-09 at 3 49 15 PM" src="https://user-images.githubusercontent.com/32881239/189443043-869d7a71-6a9d-40bd-bdaa-1e60b984f5d4.png">

No italic needed here:

<img width="293" alt="Screen Shot 2022-09-09 at 3 49 19 PM" src="https://user-images.githubusercontent.com/32881239/189442951-2eeb45af-6d88-4c65-895c-7b810b9d64e5.png">

**Comment by kingtraceyj** [comment]
tracking straight quote bugs here

tracking italics here #1327
