### ISSUE TITLE
Type fixes on this page (hyphens to en dash and apostrophes

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/carbon-platform#1253]
https://next.carbondesignsystem.com/guidelines/content/writing-style

Some examples throughout the page

<img width="252" alt="Screen Shot 2022-09-09 at 3 57 53 PM" src="https://user-images.githubusercontent.com/32881239/189444600-687e9376-816a-4d13-9c30-cede156d232c.png">
<img width="253" alt="Screen Shot 2022-09-09 at 3 57 35 PM" src="https://user-images.githubusercontent.com/32881239/189445071-a86892dc-e620-4dad-a6f8-a618f5c9ee8d.png">
<img width="207" alt="Screen Shot 2022-09-09 at 4 00 19 PM" src="https://user-images.githubusercontent.com/32881239/189445151-27846e44-4492-40a4-9bfe-b6e66ef3353a.png">
<img width="184" alt="Screen Shot 2022-09-09 at 4 00 25 PM" src="https://user-images.githubusercontent.com/32881239/189445153-e6926b63-53c8-4c92-b24c-c143ac125b0a.png">
<img width="185" alt="Screen Shot 2022-09-09 at 4 00 30 PM" src="https://user-images.githubusercontent.com/32881239/189445156-1f499a76-756b-499c-b4a9-f5085c84fa44.png">
<img width="293" alt="Screen Shot 2022-09-09 at 3 59 46 PM" src="https://user-images.githubusercontent.com/32881239/189445144-770b880b-b21a-445e-b367-6b949f354833.png">
<img width="226" alt="Screen Shot 2022-09-09 at 4 00 11 PM" src="https://user-images.githubusercontent.com/32881239/189445147-da828d09-f658-4de4-b663-b9ad23ec7e22.png">
<img width="218" alt="Screen Shot 2022-09-09 at 4 00 15 PM" src="https://user-images.githubusercontent.com/32881239/189445149-d3c21b07-4152-47af-9692-59cebd584b9b.png">

**Comment by alisonjoseph** [comment]
This page is being pulled remotely from the Carbon website, any hypen to en dash updates will need to be made here https://github.com/carbon-design-system/carbon-website/edit/main/src/pages/guidelines/content/writing-style.mdx

Quotes in mdx will be handled globally #721

**Comment by kingtraceyj** [comment]
tracking straight quote bugs in this #1378 design issue that will be globally resolved in #721

**Comment by kingtraceyj** [comment]
tracking straight quote bugs here #1378
