### ISSUE TITLE
Update design kit empty state card icon

### ISSUE THREAD

**Issue by kingtraceyj** [carbon-design-system/carbon-platform#1277]
Update Design kit empty state card icon from ruler to tools--alt

<img width="480" alt="image" src="https://user-images.githubusercontent.com/20582179/190253513-8c7d801c-6c39-4ae4-b23c-56ef3b434de0.png">

**Comment by mattrosno** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-624c3fc8b7972e001130fef7/issues/carbon-design-system/carbon-platform/1277?planning-poker) with Zenhub @alisonjoseph @andreancardona @francinelucca @jdharvey-ibm
