### ISSUE TITLE
Outline all type in SVGs

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/carbon-platform#1278]
I found a few more of these suckers.

<img width="381" alt="Screen Shot 2022-09-14 at 9 46 46 PM" src="https://user-images.githubusercontent.com/32881239/190302100-44479ae2-269e-416e-9331-e9335e6081d1.png">

<img width="375" alt="Screen Shot 2022-09-14 at 9 47 25 PM" src="https://user-images.githubusercontent.com/32881239/190302102-26875487-a7f3-4d56-98c7-a76bfb37649a.png">

**Comment by mattrosno** [comment]
@jeanservaas I'm closing this, as I opened up two PRs in other repos with the new SVGs. I'm not sure how we had SVGs with `<text>` elements, but we did.
