### ISSUE TITLE
Replace Medium posts coming soon

### ISSUE THREAD

**Issue by francinelucca** [carbon-design-system/carbon-platform#1280]
Replace "medium posts coming soon" text in https://next.carbondesignsystem.com/about-carbon/articles#latest-news with "Visit our Medium page to follow along with news and updates" and a link to medium

**Comment by alisonjoseph** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-624c3fc8b7972e001130fef7/issues/carbon-design-system/carbon-platform/1280?planning-poker) with Zenhub @andreancardona @francinelucca @jdharvey-ibm
