### ISSUE TITLE
Add yourlearning icon to MdxIcon component

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon-platform#1290]
Looks like we need to add yourlearning to the mdxicon component

`<MdxIcon name="yourlearning" />`

<img width="612" alt="Screen Shot 2022-09-21 at 11 42 37 AM" src="https://user-images.githubusercontent.com/2753488/191562875-a857599d-cfda-477c-a278-c1411a031488.png">
-------
**Bug🐛:** Missing the yourlearning icon in the resource card
**Page:** [URL](https://next.carbondesignsystem.com/migrating/guide/overview#yourlearning)
https://carbondesignsystem.com/migrating/guide/overview/#yourlearning

![image](https://user-images.githubusercontent.com/3360588/191099467-41bcef0d-d115-4bb4-bd64-76fabe0d5c77.png)

_Originally posted by @tay1orjones in https://github.com/carbon-design-system/carbon-platform/discussions/1268#discussioncomment-3684048_

**Comment by mattrosno** [comment]
When doing this, let's save the SVG source in the Figma file alongside our other custom icons (icons not coming from `@carbon` npm packages.
