### ISSUE TITLE
On pages with tabs, can't select different tabs via keyboard

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon-platform#1292]
**Bug🐛:** On pages with tabs, can't select different tabs via keyboard
**Page:** URL https://next.carbondesignsystem.com/elements/color/overview
**Browser:** Chrome
**Suggestion:** Via enter/space, be able to switch tab that the page is on

_Originally posted by @abbeyhrt in https://github.com/carbon-design-system/carbon-platform/discussions/1268#discussioncomment-3684104_

**Comment by alisonjoseph** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-624c3fc8b7972e001130fef7/issues/carbon-design-system/carbon-platform/1292?planning-poker) with Zenhub @andreancardona @francinelucca @jdharvey-ibm

**Comment by andreancardona** [comment]
Hey ya'll - leaving a quick comment here:  Looked at this with @alisonjoseph and I think the issues are coming from the fact that Tabs natively shouldn't be rendering links but only content adding this to our next Squad huddle
