### ISSUE TITLE
catalog item focus is off when navigating via keyboard

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon-platform#1306]
**Bug🐛:** function catalog item focus is off when navigating via keyboard
**Page:** https://next.carbondesignsystem.com/assets/functions
**Browser:** Chrome
**Suggestion:** Seems like the outline should follow the card size 
<img width="1282" alt="Captura de Pantalla 2022-09-19 a la(s) 2 48 51 p m" src="https://user-images.githubusercontent.com/32556167/191104101-c0888732-c662-48da-85e1-14a3a5041e28.png">

_Originally posted by @jnm2377 in https://github.com/carbon-design-system/carbon-platform/discussions/1268#discussioncomment-3684211_

**Comment by alisonjoseph** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-624c3fc8b7972e001130fef7/issues/carbon-design-system/carbon-platform/1306?planning-poker) with Zenhub @andreancardona @francinelucca @jdharvey-ibm

**Comment by francinelucca** [comment]
I see this fixed on next-test.carbondesignsystem.com for design kits but not on asset catalogs 👀 : 
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/40550942/192819284-c0f570ff-e95a-4e3f-93c1-36c331c7523a.png">
