### ISSUE TITLE
Need updated links - contributing > bugs and requests 

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon-platform#1311]
**Bug🐛:** Both these links seem off, in carbondesignsystem.com the "Carbon Repo" takes you to see a list of the repos but on platform the new url doesn't and the "Instructions" url on both take you to create a new website page which doesn't seem right given the context.
**Page:** https://next.carbondesignsystem.com/contributing/bugs-and-requests#github-pull-requests
**Browser:** Chrome
**Suggestion:** Maybe have the "Carbon Repo" link out to https://next.carbondesignsystem.com/contributing/bugs-and-requests#github-issues instead on platform, not sure where the "instructions" should link to 🤷 
<img width="878" alt="image" src="https://user-images.githubusercontent.com/40550942/191114393-1522638d-eadc-4e75-adec-530049383b40.png">

_Originally posted by @francinelucca in https://github.com/carbon-design-system/carbon-platform/discussions/1268#discussioncomment-3684629_

**Comment by francinelucca** [comment]
do we know what the instructions should link to? 🤔
