### ISSUE TITLE
Storybook/Docs discrepancy logic exploration

### ISSUE THREAD

**Issue by kingtraceyj** [carbon-design-system/carbon-platform#1360]
Looking at how and why we categorize components together

Variants vs Type

**Comment by jeanservaas** [comment]
@aubrey-oneal does this need to be closed, we have both your issue and my issue (below) Is this one something different?

#1258 #1357

**Comment by aagonzales** [comment]
Decisions will be made via this [new issue](https://github.com/carbon-design-system/carbon-platform/issues/1539) around a final definition of type vs variant and how they are represented in docs and in the index/schema.
