### ISSUE TITLE
YL icon missing from resource cards

### ISSUE THREAD

**Issue by kingtraceyj** [carbon-design-system/carbon-platform#1363]
YL icon missing in these cards:
https://next-test.carbondesignsystem.com/migrating/guide/overview#yourlearning

Present in current carbon website:
https://carbondesignsystem.com/migrating/guide/overview/#yourlearning

Example of what they should look like:
https://www.ibm.com/brand/expression#learn-the-essentials

**Comment by francinelucca** [comment]
copy of #1290 ?

**Comment by alisonjoseph** [comment]
<img width="566" alt="Screen Shot 2022-09-28 at 8 26 05 AM" src="https://user-images.githubusercontent.com/2753488/192790489-d1632519-12f6-449b-9be2-f999dd1e650f.png">

Confirmed this is a duplicate and has been fixed on main branch.
