### ISSUE TITLE
Develop crosslink banner for homepage

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon-platform#1365]
Related design issue: https://github.com/carbon-design-system/carbon-platform/issues/1235

For the v1 release, we need a banner on the homepage that will link the [Next](https://next.carbondesignsystem.com/) platform site out to the [Main](https://carbondesignsystem.com/) Carbon site. 

**Interactions:**
- Banner **only** exists on the homepage
- Banner is **not** sticky and scrolls away

**Content**
- The exact content is still TBD. @aubrey-oneal to finalize

## Spec
[Figma file](https://www.figma.com/file/H3kWgBYKdMzov7LIZ1BlHa/Next-crosslinks?node-id=67%3A6733)

<img width="4034" alt="Group Next" src="https://user-images.githubusercontent.com/11670886/192643243-4ae3eada-1780-40eb-b3c1-bcfc2ee82c77.png">

**Comment by alisonjoseph** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-624c3fc8b7972e001130fef7/issues/carbon-design-system/carbon-platform/1365?planning-poker) with Zenhub @andreancardona @francinelucca @jdharvey-ibm
