### ISSUE TITLE
Guidance for List needs broken down into Ordered list and Unordered list

### ISSUE THREAD

**Issue by mattrosno** [carbon-design-system/carbon-platform#1374]
Found in https://github.com/carbon-design-system/carbon-platform/issues/907

Short term fixed in https://github.com/carbon-design-system/carbon/pull/12192

The Ordered list and Unordered list are sharing the same Usage, Style, and Accessibility docs. We probably need to split this up, if we're indexing both component separately instead of indexing one List component.

**Comment by kingtraceyj** [comment]
@laurenmrice is currently working on list docs. we should sync up with her. she's been thinking through list structure.

**Comment by aagonzales** [comment]
Documentation will be rolled up from the two individual index items. @mattrosno is adding a canonical data point to address how the roll-up works in the schema. We no longer need to break apart guidance for ordered and unordered list
