### ISSUE TITLE
Straight quote bugs - Design audit 

### ISSUE THREAD

**Issue by kingtraceyj** [carbon-design-system/carbon-platform#1378]
This issue tracks straight quote bugs that will be handled globally by #721

**Comment by kingtraceyj** [comment]
#1251

https://next.carbondesignsystem.com/guidelines/content/overview

<img width="436" alt="Screen Shot 2022-09-09 at 3 49 05 PM" src="https://user-images.githubusercontent.com/32881239/189443038-0479564d-9449-4cb6-a37c-7621ada5a188.png">

<img width="171" alt="Screen Shot 2022-09-09 at 3 49 15 PM" src="https://user-images.githubusercontent.com/32881239/189443043-869d7a71-6a9d-40bd-bdaa-1e60b984f5d4.png">

**Comment by kingtraceyj** [comment]
#1250

https://next.carbondesignsystem.com/libraries/carbon-components-angular

<img width="548" alt="Screen Shot 2022-09-09 at 3 09 59 PM" src="https://user-images.githubusercontent.com/32881239/189435203-d44071bd-2c75-4a86-86c1-2069a0aab1ed.png">

<img width="662" alt="Screen Shot 2022-09-09 at 3 10 02 PM" src="https://user-images.githubusercontent.com/32881239/189435207-c40a1e45-39e0-4463-948b-586d80d3a63e.png">

here too. Probably in all cases where there’s “Carbon’s”
https://next.carbondesignsystem.com/libraries/carbon-react

It’s also in the small text on the [Libraries ](https://next.carbondesignsystem.com/libraries)page

<img width="311" alt="Screen Shot 2022-09-09 at 3 14 56 PM" src="https://user-images.githubusercontent.com/32881239/189435917-bd5a19cc-b7d4-4f86-b11a-63ed14ea91a2.png">
<img width="354" alt="Screen Shot 2022-09-09 at 3 15 04 PM" src="https://user-images.githubusercontent.com/32881239/189435918-b9998253-7078-4384-ab40-4b72c52f7b4a.png">

Here
https://next.carbondesignsystem.com/libraries/ibm-cloud-cognitive

<img width="368" alt="Screen Shot 2022-09-09 at 3 16 49 PM" src="https://user-images.githubusercontent.com/32881239/189436164-700cd283-c6b2-4722-8069-eeb1a5112cca.png">

<img width="360" alt="Screen Shot 2022-09-09 at 3 17 11 PM" src="https://user-images.githubusercontent.com/32881239/189436167-dbd9cb1b-0c99-473c-ba7f-9a5dee96de95.png">

**Comment by kingtraceyj** [comment]
#1253 

https://next.carbondesignsystem.com/guidelines/content/writing-style


Some examples throughout the page

<img width="252" alt="Screen Shot 2022-09-09 at 3 57 53 PM" src="https://user-images.githubusercontent.com/32881239/189444600-687e9376-816a-4d13-9c30-cede156d232c.png">
<img width="253" alt="Screen Shot 2022-09-09 at 3 57 35 PM" src="https://user-images.githubusercontent.com/32881239/189445071-a86892dc-e620-4dad-a6f8-a618f5c9ee8d.png">
<img width="207" alt="Screen Shot 2022-09-09 at 4 00 19 PM" src="https://user-images.githubusercontent.com/32881239/189445151-27846e44-4492-40a4-9bfe-b6e66ef3353a.png">
<img width="184" alt="Screen Shot 2022-09-09 at 4 00 25 PM" src="https://user-images.githubusercontent.com/32881239/189445153-e6926b63-53c8-4c92-b24c-c143ac125b0a.png">
<img width="185" alt="Screen Shot 2022-09-09 at 4 00 30 PM" src="https://user-images.githubusercontent.com/32881239/189445156-1f499a76-756b-499c-b4a9-f5085c84fa44.png">
<img width="293" alt="Screen Shot 2022-09-09 at 3 59 46 PM" src="https://user-images.githubusercontent.com/32881239/189445144-770b880b-b21a-445e-b367-6b949f354833.png">
<img width="226" alt="Screen Shot 2022-09-09 at 4 00 11 PM" src="https://user-images.githubusercontent.com/32881239/189445147-da828d09-f658-4de4-b663-b9ad23ec7e22.png">
<img width="218" alt="Screen Shot 2022-09-09 at 4 00 15 PM" src="https://user-images.githubusercontent.com/32881239/189445149-d3c21b07-4152-47af-9692-59cebd584b9b.png">

**Comment by kingtraceyj** [comment]
#1089 

<img width="446" alt="Screen Shot 2022-07-29 at 8 13 00 PM" src="https://user-images.githubusercontent.com/32881239/181865337-3aceb236-26d4-49a1-a38d-5f4ea113960a.png">

https://next.carbondesignsystem.com/contributing/schema

**Comment by aagonzales** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-624ca8ad03d709001dc542bf/issues/carbon-design-system/carbon-platform/1378?planning-poker) with Zenhub @jeanservaas @aubrey-oneal

**Comment by mattrosno** [comment]
Closing this because all bugs listed here are being fixed in platform and website PRs, and via:

- https://github.com/carbon-design-system/carbon-platform/issues/721
- https://github.com/carbon-design-system/carbon-platform/issues/1451
