### ISSUE TITLE
Update Figma tutorial

### ISSUE THREAD

**Issue by aubrey-oneal** [carbon-design-system/carbon-platform#1394]
🔎 Missing content
**Page:** https://next.carbondesignsystem.com/designing/figma
**Issue:** E.g. Whole page is outed, content has recently been updated to include v11 assets. Also includes separate directions for internal and external users.
**Suggestion:** E.g. Import in new markdown page from main Carbon Figma page
https://carbondesignsystem.com/designing/kits/figma

_Originally posted by @aagonzales in https://github.com/carbon-design-system/carbon-platform/discussions/1270#discussioncomment-3684154_

**Comment by aagonzales** [comment]
Link to PR
https://github.com/carbon-design-system/carbon-website/pull/3176/files#diff-32d13ecb57b003b1fc2f08c460f5947b72bb0600fa6f116db23c5f0aa177ac33
