### ISSUE TITLE
Separate routes for remote vs platform-generated content (/remote/..., etc.) with rewrites as needed

### ISSUE THREAD

**Issue by jdharvey-ibm** [carbon-design-system/carbon-platform#1416]
There are some MDX pages in the web-app which rely on imports to work. We disallow these for typical remote MDX, but need a mechanism by which to allow them for our own platform MDX pages.

This issue is the work to "namespace" the remote MDX content based on where it comes from. If it is platform-team-generated, then it can have a route prefix indicating that, which will let us know when processing the MDX whether or not to allow import statements.

For out-of-band remote MDX (i.e. untrusted MDX), a separate route prefix can be used to denote this and enforce stricter MDX requirements, such as no import/export statements.

Assuming this content becomes namespaced, route rewrites would be used to map pages to the correct internal routes to maintain the existing user-visible URL structure.

Ideas for namespacing:

- Pages such as `/about-carbon/how-carbon-works` would have an internal route of `/platform/about-carbon/how-carbon-works`. The prefix of "platform" would indicate that this content should be loaded from a specific package or repo and should allow import/export statements to be used
- Pages such as `/libraries/carbon-react/latest/assets/accordion/usage` could either have an internal route of something like `remote/libraries/carbon-react/latest/assets/accordion/usage` or could rely on the `libraries` prefix as the indicator that any resulting MDX that is rendered should be considered untrusted and things like imports/exports should be disallowed.
- Another idea for untrusted MDX would be to effectively treat certain prefixes as an allow-list. For example, the presence of `/platform/` as a prefix would equal "trusted" and the absence of that prefix would equal "untrusted".

**Comment by mattrosno** [comment]
Would these internal routes get exposed? If `/platform` was used as an internal route, would the end user see `/platform` in URLs?

**Comment by jdharvey-ibm** [comment]
No, we'd want to keep those private and only expose rewritten versions of the routes that are nicer and exist currently.

**Comment by jdharvey-ibm** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-624c3fc8b7972e001130fef7/issues/carbon-design-system/carbon-platform/1416?planning-poker) with Zenhub @andreancardona @francinelucca

**Comment by jdharvey-ibm** [comment]
Per discussion in issue refinement, we want to treat everything as "trusted" as-is, except for a few specific route prefixes, like:

- /libraries
- /assets
- /data-visualization
- maybe others in the future
