### ISSUE TITLE
Can't close side nav on home page with new banner at small breakpoints

### ISSUE THREAD

**Issue by mattrosno** [carbon-design-system/carbon-platform#1421]
**Description**

> Tell us more about the problem that you're running into. What did you see? What did you expect to
> see?

I'm seeing two issues, maybe related.

1. At small and medium breakpoints, the new home page banner bar is covering the top of the side nav so you can't get to the X button.
2. Outside click to close the side nav doesn't work if you try clicking the black UI header bar.

<img width="612" alt="image" src="https://user-images.githubusercontent.com/1691245/194147841-faaa3e32-7ab7-483a-a529-617b13d5b2e8.png">

**Steps to reproduce**

> How do we reproduce the error? Please be as specific as you can.

1. At small and medium breakpoints
3. Go here: https://next.carbondesignsystem.com
4. Open the side nav
5. Try to close the side nav

**Comment by alisonjoseph** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-624c3fc8b7972e001130fef7/issues/carbon-design-system/carbon-platform/1421?planning-poker) with Zenhub @andreancardona @francinelucca @jdharvey-ibm
