### ISSUE TITLE
Link thumbnail displaying Times

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/carbon-platform#1426]
This may already be captured in another issue but double checking
https://next.carbondesignsystem.com/assets/components

<img width="691" alt="Screen Shot 2022-10-07 at 9 13 46 AM" src="https://user-images.githubusercontent.com/32881239/194576155-dcccae20-be55-49cc-a25a-dcf1a9224af0.png">

**Comment by mattrosno** [comment]
@jeanservaas I found 8 that need fixed, including breadcrumb. I don't know how we haven't caught and fixed these yet.

![image.png](https://images.zenhubusercontent.com/546f60da7c6ccc6277a5fd78/85fefe63-58d4-4c9d-bf5c-29002d6095f3)

**Comment by jeanservaas** [comment]
@mattrosno the grid svg doesn't have any type in it. This is what I have as "grid.svg"

<img width="385" alt="image" src="https://user-images.githubusercontent.com/43144260/195140425-76a35473-60b0-4beb-997c-8c65db9a2564.png">

I've attached all of the svgs here, including grid, just in case



[type_outlines.zip](https://github.com/carbon-design-system/carbon-platform/files/9757751/type_outlines.zip)
