### ISSUE TITLE
Do/don't cards need spacing above (global issue)

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/carbon-platform#1427]
Global issue

— https://next.carbondesignsystem.com/elements/2x-grid/overview

— https://next.carbondesignsystem.com/elements/icons/usage

— https://next.carbondesignsystem.com/elements/pictograms/usage

see examples below

2x Grid page
<img width="881" alt="Screen Shot 2022-10-07 at 9 16 24 AM" src="https://user-images.githubusercontent.com/32881239/194576926-9fc751cf-1342-41c5-84d7-d5d17904dd4c.png">

<img width="958" alt="Screen Shot 2022-10-07 at 9 16 34 AM" src="https://user-images.githubusercontent.com/32881239/194576932-5467ce15-7bf4-4f6a-8d63-819222e458d0.png">

<img width="1033" alt="Screen Shot 2022-10-07 at 9 16 49 AM" src="https://user-images.githubusercontent.com/32881239/194576934-dd749b7b-2d96-45b9-8928-531ef0599d66.png">

<img width="975" alt="Screen Shot 2022-10-07 at 9 16 57 AM" src="https://user-images.githubusercontent.com/32881239/194576943-983d0d07-cdac-4a9a-93b0-aa8c395641da.png">

**Comment by jdharvey-ibm** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-624c3fc8b7972e001130fef7/issues/carbon-design-system/carbon-platform/1427?planning-poker) with Zenhub @andreancardona @francinelucca

**Comment by jdharvey-ibm** [comment]
Also confirm what to do with the left margin/padding

**Comment by alisonjoseph** [comment]
@carbon-design-system/carbon-platform-devs I believe this will be fixed with the component migration PR https://github.com/carbon-design-system/carbon-platform/pull/1423  

what is the left margin/padding issue?

**Comment by jdharvey-ibm** [comment]
@alisonjoseph The screenshot in the issue description above shows the left bound of the do/don't card as aligned with the graphic above it. Currently, on the platform sites it is indented a bit to the right. I'm not sure which of those is the correct behavior.
<img width="1036" alt="image" src="https://user-images.githubusercontent.com/51208233/195690110-121b2b7b-ec80-417f-bdec-0da96800eea6.png">

**Comment by alisonjoseph** [comment]
@jdharvey-ibm both issues are fixed locally in the mdx-components branch. I'm going to put them in their own smaller PR.

<img width="883" alt="Screen Shot 2022-10-14 at 8 07 21 AM" src="https://user-images.githubusercontent.com/2753488/195854514-8ec106e5-f1fc-406f-ba0d-7e3cdb8dbae4.png">
