### ISSUE TITLE
Update thumbnails from #1315

### ISSUE THREAD

**Issue by mattrosno** [carbon-design-system/carbon-platform#1432]
This is the dev issue for: https://github.com/carbon-design-system/carbon-platform/issues/1315

**Comment by jdharvey-ibm** [comment]
From Matt: To test, it's a good idea to open the images in chrome and set a colored background for comparison.

**Comment by jdharvey-ibm** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-624c3fc8b7972e001130fef7/issues/carbon-design-system/carbon-platform/1432?planning-poker) with Zenhub @andreancardona @francinelucca

**Comment by mattrosno** [comment]
Mentioned PR is now merged.
