### ISSUE TITLE
Uniformly use 'IBM' in tables

### ISSUE THREAD

**Issue by aubrey-oneal** [carbon-design-system/carbon-platform#1435]
📝 Fix
**Page:** https://next.carbondesignsystem.com/designing/get-started#step-4:-review-foundational-guidance
**Issue:** I notice the row items for `Brand` and `Brand Systems` don't include the word "IBM" in front of them for this page, but on another page ([Content guidelines](https://next.carbondesignsystem.com/guidelines/content/overview#content-foundations)) we are using the word "IBM" in front. We should probably be consistent in both places of how we want to do this.

---

_Originally posted by @laurenmrice in https://github.com/carbon-design-system/carbon-platform/discussions/1270#discussioncomment-3684495_

**Comment by aagonzales** [comment]
We will add IBM to the names
