### ISSUE TITLE
Dev: update carbon-website community assets page

### ISSUE THREAD

**Issue by mattrosno** [carbon-design-system/carbon-platform#1439]
This is the dev issue to complete the designs here:

https://github.com/carbon-design-system/carbon-platform/issues/1234#issuecomment-1276535988

https://github.com/carbon-design-system/carbon-platform/issues/1439#tasklist-block-4f79810f-77c6-43a1-88f8-b527ce719edd

**Comment by jdharvey-ibm** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-624c3fc8b7972e001130fef7/issues/carbon-design-system/carbon-platform/1439?planning-poker) with Zenhub @francinelucca @andreancardona

**Comment by andreancardona** [comment]
Carbon Website PR: https://github.com/carbon-design-system/carbon-website/pull/3233

**Comment by mattrosno** [comment]
This should have been closed 10/31.
