### ISSUE TITLE
Finalize list of one-use components from mdx-components package

### ISSUE THREAD

**Issue by jdharvey-ibm** [carbon-design-system/carbon-platform#1496]
Continue with the mural investigation to figure out which components are only used in one place (and hopefully not in any dynamic docs) and add those to the list of components that will be excluded from mdx-components package.

https://app.mural.co/t/ibm14/m/ibm14/1667230506318/3c007d2b56bfc0b1c820e15d7d946285da5ae4a2?sender=jdharvey8136

Once this list is done, the conversion PR can be updated accordingly to "revert" changes we no longer want.

#1423

**Comment by francinelucca** [comment]
- @carbon/react:
- [ ]      `Tag`
- [ ]      `StructuredListWrapper`
- [ ]       `StructuredListCell`
- [ ]      `StructuredListBody`
- [ ]      `StructuredListRow`
- [ ]      `ListItem`
- [ ]      `UnorderedList`
- [ ]      `OrderedList`
- [ ]      `Accordion`
- [ ]      `AccordionItem`
- [ ]      `CodeSnippet`
- [ ] `ColorPalette`
- [ ] `ColorTokenTable`
- [ ] `ColorGrid`
- [ ] `ColorBlock`
- [ ] `Glossary`
- [ ] `PictogramLibrary`
- [ ] `IconLibrary`
- [ ] `StatusIndicatorTable`
- [ ] `MdxIcon`
- [ ] `TypesetStyle`
- [ ] `TypeScaleTable`
- [ ]  `TypeWeight`
- [ ] `Profile`
- [ ] `MdxPage`
- [ ] `MdxNotification`
- [ ] `FullPageError`
