### ISSUE TITLE
Incorrect column span in ResourceCard

### ISSUE THREAD

**Issue by francinelucca** [carbon-design-system/carbon-platform#1528]
**Description**

Expect Resource Card to span 4 columns here:
<img width="1324" alt="image" src="https://user-images.githubusercontent.com/40550942/204860458-b877fa50-0f73-4caa-996f-58fa899db8b0.png">

**Steps to reproduce**

> How do we reproduce the error? Please be as specific as you can.

1. https://next.carbondesignsystem.com/elements/color/implementation, scroll to bottom, notice huge resource card, compare to https://carbondesignsystem.com/guidelines/color/implementation

**Comment by jdharvey-ibm** [comment]
We plan to address this by adding a wrapping `Row` around the content in the carbon website repo. Right now, it's just a top-level `Column`.

**Comment by francinelucca** [comment]
fixed with https://github.com/carbon-design-system/carbon-website/pull/3295
