### ISSUE TITLE
Discrepancy with the tags

### ISSUE THREAD

**Issue by andreancardona** [carbon-design-system/carbon-platform#1593]
**Description**

Discrepancy with the tags - I've so far only noticed it in `Patterns with Angular` directly from the search page - ex: if you filter by `Angular` you won't see the bug 

1. Nav to this link: https://next.carbondesignsystem.com/assets/patterns
2. Scroll down to a pattern that has an `Angular` tag - it shows as if this pattern is available in  other frameworks but then navigating to `Dialogs` (for example)  it only has 1 framework: https://next.carbondesignsystem.com/libraries/carbon-components-angular/latest/assets/dialogs

<img width="1363" alt="Screenshot 2023-02-08 at 13 12 34" src="https://user-images.githubusercontent.com/32720851/217641115-8f2ca0a6-04a5-43e3-89e8-72384c298880.png">

**Comment by mattrosno** [comment]
Good catch. This should have a link that says `Design only`.

<img width="192" alt="image" src="https://user-images.githubusercontent.com/1691245/217644155-7b910dbb-cbb2-4a35-a988-47768fab2d80.png">

So you can get from the Angular implementation to the Design only documentation.

<img width="698" alt="image" src="https://user-images.githubusercontent.com/1691245/217644272-1582dabc-79b0-4169-b547-8a70b4703709.png">
