### ISSUE TITLE
CatalogMultiselectFilter enhancements

### ISSUE THREAD

**Issue by mattrosno** [carbon-design-system/carbon-platform#163]
### Description

There are accessibility issues with the new multiselect custom component, but also some UX issues that need addressed:

- [x] Close popover on escape key
- [x] Move focus to popover on open and give it the thin blue focus outline, like the normal multiselect component
- [x] Update state on close so the popover doesn't close each time you select a new item
- [x] Add motion to popover opening/closing (slide down like dropdown?)
- [x] Can we nest a tag in a multi-select? We're currently getting "button in button" accessibility warnings.

### Steps to reproduce

- Open the multi select and the popover does not have focus, pressing escape does not close the popover, and the popover should not close when you select an item

**Comment by mattrosno** [comment]
I'm questioning if there should ever be a reason to keep the popover open when you select an item. Will we want this on mobile?

**Comment by mattrosno** [comment]
@kingtraceyj I added a 4th checkbox to this issue if we want to add any motion to the filter dropdown.

**Comment by mattrosno** [comment]
@andreancardona I moved this to sprint 11 because it was unrealistic to finish this given complexity of asset LP.

**Comment by andreancardona** [comment]
@mattrosno spoke with D.A. about a button within a button - and the point of view is that it is _ok_ because it is not an explicit button in this situation
