### ISSUE TITLE
Catalog design iteration

### ISSUE THREAD

**Issue by mattrosno** [carbon-design-system/carbon-platform#185]
- [x] Update Sterling to AI Apps for sponsor team
- [x] Add community maintained sponsor team
- [x] Fix sponsor circle background color so it's white
- [x] Replace sponsor text with library name (and version too?)
- [x] Create data viz catalog
- [x] Collapse assets by framework (both for components and assets) and remove React as the default filter
- [x] Component sub-types
- [x] Page header header needs bigger font size on xlg?
- [x] Use "backup" pictogram for libraries catalog

**Comment by aubrey-oneal** [comment]
**Navigation**
Structural navigation
Contextual navigation

**Input**
Data input and control
Forms

**Information display**
Data display and list
FYI
Progress and validation
Content organization
Content element

**Container**
Panel
Structure
