### ISSUE TITLE
Component: PageTab

### ISSUE THREAD

**Issue by andreancardona** [carbon-design-system/carbon-platform#196]
Create a PageTab header that follows the design: 
<img width="947" alt="Screen Shot 2022-01-19 at 12 10 29 PM" src="https://user-images.githubusercontent.com/32720851/150189134-d4341d40-5446-4bd9-93b6-d09a4f210f6b.png">

**Comment by mattrosno** [comment]
@andreancardona closing this until it's determined that we need page tabs.
