### ISSUE TITLE
Sort component styling is wrong

### ISSUE THREAD

**Issue by mattrosno** [carbon-design-system/carbon-platform#197]
### Description

Are our overrides wrong? Are there upstream Carbon changes to account for? Is this just production or development environment too?

### Steps to reproduce

https://carbon-platform-playground.wdc1a.ciocloud.nonprod.intranet.ibm.com/assets/components

![image](https://user-images.githubusercontent.com/1691245/150200298-f7b52f53-2d38-4c5e-ad6f-7bf4620be755.png)

**Comment by mattrosno** [comment]
To do: Next.js build and start locally to see if reproducable.

**Comment by francinelucca** [comment]
ran docker container from published image and sort component seems ok , also confirmed looks good in netlify and CE current deployments
<img width="342" alt="image" src="https://user-images.githubusercontent.com/40550942/153946439-5a29081a-5b2b-4ae2-829a-fd3e14c66be5.png">

**Comment by mattrosno** [comment]
@francinelucca cool, thanks, closing.
