### ISSUE TITLE
Logging service

### ISSUE THREAD

**Issue by jdharvey-ibm** [carbon-design-system/carbon-platform#21]
- [x] #81
- [x] #82

### Package/API

- [x] #83
  - [x] Document usages for each API
- [x] #84
- [x] #85
- [x] #86
- [x] #87
- [x] #88
- [x] #89
- [x] #90

### Service

- [x] #91
- [x] #92
- [x] #93
- [x] #94

**Comment by mattrosno** [comment]
@jdharvey-ibm can this epic be closed?

**Comment by jdharvey-ibm** [comment]
@mattrosno Yep! Closing.
