### ISSUE TITLE
Web App: Error out immediately on startup if environment incorrectly configured

### ISSUE THREAD

**Issue by francinelucca** [carbon-design-system/carbon-platform#232]

**Comment by jdharvey-ibm** [comment]
@francinelucca can you give this a shot on the latest from the main branch to see if it errors out as expected? I think the changes I integrated on Friday might have fixed this.

**Comment by jdharvey-ibm** [comment]
Okay, thanks for giving it a whirl. In the interest of keeping the production server running as closely to Next.js defaults as possible, let's close this issue as a "wontfix". The risk is pretty minimal, and we'll see it in the logs pretty quickly if/when it happens.
