### ISSUE TITLE
Prop warning for header login link

### ISSUE THREAD

**Issue by mattrosno** [carbon-design-system/carbon-platform#239]
### Description

Next.js is throwing a warning. Also, the icon is positioned low for some reason.

![image](https://user-images.githubusercontent.com/1691245/152573924-6862b844-f926-4486-ba8c-9c7510babe01.png)

### Steps to reproduce

See above.

**Comment by mattrosno** [comment]
Adding to private beta so we fix the icon alignment.

**Comment by francinelucca** [comment]
icon alignment will be fixed with #231, got still to work on a fix for app warning
