### ISSUE TITLE
Provide stable selectors per asset

### ISSUE THREAD

**Issue by mattrosno** [carbon-design-system/carbon-platform#243]
If every asset in the system had a unique identifier, then we can use that as the means to target assets during automated tests and in services like Carbon Devtools where it's finding components on the page (right now, Devtools is crawling the page looking for class names which is error prone.) Per the platform [draft schema](https://github.com/carbon-design-system/carbon-platform/blob/3fd6b72a643b3ed00f606e4aa8a28b6bc446780d/docs/resource-schemas.md), we have libraries and assets where each has an `id`.

# Constraints

Code packages can change names over time. Components can change names over time. Not all components use class names for styling.

# Option 1) generated identifiers

We could generate an identifier per asset (e.g. UUIDs.) Pros: guaranteed uniqueness. Assets can safely change libraries as the identifier has no dependency on the asset's library. Cons: we have to persist those identifiers, they aren't contextual, not readable, etc.

# Option 2) library/asset identifiers

In the draft schema, part of registering a library with the platform is receiving an identifier for the library. For example, the identifier for the Carbon React component library could be `carbon-react`. Because the platform is providing the id, the platform can guarantee uniqueness.

Also in the draft schema is an `id` per asset. That is determined by the library maintainers, and it's on those maintainers to ensure uniqueness within that library. For example, the `id` for a Card component could be `card`. Because libraries will typically have components named the same, the fully qualified identifier could include the library and asset's ids, delineated by `/`. E.g. `carbon-react/card`. That means adding the stable selector as an HTML attribute would be:

```html
<div data-autoid="carbon-react/card">Card component</div>
```

Taking this a bit further, there are dependency needs in the schema where an asset inherits certain properties from an asset in another library. Because libraries are versioned, we could add that to the fully qualified selector as `library-id@version/asset-id`. The version would be optional. Without the version, the selector would default to latest, but by including the version, the stable selector becomes more specific by targeting the asset at a specific point in time.

For example, this could be used in the schema for the Carbon React card:

```yml
id: card
inherits:
  asset: carbon-styles@v1.0.0/card
```

Including the library in the selector means we can version the selectors. But what happens when an asset is transferred from one library to another? Does that mean we'd have to keep track of that in a resolver to not break any automated tests that are depending on `previous-library/my-asset` but now resolves to `new-library/my-asset`?

**Comment by mattrosno** [comment]
@jeffchew @photodow have an opinion here? I'm leaning towards option 2, but don't know how to handle that scenario when an asset moves to a different library (code package).

**Comment by mattrosno** [comment]
@jeffchew reviewing the [Carbon for IBM.com stable selector docs](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/docs/stable-selectors.md)... the intent of the schema is to identify the assets, not individual HTML elements inside of the assets.

In the BEM example:

```html
<input type="text" data-autoid="block__element--modifier"/>
```

The `block` could be of format `library-id/asset-id` or `library-id@version/asset-id`? Like a vendor prefix that's registered with platform?

**Comment by jeffchew** [comment]
@mattrosno I like the idea of `library-id/asset-id` and adding naming consistency across all Carbon assets. 

We do actually have stable selectors within outer components, so it would be easier (and a stable/reliable way) for tests/campaigns/etc to access elements within the outer component.

The masthead is probably the most extreme case, but it's been helpful for both our e2e test creation as well as the adobe target team for targeting and identifying elements within the masthead. We document it in our docs:

https://www.ibm.com/standards/carbon/web-components/?path=/docs/components-masthead--default#stable-selectors

**Comment by mattrosno** [comment]
@jeffchew in that masthead example, the prefix and block part of BEM `dds--masthead` would then be derived from the platform schema as `ibmdotcom-web-components/masthead`. I like that it would be unique to the greater design system and in a standardized format, but would it be too long? Some of your inner element stable selectors are already long, e.g.

`dds--masthead__l0-nav--subnav-col${item}-item${item}`

so would adding the library's id to it be a big deal? E.g.:

`ibmdotcom-web-components/masthead__l0-nav--subnav-col${item}-item${item}`

(Not asking about migration, but the ideal, scalable, identifier strategy.)

**Comment by mattrosno** [comment]
Hi @jeffchew following up to https://github.com/carbon-design-system/carbon-platform/issues/243#issuecomment-1032941002 - will the `library-id/asset-id` format for the "block" of BEM work for you?

**Comment by mattrosno** [comment]
Marking this as closed unless there is any objection of the `library-id/asset-id` format which can be driven by the schema.
