### ISSUE TITLE
Page header title descender is clipped

### ISSUE THREAD

**Issue by mattrosno** [carbon-design-system/carbon-platform#261]
### Description

The page header title has `overflow: hidden;` from the line clamp mixin which is cutting of the bottom of descenders like "g".

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/1691245/154542106-5ecf0fb8-3e59-4186-8a39-70c236fcf4bf.png">

### Steps to reproduce

Any page header with a descender like "g".

**Comment by alisonjoseph** [comment]
@mattrosno I was looking at this, what is the purpose of the overflow: hidden and the line clamp mixin? Can we just remove overflow hidden?
