### ISSUE TITLE
Log in interface

### ISSUE THREAD

**Issue by mattrosno** [carbon-design-system/carbon-platform#268]
We are currently leveraging Next.js middleware to enforce IBMid authentication prior to viewing **any** page in the private beta. This is a short-term solution so we can show IBM internal content in the private beta. A later monthly release will have proper authentication where open-source content is visible prior to logging in.

Right now it looks like this when the page loads, then you click the user icon top right to log in, then you're in.

<img width="1182" alt="image" src="https://user-images.githubusercontent.com/1691245/154759197-4fc6df4a-d91d-49b0-8488-d2a4d257cf21.png">

# Option 1

We add a log in button with copy to that 404 page. A simple "page not found, log in to view all pages." This is by far the simplest approach. We could even modify that 404 page to not show the log in prompt if you've since logged in.

# Option 2

We build a full login page (similar to https://badges.carbondesignsystem.com) where we take over the full page and no side nav and we prompt people to log in. I don't think it's worth that effort.

# Option 3

Some log in modal that pops up. There will still be an empty 404 page behind it, so this doesn't seem ideal.

# Recommendation

Option 1 to help us hit this first private beta release as it's the quickest to do and with minimal effort we can make that 404 page look good with the log in prompt.

**Comment by mattrosno** [comment]
@kingtraceyj @jeanservaas can you look at this today to unblock @francinelucca?

**Comment by jeanservaas** [comment]
@francinelucca I can't Slack, but I just wanted to run this by you.

Can we play with type sizes here a bit? I guess I was just wondering how much latitude we have for design.

**Option 1**

<img width="1315" alt="image" src="https://user-images.githubusercontent.com/43144260/155170359-5d079694-07d9-4e57-8eff-e939bc6003fb.png">


Make the "Page not found." a little bit smaller so it's not so prominent and the pop up the "Log in to view all pages"

**Option 2**

Make it all extra with all one type size.

<img width="1312" alt="image" src="https://user-images.githubusercontent.com/43144260/155170576-98c1dbb9-a6b3-4b35-8b66-0d2b5e273658.png">

Do you have any thoughts/preferences? Was this what you were looking for?

**Comment by francinelucca** [comment]
Thanks! @jeanservaas, I think we can make either/or happen.
I don't really have a preference, Maybe I'd go for Option 2 so that when the user is already logged in we can not show the login stuff and it wouldn't look as empty? or do we want to show it either way? (in the case that it's actually a 404 page)
any thoughts here? @mattrosno @andreancardona @jdharvey-ibm

**Comment by jeanservaas** [comment]
Cool, yes definitely guys weigh in! 

I don't think either would look too empty as long as we leverage the display-01 for 1 or both lines... 

I was just thinking more about like, whether we want to emphasize the "page not found" part, since we're kind of just repurposing a 404 page for a log in page.

We can see if joe or andrea have any opinions, but if no one weighs in after a while, we can just go with option 2 francine.

**Comment by mattrosno** [comment]
@jeanservaas's option 2 looks good to me @francinelucca.

We always can optimize the 404 page later on when the site is populated. For example, we point to common pages in the website's current 404. https://www.carbondesignsystem.com/404/

**Comment by jdharvey-ibm** [comment]
Either option is totally fine with me! If I _had_ to pick one, I'd maybe lean slightly towards option 1, but only because I feel less bad about hitting a page-not-found when the error text is smaller than the corrective action :joy:

**Comment by jeanservaas** [comment]
@francinelucca 

**Medium breakpoint:** $display-01 token is a fluid token, so the type will automatically change size at the medium breakpoint.

— I'd keep at hard break after "Page not found" at tablet if possible... it just reads better.

<img width="762" alt="image" src="https://user-images.githubusercontent.com/43144260/155378999-d9fb9296-73d8-439b-a3cd-a03e082be9c4.png">

Small breakpoint:

— Change type token in mobile from "display
— No hard break after "Page not found"

<img width="407" alt="image" src="https://user-images.githubusercontent.com/43144260/155380814-e5da0991-dff3-452c-8485-66a1e6596f05.png">

**Comment by francinelucca** [comment]
Medium Breakpoint: 
![image](https://user-images.githubusercontent.com/40550942/155399801-09f3bdaf-f498-472b-b8f0-763402635b0c.png)
Small Breakpoint: 
![image](https://user-images.githubusercontent.com/40550942/155399839-07c9f65a-8f5d-4dbd-8d41-07f865b84f98.png)
