### ISSUE TITLE
Fix broken thumbnail images

### ISSUE THREAD

**Issue by mattrosno** [carbon-design-system/carbon-platform#280]
- [x] Network diagram
- [x] Connecting lines (border missing)
- [x] Donut
- [x] Gauge
- [x] Meter
- [x] Proportional symbol (missing border)
- [x] CTA (doesn't have transparent bg)

### Description

It should have a transparent background like the others.

### Steps to reproduce

See examples below.

**Comment by mattrosno** [comment]
- [ ]
<img width="577" alt="image" src="https://user-images.githubusercontent.com/1691245/157515576-52ccdfb8-5f02-4c90-90ac-352522672345.png">

**Comment by mattrosno** [comment]
<img width="392" alt="image" src="https://user-images.githubusercontent.com/1691245/157519375-589f04ec-a82b-4fcd-8d56-aa667f9fb588.png">

**Comment by mattrosno** [comment]
<img width="389" alt="image" src="https://user-images.githubusercontent.com/1691245/157519706-b6a574db-542e-4b82-9e5e-d997eccb22a5.png">

**Comment by mattrosno** [comment]
<img width="393" alt="image" src="https://user-images.githubusercontent.com/1691245/157519843-ec9ef744-f56c-48d2-baa0-395a46678dbb.png">

**Comment by mattrosno** [comment]
<img width="387" alt="image" src="https://user-images.githubusercontent.com/1691245/157520078-f5a1b18c-c153-46ee-9106-128eae241a58.png">

**Comment by mattrosno** [comment]
<img width="389" alt="image" src="https://user-images.githubusercontent.com/1691245/157520347-cca3c3fd-afbd-45e8-a2a5-148ba604278b.png">

**Comment by mattrosno** [comment]
<img width="386" alt="image" src="https://user-images.githubusercontent.com/1691245/157520999-a7529bf2-1f49-44a2-bfaf-2555cd59a172.png">

**Comment by jeanservaas** [comment]
[fixes.zip](https://github.com/carbon-design-system/carbon-platform/files/8218052/fixes.zip)
