### ISSUE TITLE
Figure out Grid narrow mode without Carbon v11 CSS grid not supporting narrow mode

### ISSUE THREAD

**Issue by mattrosno** [carbon-design-system/carbon-platform#282]
### Description

Some of these components like the search bar, results bar, sort bar, pagination properly hang into the left gutter, but should not also hang into the right gutter like shown below.

We're overriding the grid condensed mode, and we need addition overrides to achieve hanging content per spec.

### Steps to reproduce

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/1691245/155604978-76272969-e45c-4732-88a3-b70e78c77329.png">

**Comment by mattrosno** [comment]
@alisonjoseph @andreancardona looks like I made an issue for this a couple weeks ago. It looks like we can bring in `@carbon/react@0.16.0` and hopefully remove our grid overrides with the addition of the new `ColumnHang` component.

https://github.com/carbon-design-system/carbon/pull/10934

We shouldn't need to reference the Sass docs: https://github.com/carbon-design-system/carbon/blob/main/packages/grid/docs/sass.md

The docs here are good: https://carbon-react-next.netlify.app/?path=/docs/elements-grid--default

Also the demo site: https://carbon-elements.netlify.app/grid/examples/css-grid/

**Comment by alisonjoseph** [comment]
Oh nice, some of the mdx components need to hang to, so this is exciting to see! 🤞
