### ISSUE TITLE
Add footer component

### ISSUE THREAD

**Issue by mattrosno** [carbon-design-system/carbon-platform#283]
Before building this, we need to evaluate how this will render on pages without a side nav, since all pages need the footer.

<img width="1253" alt="image" src="https://user-images.githubusercontent.com/1691245/155605704-dfef170b-97b9-4d22-8dfc-06e1825694d1.png">

**Comment by mjabbink** [comment]
Something like this I think @jeanservaas 
https://www.ibm.com/able/

**Comment by alisonjoseph** [comment]
Or this site also is full width with the footer, https://www.ibm.com/design/racial-equity-in-design/ 

Looks like the IBM logo just jumps over to the first column, the rest stays the same?
