### ISSUE TITLE
Apply schema to forked PALs

### ISSUE THREAD

**Issue by mattrosno** [carbon-design-system/carbon-platform#29]
- [x] Cloud PAL: https://github.ibm.com/ibmcloud/pal @francinelucca 
  - [x] Components (public)
  - [x] Utilities (private)
  - [x] Layouts (private)
  - [x] Hooks (private)
  - [x] Connected components (private)
- [x] Watson Moments: https://github.ibm.com/watson-developer-cloud/carbon-watson-moments https://pages.github.ibm.com/data-and-ai/watson-moments/ @andreancardona 
  - [x] React (public)
  - [x] Styles (private)
- [ ] Carbon for IBM Products: https://github.ibm.com/CDAI-design/pal

**Comment by miroslavazis** [comment]
- Carbon for IBM Products: https://github.ibm.com/CDAI-design/pal
- Cloud PAL: https://github.ibm.com/ibmcloud/pal
- Carbon for IBM.com: https://github.com/carbon-design-system/carbon-for-ibm-dotcom
- Watson Moments: https://github.ibm.com/watson-developer-cloud/carbon-watson-moments
