### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by mattrosno** [carbon-design-system/carbon-platform#304]
- [x] https://github.com/carbon-design-system/carbon-platform/pull/299
- [x] https://github.com/carbon-design-system/carbon-platform/pull/300
- [x] https://github.com/carbon-design-system/carbon-platform/pull/301
- [x] https://github.com/carbon-design-system/carbon-platform/pull/302
- [x] https://github.com/carbon-design-system/carbon-platform/pull/303
- [x] https://github.com/carbon-design-system/carbon-platform/pull/333

**Comment by mattrosno** [comment]
Added #333 to list.

**Comment by jdharvey-ibm** [comment]
Done!
