### ISSUE TITLE
Switch telemetry package to esbuild

### ISSUE THREAD

**Issue by mattrosno** [carbon-design-system/carbon-platform#307]
This is just a duplicate issue to track this GHE issue and PR so our sprint board reflect the work done by our squad :).

https://github.ibm.com/carbon/ibm/issues/124

https://github.ibm.com/carbon/ibm/pull/123

**Comment by mattrosno** [comment]
@jdharvey-ibm can this be closed?

**Comment by jdharvey-ibm** [comment]
New version published. Message sent in a few of the slack channels. https://www.npmjs.com/package/@carbon/telemetry/v/0.1.0
