### ISSUE TITLE
web-app(catalog): broken pagination validation 

### ISSUE THREAD

**Issue by francinelucca** [carbon-design-system/carbon-platform#310]
### Description

We're missing some navigation validations for the pagination component in the catalog which makes it possible to get stuck with no content (on search or page change) when there should be content

### Steps to reproduce

1 - Select an items per page amount that allows you to navigate to second page
2 - Go to second page
3 -  Select an items per page amount that makes all content fit in first page 

You are now stuck with no content

------
1 - Select an items per page amount that allows you to navigate to second page
2 - Go to second page
3 -  Perform a search that returns a small subset of items

You are now stuck with no content

-------
1 - manually modify page number in browser query to an invalid page number

You are now stuck with no content

**Comment by mattrosno** [comment]
@francinelucca great catch. We need to reset page to 0 (or 1, whatever we use for first) whenever search, results per page, or the filter is updated. Also add error handling for invalid or malformed page number from the URL query.
