### ISSUE TITLE
Persist filter, search, and pagination to local storage like sort and view

### ISSUE THREAD

**Issue by mattrosno** [carbon-design-system/carbon-platform#313]

**Comment by francinelucca** [comment]
need to rethink this after our talk today @mattrosno , @jdharvey-ibm . I'm assuming this no longer applies? or...?

**Comment by mattrosno** [comment]
Here's what I'm seeing on main branch. To summarize the problem: we're getting race conditions when loading the page and trying to read values from both the URL and from local storage.

Our recommended solution:

1. Anything that affects the data that we fetch should be driven by the URL only. That's currently search, page, items, filter, and sort. This means the URL can be shared and the recipient will see the same data.
2. Anything that's only presentational in nature (doesn't affect the fetched data) can be persisted to local storage and not URL. That's currently just the view (grid or list) right now. We can still persist that to local storage on a per-page basis as maybe a user prefers to view components in grid and functions in list.

This should simplify our logic to handle all this and prevent race conditions. I'm confident in the approach because after using the catalog and stepping into an asset detail page, browser back includes the URL query string so you'll see exactly what you were previously just seeing.

The as-is on main branch:

<img width="1392" alt="image" src="https://user-images.githubusercontent.com/1691245/160194923-ea99b66f-3f43-4aeb-b7c1-6cfd20422f6d.png">

CC @miroslavazis because this request originally came from you.

**Comment by francinelucca** [comment]
closing this issue as it no longer applies to new approach, new dev requirement tracked in #425
