### ISSUE TITLE
Support all markdown elements

### ISSUE THREAD

**Issue by mattrosno** [carbon-design-system/carbon-platform#323]
Do we need to support basic syntax? https://www.markdownguide.org/basic-syntax

Or the full GitHub Flavored Markdown spec? https://github.github.com/gfm

We will need to support everything we support in the [Gatsby theme](https://gatsby-theme-carbon.vercel.app/components/markdown#comments). So we do need github flavored markdown. 

- [x] Heading (h1->h6 w/ autolink)
- [x] Paragraph
- [x] Link
- [x] Blockquote
- [x] Ordered list
- [x] Unordered list
- [x] #351
- [x] #595
- [x] #561
- [x] #499

**Comment by alisonjoseph** [comment]
We will need to support everything we support in the [Gatsby theme](https://gatsby-theme-carbon.vercel.app/components/markdown#comments). So everything in basic syntax plus tables.

**Comment by mattrosno** [comment]
@alisonjoseph closing this! Looks like we've completed this epic.
