### ISSUE TITLE
Render nested lists with correct styles in MDX

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon-platform#351]
We need to be able to pass in a prop to nested lists rendered with mdx to correctly pull in Carbon styles.

This is a bug because as-is, the bullets are wrong.

**Comment by mattrosno** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-624c3fc8b7972e001130fef7/issues/carbon-design-system/carbon-platform/351?planning-poker) with ZenHub @alisonjoseph @andreancardona @francinelucca
