### ISSUE TITLE
Add full code snippet functionality to MDX component

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon-platform#363]
Add full code component functionality to match Gatsby theme

- [ ] Path / src links
- [ ] Prism syntax highlighting

**Comment by mattrosno** [comment]
Not high priority because the as-is code block works, it just doesn't have feature parity with Carbon Gatsby theme.

**Comment by mattrosno** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-624c3fc8b7972e001130fef7/issues/carbon-design-system/carbon-platform/363?planning-poker) with ZenHub @alisonjoseph @andreancardona @francinelucca
