### ISSUE TITLE
Add remark-gfm plugin to MDX

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon-platform#364]
Ref #323 

This is need to render tables and any other github flavored markdown so we have the same support we currently have in the gatsby theme. 

Add [remark-gfm ](https://github.com/remarkjs/remark-gfm)plugin.

Ran into issues adding since this package is ESM only

Example where this needs to get added in `next.js.config`
```
const remarkGfm = require('remark-gfm')
const path = require('path')
const libraries = require('./data/libraries')
const withMDX = require('@next/mdx')({
  extension: /\.mdx?$/,
  options: {
    remarkPlugins: [remarkGfm],
    providerImportSource: '@mdx-js/react'
  }
})
```

Example repo I found where someone has it working https://github.com/Code-Hex/code-hex.github.io/pull/46/files#diff-1002271eab1e3c815fbbc299851bcd5bd3fb16efbce591c4803bf9d6314924feR5

**Comment by mattrosno** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-624c3fc8b7972e001130fef7/issues/carbon-design-system/carbon-platform/364?planning-poker) with ZenHub @alisonjoseph @andreancardona @francinelucca @jdharvey-ibm
