### ISSUE TITLE
Enhance asset landing page with new content and links

### ISSUE THREAD

**Issue by mattrosno** [carbon-design-system/carbon-platform#369]
https://www.figma.com/file/j0jgy6QBNV1UtyUN0nkzSg/v0.2-Asset-Landing-Page?node-id=0%3A1

**Design**

- [x] Share copy updates @aubrey-oneal 
- [x] Draw new hero background image (Thy?)
- [x] Redlines for modified page @kingtraceyj 
- [x] Export new images for featured content @kingtraceyj 

**Dev**

- [ ] Update Hero component with new background image placement and reduced copy
- [ ] Update existing copy
- [ ] Link to asset catalogs
- [ ] Link to collections
- [ ] Link to featured libraries
- [ ] Update roadmap copy @mattrosno

**Comment by kingtraceyj** [comment]
Final redlines: https://ibm.box.com/s/qwt7h1t2kw9dalhasiukg6w97y03zcyb

Still needs a few copy edits. For discussion, where is the best place to keep final copy? Redlines? Boxnote? Figma?

**Comment by mattrosno** [comment]
@kingtraceyj @aubrey-oneal your call on final copy. Maybe a Box note in here? https://ibm.ent.box.com/folder/158457453079

@aubrey-oneal @ljcarot @andreancardona just a heads up, I'm going to make a pass over the roadmap copy with suggested content that reflects our progress and discussions from yesterday. I will share when ready for review. @andreancardona I wouldn't mess with the roadmap portion of the assets landing page yet.

**Comment by mattrosno** [comment]
@andreancardona you can get colors for this portion here: https://github.com/carbon-design-system/carbon-platform/blob/main/services/web-app/data/type.js

<img width="1082" alt="image" src="https://user-images.githubusercontent.com/1691245/160853859-68cdb633-7571-4586-8b82-6d27bd18e1c6.png">

**Comment by mattrosno** [comment]
@kingtraceyj @andreancardona let me know if you want to talk image format. I recommend JPG or PNG at 3x. Current page is all PNGs for hero and roadmap images.

3x for 5k displays, and Next.js will downsize the image for us for everything else.

Not SVG because gradients like these are hard to get right in SVG. Not worth the trouble.
<img width="145" alt="image" src="https://user-images.githubusercontent.com/1691245/160858549-4eb340cd-5e7a-408d-857b-7a6e207bbe4a.png">

I'd export the hero image where the illustration takes up the full image. No gutter baked in. That makes it easier for us to position the image across our various breakpoints.
<img width="360" alt="image" src="https://user-images.githubusercontent.com/1691245/160858837-06063f80-6edd-49e5-9853-c79595ba1970.png">

**Comment by kingtraceyj** [comment]
landing page assets:

**Header**
![v0-2_header](https://user-images.githubusercontent.com/20582179/161782487-e1766e65-c39f-4e54-b9ec-fbade52b503a.png)

**Feature cards:**

Chart library:
![Charts_collection](https://user-images.githubusercontent.com/20582179/161782198-3f5aaa50-ba26-471f-a11f-868809bcc419.png)

React library:
![carbon_react_library](https://user-images.githubusercontent.com/20582179/161782820-9569657c-e3dd-443a-812b-b28c56e8b06a.png)


Card icons:
[Card-Icons.zip](https://github.com/carbon-design-system/carbon-platform/files/8419264/Card-Icons.zip)

**Comment by kingtraceyj** [comment]
@alisonjoseph and @andreancardona jeannie just updated the roadmap images as well! hot off the press
[New_roadmap_imgs.zip](https://github.com/carbon-design-system/carbon-platform/files/8419331/New_roadmap_imgs.zip)
!

**Comment by alisonjoseph** [comment]
@kingtraceyj looks like the roadmap images are missing the background? ![Screen Shot 2022-04-05 at 2.51.16 PM.png](https://images.zenhubusercontent.com/5667369b638e718c995f3b3e/3ea30fbd-422e-4e47-9fc3-46c109f577e2)

**Comment by jeanservaas** [comment]
Here @andreancardona will these work?

[roadmap_imgs.zip](https://github.com/carbon-design-system/carbon-platform/files/8428934/roadmap_imgs.zip)

**Comment by alisonjoseph** [comment]
![carbon-next-v0 1](https://user-images.githubusercontent.com/2753488/162062774-06eb2149-d80a-44e0-9f22-0db3b0901938.png)

vs

new image
![roadmap_v0 1](https://user-images.githubusercontent.com/2753488/162063138-8da23ca2-2a63-4505-8514-614034143dcf.png)

@jeanservaas looks like the border/background is part of the image, and is missing in the updates ones?

**Comment by jeanservaas** [comment]
Uggggg crap. i must've been on an old file. Hang tight.

**Comment by jeanservaas** [comment]
OMG @andreancardona I'm so sorry I misunderstood what you were asking for. OMG we did those images late at night and the final version wasn't saved somehow!!!! I had to rebuild those colors and arrows in there. 

Sorry again about the confusion. These should be correct.

[roadmap_imgs_revised.zip](https://github.com/carbon-design-system/carbon-platform/files/8434960/roadmap_imgs_revised.zip)
