### ISSUE TITLE
Add Slack support channels to schema and render in library detail page

### ISSUE THREAD

**Issue by mattrosno** [carbon-design-system/carbon-platform#373]
- Along with other contact information

**Questions**

- [ ] Would there be value to putting this in the schema or do we allow teams to specify this through freeform markdown in the library detail page?
- [ ] Would we want more than one Slack channel per library?

**Comment by aubrey-oneal** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-624ca8ad03d709001dc542bf/issues/carbon-design-system/carbon-platform/373?planning-poker) with ZenHub @kingtraceyj

**Comment by mattrosno** [comment]
Closing this in favor of a new issue.
