### ISSUE TITLE
Library side nav and back functionality

### ISSUE THREAD

**Issue by mattrosno** [carbon-design-system/carbon-platform#374]
**Design**

- [x] Redlines https://ibm.ent.box.com/file/928877865078
- [x] Motion
- [x] Accessibility considerations ("tree" under the hood?) @kingtraceyj 

**All**

- [x] Design review

**Comment by mattrosno** [comment]
13 for starters. Less if we're able to extend Carbon's side nav. More if we need to do a custom tree view component.

**Comment by mattrosno** [comment]
Another option is to use https://carbon-components-react.netlify.app/?path=/docs/experimental-unstable-treeview--default if we could use a right-justified chevron instead of the default left-justified arrow to show open and closed trees.

Can we do that with CSS overrides? Or would we need to contribute an upstream prop to pass in our own icon and maybe a prop for icon alignment as well? Similar to how accordion has an `align` prop with `start` and `end`?

https://carbon-components-react.netlify.app/?path=/docs/components-accordion--accordion-story

**Comment by kingtraceyj** [comment]
@mattrosno and @alisonjoseph mike sent me these links to a side nav that slides in from another team:

Storybook: [http://dev.maggieryder.com/storybook/?selectedKind=JQuery%20dl-menu%20copy&selectedSt[…]&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs](http://dev.maggieryder.com/storybook/?selectedKind=JQuery%20dl-menu%20copy&selectedStory=sliding%20transition&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs)

Click in “Systems” in left nav and then “IBM Watson” or “IBM Cloud”
https://github.ibm.com/brand/center/issues/465
https://github.ibm.com/brand/center/issues/431
https://github.com/carbon-design-system/gatsby-theme-carbon/issues/587

**Comment by mattrosno** [comment]
All epic issues closed 🎉 closing the epic! @alisonjoseph @francinelucca
