### ISSUE TITLE
Add design kits schema

### ISSUE THREAD

**Issue by mattrosno** [carbon-design-system/carbon-platform#376]
**Questions**

- [x] Do design kits belong to libraries and assets? Or are design kits a third resource type (libraries, assets, kits) that we index, then reference across libraries and assets?
  - Third resource type
- [x] If we create a new resource to index kits, would we want these exposed in a catalog of kits?
  - No, we'll just have a markdown page for design kits "getting started" but with a new MDX component to represent a kit
- [x] Would each indexed design kit needs its own detail page? Or would we link out to it (link or action)?
  - Detail pages are not needed

**To do**

- [x] Add schema
  - [x] Resource
  - [x] Relationships
- [x] Add schema validation
- [x] Add indexes
- [x] Add relationships
- [x] Create issue for new MDX component

@aubrey-oneal 

- [x] Design kit `type` values and definitions
- [x] Review indexed statuses and determine if any need `note`s and `license`... really everything indexed

**Comment by mattrosno** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Carbon-Platform-624c3fc8b7972e001130fef7/issues/carbon-design-system/carbon-platform/376?planning-poker) with ZenHub @jdharvey-ibm @alisonjoseph @francinelucca

**Comment by aubrey-oneal** [comment]
Here are the 'core' kits:

<img width="392" alt="Screen Shot 2022-04-19 at 10 22 31 AM" src="https://user-images.githubusercontent.com/47198241/164038844-c13c4dc1-5b78-4b28-b3e0-9df7c5bbe41f.png">

**Comment by mattrosno** [comment]
Outstanding questions:

1. Do we need detail pages per kit?
2. Do we need a catalog of kits that only shows structured data? Or a markdown "getting started" type of page that has body copy inline with resource cards that have data coming form our indexed kits (to show real-time status, etc.)
3. Would we want to show compatible/applicable kits per library? Per asset too? Or both?

**Comment by aubrey-oneal** [comment]
Met with @jeanservaas and Anna to discuss definition of design kits. 
1. Based on our conversation, a design kit is a file that contains elements or components or other utilities. For example, White Theme is a design kit that contains components. Color styles and text styles are design kits (plural) that contain elements. 
2. From this we can have the following data in our Schema that is surface in Get Started. 
- Type: universal, local
- Tool availability: Figma, Sketch, Adobe XD, Axure
- Contains: Elements, Components, Utility, etc.
3. We decided on Universal design kits as a term to refer to all the 'cannon' or 'core' kits designers should get started with. And local to refer to any PAL libraries or other add-ons.
4. We will still need to exchange 'Design kit' for 'Library' in tool tutorials if that is the term the tool uses.

Here is an example of how it might surface in Getting started. 

Step 3: Get universal design kits
<img width="1054" alt="Screen Shot 2022-04-19 at 12 57 48 PM" src="https://user-images.githubusercontent.com/47198241/164066795-9327d71d-cdb2-4465-b953-beffe59b6b0e.png">

Step 5: Get local design kits
<img width="1008" alt="Screen Shot 2022-04-19 at 12 59 57 PM" src="https://user-images.githubusercontent.com/47198241/164066830-17fe9457-6936-495d-b279-bb7fb212a5ac.png">

**Comment by mattrosno** [comment]
@aubrey-oneal the type (elements, components, utility) can we have it so a kit only has one type? Or are there examples where a kit has elements and components so it needs both stated?

Side note, I think we'll want to save global vs local in a consistent manner as libraries/assets that I can show an example of.

**Comment by aubrey-oneal** [comment]
@mattrosno I can't think of a situation where a design kit has multiple types. I think we should aim for one type per kit. The point is to set an expectation for what the designer is installing/downloading.

Not following your second point. Do you mean it would be good practice for us to have playbacks that include one universal design kit and one local design kit example to help our audience see the big picture-- and the same for Libraries?

**Comment by mattrosno** [comment]
@aubrey-oneal I'll show in an example of how we can treat local design kits. I don't think we should show local design kits in the global design kits page, just like we don't show local components in the global asset catalogs.

That is a v2 thing when we're able to offer team-specific catalogs and guidance (so teams have consolidated global and local assets/kits.)

**Comment by aubrey-oneal** [comment]
@mattrosno let's try out the following definitions for types. Feel free to wordsmith.

Components: These design kits contain high fidelity components which have guidance and code on the Carbon platform.

Elements: These design kits implement part of the IBM Design Language. Elements include color, icons, pictograms, text, the Grid template, and UI Shell template. 

Wireframes: These design kits contain low fidelity and mid fidelity wireframes, allowing designers to prototype concepts before committing to high fidelity components.

Guidelines: These kits contain bite sized guidance and tools to help with handoff to developers.

**Comment by aubrey-oneal** [comment]
Anna helped me better understand the relationship between kits:

<img width="986" alt="image (3)" src="https://user-images.githubusercontent.com/47198241/165374019-c8dbe8a7-993c-4d76-ac8e-0c3c2538d584.png">

**Comment by aubrey-oneal** [comment]
Here is an example of the dependencies in Figma for dotcom (via Rich Kummer)

We have a few dependencies in our Figma libraries:
Type tokens from Text Styles - IBM Design Language
Color styles from White theme - Carbon Design System
Icons from Icons - IBM Design Language
Pictograms from Pictograms - IBM Design Language

**Comment by aubrey-oneal** [comment]
@mattrosno after talking to Tracey and Jeannie we want the notes on any design kit to be very short (perhaps structured in the future). For now the only notes we found to include are

'Not symbolized' for data-viz-sketch
'Design only' for the four mobile kits
