### ISSUE TITLE
Onboard designers to EDT dev environment

### ISSUE THREAD

**Issue by aubrey-oneal** [carbon-design-system/carbon-platform#386]
### Summary

Ann and Aubrey are focusing on improving the Coach review process and need help getting their dev environment set up.

### Available resources

https://github.ibm.com/Design/EDT/wiki/Development-Setup

**Comment by mattrosno** [comment]
Hi @aubrey-oneal - I'm closing this as it seems to be an issue for EDT and not Carbon Platform.
