### ISSUE TITLE
Address Github API rate limiting

### ISSUE THREAD

**Issue by francinelucca** [carbon-design-system/carbon-platform#388]
Private Beta hitting public github (not signed in) API Rate limiting, causes some (ISR) pages to not load

**Comment by kingtraceyj** [comment]
@mattrosno do you have more detail for on this for design deliverables??????

**Comment by mattrosno** [comment]
@francinelucca are we still running into this issue?

**Comment by francinelucca** [comment]
I think we're safe to close this? @jdharvey-ibm. This hasn't seemed to be an issue in PROD for a while now; As far as I can tell in dev I can pull *all* static content once an hour (token apis call limit refreshes every hour), but PROD never fetches all content at once except for build time so we should be good? 
<img width="742" alt="image" src="https://user-images.githubusercontent.com/40550942/180793937-0c208c98-01c6-44a9-8bd1-ecced5e1f143.png">

**Comment by jdharvey-ibm** [comment]
Closing this. We can revisit it in the future if it becomes an issue again. When we reintroduce private repos, there will need to be a GitHub app in place to handle auth and rate limiting on a per-repo basis.
