### ISSUE TITLE
Web App: Broken Build, webpack errors

### ISSUE THREAD

**Issue by francinelucca** [carbon-design-system/carbon-platform#391]
### Description

![image](https://user-images.githubusercontent.com/40550942/158416364-ba2d9b00-1524-4a99-ab25-542f0c3409b5.png)
https://github.com/carbon-design-system/carbon-platform/runs/5549154294?check_suite_focus=true

### Steps to reproduce

Run from root: `CARBON_RUN_MODE=PROD node packages/micromanage docker --build @carbon-platform/web-app`

**Comment by jdharvey-ibm** [comment]
I wasn't able to pinpoint the source of the problem. It seems like no matter what I change, I still see the same issue that @francinelucca pasted above. This seems to have been introduced as a result of merging in the mdx PR #340
