### ISSUE TITLE
web-app: useQueryState: separate responsibilities

### ISSUE THREAD

**Issue by francinelucca** [carbon-design-system/carbon-platform#425]
See discussion on #313. 

**Summary**

- [x] Separate useQueryState into two, single-responsibility hooks:
  - useQueryState: only handles state through the query (non-persistent params, e.g.: page, pageCount, filter...)
  - useLocalState: only handles state through localStorage (persistent params, e.g.: view)

- [x] Revise usage of `useQueryState` across the app after refactor and move into `useLocalState` if necessary (probably only for `view` for now)

**Comment by francinelucca** [comment]
Added summary, does this need further info or can we move into Ready for Est. @mattrosno ?

**Comment by mattrosno** [comment]
Thank you! I moved to the estimates pipeline.

**Comment by mattrosno** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-624c3fc8b7972e001130fef7/issues/carbon-design-system/carbon-platform/425?planning-poker) with ZenHub @alisonjoseph @andreancardona @francinelucca
