### ISSUE TITLE
Content migration plan for v1

### ISSUE THREAD

**Issue by kingtraceyj** [carbon-design-system/carbon-platform#438]
### Summary

Plan to move content from current Carbon to Carbon platform for v1.

Figma: https://www.figma.com/file/NusJZnT9zWi3e21v0Bybf6/Carbon-Platform-V1.0-Content-Audit?node-id=12%3A1777
Airtable - Carbon ecosystem content: https://airtable.com/appQVznCGJPoiODCq/tblunS3vygGrIpbSL/viwTvhE9kfj6ulLAH?blocks=hide

**Comment by kingtraceyj** [comment]
#439 Verify LHN proposal + content plan for V1.0
#440 V0.2 Release: Library documentation
#441 V1.0 Release: Getting Started
#442 V1.0 Release: About Carbon
#443 V1.0: Migrate pages as a temporary MVP

**Comment by mattrosno** [comment]
@kingtraceyj @aubrey-oneal closing this as all issues are closed.
