### ISSUE TITLE
Verify LHN proposal + content plan for v1

### ISSUE THREAD

**Issue by kingtraceyj** [carbon-design-system/carbon-platform#439]
https://www.figma.com/file/NusJZnT9zWi3e21v0Bybf6/Carbon-Platform-V1.0-Content-Audit?node-id=12%3A1777

To do:

- [x] Align with Carbon core on migration plan (Anna and Lauren)
- [x] Preliminary prototype

**Comment by aubrey-oneal** [comment]
[Content migration plan for v1 #438.pdf](https://github.com/carbon-design-system/carbon-platform/files/8474416/Content.migration.plan.for.v1.438.pdf)

Above it the planned left hand nav for V1.0 (June release). The notes on the side show the expected work to be done in our content migration plan for each nav item.

**Comment by aubrey-oneal** [comment]
Some minor updates to help with migration

[Group 106.pdf](https://github.com/carbon-design-system/carbon-platform/files/8765498/Group.106.pdf)
