### ISSUE TITLE
Library documentation migration plan

### ISSUE THREAD

**Issue by kingtraceyj** [carbon-design-system/carbon-platform#440]
### Description
Create designs and preliminary content for the Library documentation pages for V1.0 release. 

### Deliverable
https://www.figma.com/file/K6HobXD4KXUIdkLrVjUzwK/LibraryDetail_CarbonReact?node-id=0%3A1

To do:

- [x] Aubrey and Tracey to decide where content is going, making sure it aligns with current library detail page designs, align with team on designs and preliminary content
- [x] Outstanding decision to be made: Will we include contributors and maintainers or is this a PI issue?

**Comment by kingtraceyj** [comment]
current library docs IA: https://www.figma.com/file/K6HobXD4KXUIdkLrVjUzwK/LibraryDetail_CarbonReact?node-id=0%3A1

**Comment by mattrosno** [comment]
We will be able to close this issue once https://github.com/carbon-design-system/carbon-platform/issues/366 epic is fully populated.
