### ISSUE TITLE
V1.0 Release: How Carbon works Content

### ISSUE THREAD

**Issue by kingtraceyj** [carbon-design-system/carbon-platform#442]
### Goal of the page
Describe the Carbon ecosystem and how it works. 

- This will introduce the concept global>domain>team resources (or whatever language we align on) and also outline how governing bodies fit into the ecosystem. 
- This will also result in the deprecation/re-organization of the following CDS pages: 

### Sections of the page:
- What is Carbon (can use definition in landing page)
- Carbon ecosystem (can take imagery from get started if it fits)
- the Carbon team (this should appear in Libraries but there is an outstanding issue around privacy compliance)
- Partners

### To do:

- [x] Aubrey to draft content. 
- [x] Content review with design team
- [X] Second round of content creation based on feedback

**Comment by jeanservaas** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-624ca8ad03d709001dc542bf/issues/carbon-design-system/carbon-platform/442?planning-poker) with ZenHub @aubrey-oneal @kingtraceyj
