### ISSUE TITLE
V1.0: Migrate pages as a temporary MVP

### ISSUE THREAD

**Issue by kingtraceyj** [carbon-design-system/carbon-platform#443]
- What's happening 
- Case Studies
- Contribute
- FAQ and Contact (taking this out of the 'Help' drop down)

We have future plans for these pages, but reworking these is out of scope for V1.0

**Comment by aubrey-oneal** [comment]
We no longer need this issue. Content has been migrated via remote MDX according to LHN proposal.

**Comment by aubrey-oneal** [comment]
See above
