### ISSUE TITLE
V1 research plan

### ISSUE THREAD

**Issue by kingtraceyj** [carbon-design-system/carbon-platform#446]
Outline a plan for user testing we want to be done for V1

**Additional information:**
Will use v1 prototype to test interactions

### To do:
**Outline:**

- [x] what are the flows and assumptions we want to test?
- [x] what types of users do we want to look for?
- [x] what is our timeline?
- [ ] how will we document our findings?

**Comment by kingtraceyj** [comment]
**Things to test for:**
- [ ]  Relationship of assets and libraries (or choose 1-2 small areas to focus on for now)

**Comment by aubrey-oneal** [comment]
Here is our box folder with a started protocol and tear sheet and I've logged our study in our airtable. Once we know who our participants are I can add them to our airtable too. 
https://ibm.ent.box.com/folder/162588959495
https://airtable.com/app2QyMSSvHUAiOzt/tbl6qslk1Y8RPj1pb/viwFgHU3OOlLgoyFZ?blocks=hide

**Comment by kingtraceyj** [comment]
Flows and assumptions:

Timeline:
Sprint 16: plan
Sprint 17: finalize script, recruit users, finish prototype
Sprint 18: test users
Sprint 19: present findings

**Comment by aubrey-oneal** [comment]
@kingtraceyj do you feel ready to close this out? I suggest we make individual sprint 17 issue for recruiting, finalizing script, and finishing prototype.
