### ISSUE TITLE
Communication plan for V1 release

### ISSUE THREAD

**Issue by kingtraceyj** [carbon-design-system/carbon-platform#447]
We need to communicate to all Carbon users (and external) about the changes and why

**Additional information:**
Open questions (the new landing page ):

- How do we best get users started on the new site using the new catalog? (for instance, why are there no components in the side nav anymore)
- Libraries explanation?

### Ideas for to do:

- [x] Schedule a slot on IDL call (Oct 28)
- [x] Slack announcements
- [ ] Carbon summit
- [ ] Carbon steering committee 
- [ ] Any dev meetings this could be good in?
- [ ] Figma fridays
- [x] Medium article
- [ ] Friday hive

**PAL meetings?**
- [ ] Carbon for IBM products announcement DSAG
- [ ] Cloud PAL

**Comment by kingtraceyj** [comment]
Linda can possibly help with the comms on this.

**Comment by mattrosno** [comment]
Let's do this sprint 25!

**Comment by kingtraceyj** [comment]
**Notes from platform/system sync:**

Could cross link site when platform is ready—could be banner or something on the community component index.

Community Assets/Community index—keeping page a delete content and can put a note about Carbon next.

Should have high level callout on home page—could be banner, tile, homepage callout.

**Comment by kingtraceyj** [comment]
We are scheduled to present on the Friday IDL call on October 28th (the next available date after launch)

**Comment by kingtraceyj** [comment]
Presentation issue for internal meetings: #1279

**Comment by kingtraceyj** [comment]
Slack announcement: https://ibm.box.com/s/tascu74uw0s6oo8h0w1pybovsykv4ib1

Medium draft in notes: https://ibm.box.com/s/x0rgeuazwhtqicodv7dyjjkzq6ufm1pg
