### ISSUE TITLE
fi ligatures aren't working

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon-platform#448]
Carbon Next
<img width="96" alt="Screen Shot 2022-03-28 at 1 01 38 PM" src="https://user-images.githubusercontent.com/2753488/160459216-4fb31f8b-9508-488a-b8c9-45fb3d6ea461.png">

Example of what should be happening from the Gatsby theme
<img width="98" alt="Screen Shot 2022-03-28 at 1 00 45 PM" src="https://user-images.githubusercontent.com/2753488/160459218-dce40498-149d-4a6d-8946-f4de62ec35b4.png">

_Note, this may be an issue coming from core Carbon_ 👀

**Comment by mattrosno** [comment]
We didn't do anything custom for fonts; using Carbon v11 straight up. This is all happening for us with `@use '@carbon/react';` in `/styles/vendor/_carbon.scss`.

**Comment by mjabbink** [comment]
Probably core Carbon. I think the dotcom sites are not missing that as well.

**Comment by alisonjoseph** [comment]
Confirmed this is an issue coming from core Carbon

**Comment by mjabbink** [comment]
When will this be reflected in platform site?

**Comment by mattrosno** [comment]
@mjabbink this isn't supported by default through `@carbon/styles` now, but I see there's a workaround. I'll open a PR now.

**Comment by mjabbink** [comment]
This should 100% be default seeting.

**Comment by mjabbink** [comment]
It has been since 2017 until some recent mucking about with Plex.

**Comment by mattrosno** [comment]
@mjabbink I'd subscribe to this issue for progress on making this the default setting: https://github.com/carbon-design-system/carbon/issues/11661
