### ISSUE TITLE
Remove thumbnails from functions catalog

### ISSUE THREAD

**Issue by mattrosno** [carbon-design-system/carbon-platform#449]
After reviewing the [spec](https://github.com/carbon-design-system/carbon-platform/issues/449#issuecomment-1087850257), it looks like we need to this in the functions catalog:

- [ ] Remove grid/list switcher so it's only list view
- [ ] Remove thumbnail from list view
- [ ] When removing thumbnail, set height of the rows
- [ ] Still use aspect ratio at `sm` breakpoint

Note: these changes need made at the functions catalog level, not at the catalog item level if type function, because when there are catalogs with mixed types (e.g. collections), we'll still display placeholder thumbnails for functions so there is visual consistency.

**Comment by mattrosno** [comment]
@kingtraceyj can you add any detail? Or do we simply remove thumnails in the functions catalog?
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/1691245/160463842-620d08ff-fffa-4e73-927a-413686cc5bd0.png">

**Comment by alisonjoseph** [comment]
If we remove the thumbnail images, what about the grid view? Or do we hide grid view for functions along with images?

**Comment by kingtraceyj** [comment]
The cards will look like the library overview list. Here are the [redlines](https://ibm.box.com/s/s6btwm637udnek3pbjtfem412kgw83hp) for that. I can do a functions specific redline though. We will need to add the asset tags that libraries doesn't have. 

![image](https://user-images.githubusercontent.com/20582179/161590314-09467934-065b-4680-9e80-88b147153034.png)

**Comment by kingtraceyj** [comment]
@francinelucca I'll get you an updated card with the asset and framework tags but this is the basic structure.

**Comment by kingtraceyj** [comment]
@francinelucca updated redlines for functions catalog! https://ibm.box.com/s/w6xjolukzbiv9jhqa8di207d7rfy96j4

**Comment by mattrosno** [comment]
@kingtraceyj I'm seeing this in your spec:

<img width="747" alt="image" src="https://user-images.githubusercontent.com/1691245/163584215-997bbe1a-9002-4b29-b675-9bae16809795.png">

The catalog item component looks like this for all catalogs, all collections:

<img width="425" alt="image" src="https://user-images.githubusercontent.com/1691245/163584338-f6bfde24-03e3-489b-a58a-e482d151130f.png">

Why the change to move status top right and type and framework bottom left?

1. It would be nice for this to be consistent across all asset types.
2. We'll likely have other meta information that we'll want to show like usage counts and accessibility rating, which would go inline with status at bigger breakpoints. If status remains bottom left, then there's room to also show some of that information on small breakpoint if we find that valuable.

**Comment by mattrosno** [comment]
@kingtraceyj once the above questions are resolved, we can move this to "ready for development" in the design workspace.

**Comment by kingtraceyj** [comment]
@mattrosno yeah. i do think we should be consistent. i'm tying to remember why we went in that direction. @jeanservaas do you remember why we ended up switching the tags with status on mobile for functions?

**Comment by mattrosno** [comment]
@kingtraceyj can we keep the function catalog item content mobile positioning as-is so it is consistent for all catalog items?

**Comment by jeanservaas** [comment]
@kingtraceyj we did this because we didn't have the real estate for the tags in the upper right hand corner in these small space scenarios.

**Comment by mattrosno** [comment]
@kingtraceyj since this became a design issue (per label), that means this is a design story point, so can you and @alisonjoseph make a dev issue for this and align on what needs done?

**Comment by kingtraceyj** [comment]
For both tiles with a thumbnail and without a thumbnail, small break points are the same. The status moves to upper right and tags move to lower left.

For a tile with a thumbnail, at medium breakpoints, the status moves to upper right and tags move to lower left.

For a tile without a thumbnail, at medium breakpoints, the status and tags stay in place. There is room for the tags to stay in the upper right.

### Here are the specs for a catalog with a thumbnail:

**medium:**
![image](https://user-images.githubusercontent.com/20582179/173854248-78fca766-783d-4f24-903f-d41acafb2ade.png)

**small breakpoint:**
content section same as medium but remove thumbnail
![image](https://user-images.githubusercontent.com/20582179/173854424-99546c3b-afb4-45a3-ba9f-f190fd017bb3.png) 

### Catalog tile without a thumbnail:

**medium break point:**
![image](https://user-images.githubusercontent.com/20582179/173854065-0d151922-ac7d-4f36-bd07-6ea5f3442be8.png)

**small break point:**
![image](https://user-images.githubusercontent.com/20582179/173854140-f9a29513-d79c-4c42-8c7b-547dbccb4838.png)

**Comment by alisonjoseph** [comment]
Created dev issue https://github.com/carbon-design-system/carbon-platform/issues/886
