### ISSUE TITLE
Shorten tag display names

### ISSUE THREAD

**Issue by mattrosno** [carbon-design-system/carbon-platform#465]
Some of our component tags are long.

<img width="969" alt="image" src="https://user-images.githubusercontent.com/1691245/160921994-5c19153b-c235-4407-aba9-8d2f3a220eaf.png">

Same with our data viz collection tags.

<img width="966" alt="image" src="https://user-images.githubusercontent.com/1691245/160922045-7ce4b96c-3b78-4bd4-b104-bed34185bfcc.png">

In order to shorten these as tags in the filter popover, as well in the asset table per library:

<img width="992" alt="image" src="https://user-images.githubusercontent.com/1691245/160922235-76450ac3-39ce-4a32-a146-39f9fbb5f5b6.png">

Don't update the keys used in the schema, but update the display names to:

- [x] Contextual nav
- [x] Data viz
- [x] Structural nav
- [x] Geo overlay
- [x] Geo distortion

**Comment by mattrosno** [comment]
@aubrey-oneal @kingtraceyj @jeanservaas can you review this issue description and the five checkboxes above to make sure I documented the request correctly?

**Comment by aubrey-oneal** [comment]
@mattrosno yes the changes are documented correctly and are ready for dev.

**Comment by mattrosno** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-624c3fc8b7972e001130fef7/issues/carbon-design-system/carbon-platform/465?planning-poker) with ZenHub @alisonjoseph @andreancardona @francinelucca @jdharvey-ibm
