### ISSUE TITLE
Add Google Analytics via Tealium (common.js)

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon-platform#469]
https://www.ibm.com/standards/carbon/developing/building-for-ibm-dotcom#ibm.com-tag-management-and-site-analytics

https://pages.github.ibm.com/digital-behavior/docs/tms-instrumentation.html

**Comment by ljcarot** [comment]
If GA could be added sooner than v1.0, we could begin to test and ensure we are seeing the data in GA.

**Comment by alisonjoseph** [comment]
@ljcarot do we have this information that we will need to add this? category, siteID, industry, owner? This is a screen shot from the IDL website.

![Screen Shot 2022-04-04 at 8 23 06 AM](https://user-images.githubusercontent.com/2753488/161553299-a30f1e1f-7c73-4159-a7cd-077709d2592a.png)

**Comment by mattrosno** [comment]
Per the docs (https://pages.github.ibm.com/digital-behavior/docs/tms-instrumentation.html#23-sample-code), we'll have to call `window.ibmStats.pageview()` in places after Next.js web app hydration and subsequent page views.

**Comment by mattrosno** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-624c3fc8b7972e001130fef7/issues/carbon-design-system/carbon-platform/469?planning-poker) with ZenHub @alisonjoseph @francinelucca @jdharvey-ibm

**Comment by mattrosno** [comment]
We can reference this as an example: https://github.com/carbon-design-system/carbon-website/pull/2953
