### ISSUE TITLE
Remove footer last updated time for now

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon-platform#470]
Currently the footer shows the current year, month. Need to update to display the date of last deployment.

> Last updated 08 June 2022

**Comment by mattrosno** [comment]
Will have follow-on issue for per-page timestamps.

**Comment by mattrosno** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-624c3fc8b7972e001130fef7/issues/carbon-design-system/carbon-platform/470?planning-poker) with ZenHub @alisonjoseph @andreancardona @francinelucca @jdharvey-ibm
