### ISSUE TITLE
Add About and Standards to top nav (disabled)

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/carbon-platform#489]
Having “Standards” visible provides context to a broader information architecture to come. If “About" is another item for the nav that is around the corner I would certainly not be opposed to it being visible (disabled). It is a beta with a limited audience so I think there is more good than harm that can come out of it.

FYI 
@kingtraceyj 
@jeanservaas 
@miroslavazis

**Comment by jeanservaas** [comment]
Yes I agree with this. I think we at least add another item like 'About' and ghost it in the top nav so people know that more content is coming. It's an awkward experience, even in the interim to have nothing other than assets in the header.

**Comment by jeanservaas** [comment]
@kingtraceyj yes exactly

**Comment by mattrosno** [comment]
I updated the title since you want two disabled nav items added?

**Comment by mattrosno** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-624c3fc8b7972e001130fef7/issues/carbon-design-system/carbon-platform/489?planning-poker) with ZenHub @alisonjoseph @andreancardona @francinelucca @jdharvey-ibm
