### ISSUE TITLE
Sponsor team icons should be the same size

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/carbon-platform#490]
Reference https://github.com/carbon-design-system/carbon-platform/pull/596 for the required changes to close this issue.

The Carbon for IBM.com and Carbon icons are not on the same scale. Not sure which one is the intended size so will let @kingtraceyj and @jeanservaas chime in with specs.

current
<img width="628" alt="Screen Shot 2022-04-04 at 6 36 58 PM" src="https://user-images.githubusercontent.com/32881239/161649581-af2df3b6-a0df-43f1-8f7e-10992ceb7eff.png">

**Comment by kingtraceyj** [comment]
it should be 24px:
 
![image](https://user-images.githubusercontent.com/20582179/161768914-4afd7e3b-d351-42fe-8452-5c90aa75c425.png)

redlines: https://ibm.box.com/s/vxi7hpszhg51bn668ocxukcrbz3uroy7

**Comment by mattrosno** [comment]
Confirmed this is a bug. Looks like we need to ensure that our custom sponsor SVGs render at 24px here.

**Comment by mattrosno** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-624c3fc8b7972e001130fef7/issues/carbon-design-system/carbon-platform/490?planning-poker) with ZenHub @alisonjoseph @andreancardona @francinelucca @jdharvey-ibm
