### ISSUE TITLE
Rule between dashboard items should be $border-subtle

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/carbon-platform#491]
<img width="1137" alt="Screen Shot 2022-04-04 at 6 34 50 PM" src="https://user-images.githubusercontent.com/32881239/161649759-5d4a3666-c5e5-4252-8484-92db8f86dd65.png">

FYI @jeanservaas @kingtraceyj 

Add @kingtraceyj comment that this ALSO affects the asset detail page: 

https://github.com/carbon-design-system/carbon-platform/pull/475#issuecomment-1092380003

**Comment by kingtraceyj** [comment]
the v11 token for that is `border-subtle`

**Comment by mattrosno** [comment]
As a quick experiment, I remember we built that so the borders were the same color as the background, so I was wondering if we could set `$border-subtle` as the background (e.g. red here) for a quick fix. That's a no-go, especially when we dashboard items don't fill the full last row.
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/1691245/162066050-268be060-af2b-41e0-bd44-7c843c4b92af.png">

We'll have to make a few styling changes in addition to updating color tokens. Not a huge effort. Just calling out this fix will be more than just color token changes.

**Comment by kingtraceyj** [comment]
just to document this issue, i flagged the same bug in #475 but we decided to move forward and fix it when we find the best solution in this issue.

**Comment by mattrosno** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-624c3fc8b7972e001130fef7/issues/carbon-design-system/carbon-platform/491?planning-poker) with ZenHub @andreancardona @francinelucca @alisonjoseph
