### ISSUE TITLE
Add frontmatter support for MDX pages

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon-platform#497]
We need to be able to render a mdx file with front matter.

```
---
title: Markdown
description: Usage instructions for the Markdown component
keywords: 'ibm,carbon,gatsby,mdx,markdown'
tabs: ['Page 1', 'Page 2']
---
```

- [x] title: use `<PageHeader />` component
- [x] description - add to page metadata
- [x] keywords - add to page metadata
- [x] tabs: use `<PageTabs />` component

[Gatsby theme frontmatter docs](https://gatsby-theme-carbon.vercel.app/guides/MDX)

**Comment by mattrosno** [comment]
We might be able to throw out / ignore

```markdown
hiddenFromSearch: true
tabs: ['Page 1', 'Page 2']
```

**Comment by mattrosno** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-624c3fc8b7972e001130fef7/issues/carbon-design-system/carbon-platform/497?planning-poker) with ZenHub @alisonjoseph @andreancardona @francinelucca @jdharvey-ibm

**Comment by francinelucca** [comment]
Added hiddenFromSearch task to https://github.com/carbon-design-system/carbon-platform/issues/22
