### ISSUE TITLE
Add MDX image support using Next.js image component

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon-platform#499]
- need to render static markdown images from mdx

`![alt](/assets/images/img.png)`

**Comment by mattrosno** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-624c3fc8b7972e001130fef7/issues/carbon-design-system/carbon-platform/499?planning-poker) with ZenHub @andreancardona @alisonjoseph @francinelucca @jdharvey-ibm

**Comment by mattrosno** [comment]
@alisonjoseph what @francinelucca and I landed on for now:

1. No images in the `/pages` directory
2. Mirror pages directory structure inside `/public`, and put images in there for now
3. Go unoptimized, responsive images for now with no placeholder

And I'll create a separate issue now for that.

**Comment by mattrosno** [comment]
@francinelucca per our discussion, we're supporting "local images, option B" that I detailed here: https://github.com/carbon-design-system/carbon-platform/issues/547

I wonder if we also want to support "local images, option A" (statically importing images in MDX files) so then we have options? With that, we could default to unoptimized images but then add imports for high-traffic pages so they get optimized images for now?

Maybe that means we could support `![alt](/carbon.png)` (option B), but also this with option A?

```mdx
import carbonImg from './carbon.png`

![alt](carbonImg)
```

(I don't know if that syntax would be right.)

Let's chat in our huddle in a bit.
