### ISSUE TITLE
Refactor asset catalog components for search, filter, results, pagination to work in the libraries catalog

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon-platform#500]
Visually, the libraries catalog and assets catalogs look the same for search, filter, results, empty states, and pagination.

The libraries page is currently just a list of links (basic styling). To make that more of a catalog when we have 40 or more libraries, we might need to refactor some of the asset components so they can be used here too.

**Comment by mattrosno** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Carbon-Platform-624c3fc8b7972e001130fef7/issues/carbon-design-system/carbon-platform/500?planning-poker) with ZenHub @alisonjoseph @francinelucca @jdharvey-ibm
