### ISSUE TITLE
Add next subdomain to Carbon's uptime monitoring

### ISSUE THREAD

**Issue by mattrosno** [carbon-design-system/carbon-platform#513]
https://github.com/carbon-design-system/uptime

The sooner we do this, the more data points we'll have to compare carbon-platform hosting vs carbon-website hosting.

**Comment by mattrosno** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-624c3fc8b7972e001130fef7/issues/carbon-design-system/carbon-platform/513?planning-poker) with ZenHub @alisonjoseph @francinelucca @jdharvey-ibm

**Comment by mattrosno** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-624c3fc8b7972e001130fef7/issues/carbon-design-system/carbon-platform/513?planning-poker) with ZenHub @andreancardona

**Comment by alisonjoseph** [comment]
PR: https://github.com/carbon-design-system/uptime/pull/22

**Comment by alisonjoseph** [comment]
We are currently using the 404 page as our login/landing page for the site, this triggers the uptime monitoring repo to think the site is down. Will need to update our approach to get it added.

From @jdharvey-ibm 
> looked through their docs to see if it said anything about 400 vs 200 responses and if that triggers the down notification, but I didn't find anything. None of our API routes are protected by the auth middleware, so we could add an API route called readiness that just returns a 204 and put the route to that in the config here instead. Kubernetes likes to have two health check endpoints: one called liveness and one called readiness, so adding one (or both) in the nextjs app would definitely benefit our eventual switch to k8s as well.
Those both get auto-added to all of our microservices [that are based on Nest](https://github.com/carbon-design-system/carbon-platform/blob/main/packages/api/src/main/microservice/status-endpoint/status.controller.ts), but at the moment that doesn't include the web-app service.

**Comment by alisonjoseph** [comment]
will reopen this PR once latest site without auth is deployed https://github.com/carbon-design-system/uptime/pull/22

**Comment by alisonjoseph** [comment]
https://github.com/carbon-design-system/uptime/pull/26![Screen Shot 2022-06-10 at 11.36.52 AM.png](https://images.zenhubusercontent.com/5667369b638e718c995f3b3e/f97974df-6918-456b-9011-9d7b3fed9a97)
