### ISSUE TITLE
Index Carbon Web Components

### ISSUE THREAD

**Issue by mattrosno** [carbon-design-system/carbon-platform#518]
I believe this issue is blocked until:

1. Dotcom squad moves library to carbon-for-ibm-dotcom repo
2. Dotcom squad does initial indexing (communicated by Linda)

**Tasks**

- [x] Index `Get started` library page with this content: https://www.carbondesignsystem.com/developing/frameworks/web-components

**Comment by mattrosno** [comment]
Dotcom squad is looking to do this when they are ready 🎉

**Comment by francinelucca** [comment]
I think we can close this, right? @mattrosno @alisonjoseph

**Comment by mattrosno** [comment]
@francinelucca it looks like we need to index https://carbondesignsystem.com/developing/frameworks/web-components as a `Get started` page in https://next.carbondesignsystem.com/libraries/carbon-web-components still.

(Like https://next.carbondesignsystem.com/libraries/carbon-react/latest/pages/get-started.)

**Comment by francinelucca** [comment]
https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/10048

**Comment by francinelucca** [comment]
@mattrosno now? 😃 https://next.carbondesignsystem.com/libraries/carbon-web-components/latest/pages/get-started

**Comment by mattrosno** [comment]
@francinelucca looks great!
