### ISSUE TITLE
Carbon React thumbnails for catalog

### ISSUE THREAD

**Issue by kingtraceyj** [carbon-design-system/carbon-platform#550]
Carbon react thumbnails needed to close [PR #549](https://github.com/carbon-design-system/carbon-platform/pull/549)

**Thumbnails provided:**
- [x] flex grid
- [x] form group
- [x] icon button
- [x] layer
- [x] ordered list
- [x] skeleton
- [x] unordered list
- [x] unstable heading (unstable)
- [x] unstable menu (unstable)
- [x] unstable pagination (unstable)
- [x] unstable text (unstable)
- [x] stack (component)
- [x] composed modal
- [x] error boundary

Carbon-components:
- [x] listbox
- [x] menu (same as unstable menu above)
- [x] skeleton (same as skeleton above)

**Thumbnails not provided (see comments below):**
- [x] form label (this is a child of form like 'breadcrumbitem' and should not be indexed)
- [x] tooltip icon (this should be removed from storybook, it is incorrect with the new accessibility updates

**Comment by jeanservaas** [comment]
@andreancardona @mattrosno @alisonjoseph 

There are a lot of “components” in React that's are for utility and are not proper components or are "sub-components" and would never be used alone. Thumbnails for these don't make sense for that reason... this kind of gets at the reason we don't have thumbnails for functions. 


For instance:

**Error Boundary is for utility:**

<img width="1348" alt="image" src="https://user-images.githubusercontent.com/43144260/163856932-4b70b2ef-7f07-40b4-ab80-3fe88b5bfd36.png">

**There is no design difference on the front end between "modal" and "composed modal"**

<img width="944" alt="image" src="https://user-images.githubusercontent.com/43144260/163857496-93eaeead-eb48-4291-a17b-ebbd3da09e73.png">

"Form label" is a sub-component of "form" and would never be used alone; I can make a thumbnail for "Form group," but it would also take you to the form component:

<img width="812" alt="image" src="https://user-images.githubusercontent.com/43144260/163857664-5a93e934-6483-4c9e-84a2-432d7fde9884.png">

**"tooltip icon" is a variant of tooltip that was replaced “icon-only tooltip” in v11; according to @laurenmrice that story is not supposed to be there.**

<img width="477" alt="image" src="https://user-images.githubusercontent.com/43144260/163858517-c44d6fae-9294-4721-a724-9bf1590f397d.png">

**"stack" is a helper that evenly divides/spaces everything in a group., it's more of a utility that's documented in spacing guidance... I could probably make a thumbnail, like for "Layer" but both will have more like elements docs, not traditional component docs**

<img width="679" alt="image" src="https://user-images.githubusercontent.com/43144260/163861132-0e61def6-5d4f-4663-9708-7e602fd5a4b0.png">


I'll try to make thumbs for the rest... if I have other issues I'll add them here.

**Comment by mattrosno** [comment]
@jeanservaas are you stating we have thumbnails for all components, or no? For example, the Carbon React exports `ErrorBoundary`. This is so it can be used as part of the code package's public API, just like `Button`.

https://github.com/carbon-design-system/carbon/blob/main/packages/react/src/index.js#L55

Are you saying ErrorBoundary should get no thumbnail and it looks like this?
<img width="409" alt="image" src="https://user-images.githubusercontent.com/1691245/163865275-328aa573-8643-4ecb-bb0c-a7c6d4b8f91a.png">

Or does ErrorBoundary get a thumbnail?

Or do we have dynamic placeholders where we render the asset name? (Instead of the placeholder saying "Preview image coming soon" it says "ErrorBoundary"?)

**Comment by jeanservaas** [comment]
@mattrosno 

I've listed the four thumbnails above that are problematic. The rest I will make. 

ErrorBoundary is a utility for a component it's not a component itself, it has no visual expression... these things that I've listed above are basically under-the-hood for components we already have thumbnails for... they're not used in isolation, they will not have isolated asset detail pages etc. Like if you click on "form label" in the catalog... you're just going to go to the "form" component.

I'm not sure how to handle this if they're listed individually. There is no preview image coming soon. The only thing I can think of is using the thumbnail that has already been created for the component that they are a part of. Like I showed above... there is no front end difference between modal and composed modal for instance.

There are some instances, like Layer, Stack, Flex grid that I CAN make thumbnails for, but they will not have asset detail pages like the other components — as they all relate to Elements docs, not component docs (Flex-grid= grid docs; Stack=spacing docs; Layer=theming/color docs)

These things are not all 1:1.

**Comment by andreancardona** [comment]
I think that could be a really good solution (using the same image as it's _parent_ component)

@mattrosno thoughts?

**Comment by mattrosno** [comment]
@andreancardona after chatting with @jeanservaas - we'll have a thumbnail for ErrorBoundary.

**Comment by jeanservaas** [comment]
@andreancardona 

Worked this out with Rosno... in certain cases like composed modal... we'll just use the same thumbnail image. We also worked out an idea for an ErrorBoundary thumbnail.

That leaves only two that should not be indexed 'form-label' (it's a child of form) and 'tooltip icon' (it is incorrect post v11)

I'll get the rest of these to you asap.

**Comment by andreancardona** [comment]
Awesome - I have removed the following `form-label` and `tooltip-icon`

**Comment by jeanservaas** [comment]
@andreancardona here are the new thumbs. I also included structured list because I found a mistake in the original thumbnail and fixed it.

[new-new-thumbs.zip](https://github.com/carbon-design-system/carbon-platform/files/8521845/new-new-thumbs.zip)
