### ISSUE TITLE
Thumbnails are off center at all breakpoints

### ISSUE THREAD

**Issue by jeanservaas** [carbon-design-system/carbon-platform#552]
I was just demo'ing the catalog and noticed that all of our thumbnails are consistently off center (jogged left) at all breakpoints

This is happening in both Safari and Chrome, I haven't checked Firefox.

<br>

![image.png](https://images.zenhubusercontent.com/5b96e742f28d730b01a470c0/95a13bbf-1f16-40dc-92d0-b9fe013234b7)

**Comment by mattrosno** [comment]
Confirmed I'm seeing this bug in list view.
<img width="969" alt="image" src="https://user-images.githubusercontent.com/1691245/163449178-9fe4ce86-5484-4c90-a97e-8f73f0bb9453.png">

**Comment by mattrosno** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-624c3fc8b7972e001130fef7/issues/carbon-design-system/carbon-platform/552?planning-poker) with ZenHub @alisonjoseph @francinelucca
