### ISSUE TITLE
Production is missing the favicon

### ISSUE THREAD

**Issue by mattrosno** [carbon-design-system/carbon-platform#557]
I'm seeing a 404 for the favicon.

Is SVG not supported in all browsers for the favicon? Or are we not copying it in our `Dockerfile`?

(it shows up when you're logged in, just need to add an exclusion to not return 404 if not logged in)

<img width="1430" alt="image" src="https://user-images.githubusercontent.com/1691245/163263584-5dd2de4f-2eb8-4d53-a9bc-be30d5b37ebb.png">

<img width="1430" alt="image" src="https://user-images.githubusercontent.com/1691245/163263775-7bb36954-ed1f-47e9-afd5-dbaab2371624.png">

**Comment by francinelucca** [comment]
@mattrosno does it also happen when you're logged in? I think I expect it to 404 if you're not logged in, we don't really have any exclusions right now 
<img width="1015" alt="image" src="https://user-images.githubusercontent.com/40550942/163273294-89515a43-cb11-4a60-81f6-76c5a827bfe9.png">

**Comment by mattrosno** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-624c3fc8b7972e001130fef7/issues/carbon-design-system/carbon-platform/557?planning-poker) with ZenHub @alisonjoseph @francinelucca

**Comment by francinelucca** [comment]
this should be fixed with #823 , will test on test env when deployed

**Comment by francinelucca** [comment]
tested this in my makeshift test environment and it works 👯 , moving to in review and will confirm on prod

**Comment by francinelucca** [comment]
![image](https://user-images.githubusercontent.com/40550942/173111939-06c2f3f9-7744-40cf-97b1-76fb8267722a.png)
good to close this? 👀
