### ISSUE TITLE
Render markdown table

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon-platform#561]
Create table component to match styles in Gatsby theme

https://gatsby-theme-carbon.vercel.app/components/markdown#tables
https://github.com/carbon-design-system/gatsby-theme-carbon/tree/main/packages/gatsby-theme-carbon/src/components/PageTable

**Comment by mattrosno** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-624c3fc8b7972e001130fef7/issues/carbon-design-system/carbon-platform/561?planning-poker) with ZenHub @alisonjoseph @andreancardona @francinelucca
