### ISSUE TITLE
Add asset status utility function and clean up other places we're rendering asset status

### ISSUE THREAD

**Issue by francinelucca** [carbon-design-system/carbon-platform#562]
When we pull library assets, we might want to do some transformation so that `asset.status` or some other property always has the asset status **key** (i.e., "stable"), even if status is just a value ("stable", "experimental"...), or an object ({key: "stable", note: "..."}). see note on: https://carbon-design-system.github.io/carbon-platform/resource-schemas.html#asset-status

Note: this includes fixing all places where we're doing something like
`const statusKey = asset?.content.status?.key ?? asset?.content.status ?? 'draft'` to just use the standardized property

**Comment by mattrosno** [comment]
I thought we had something in `/utils/schema.js` for this, but I guess not. That file would be a good place for this, as we have similar helpers there for getting values from our schema data model.

**Comment by mattrosno** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-624c3fc8b7972e001130fef7/issues/carbon-design-system/carbon-platform/562?planning-poker) with ZenHub @alisonjoseph @andreancardona @francinelucca
