### ISSUE TITLE
Update spacing tokens for just spacing and use rem mixin for heights/widths

### ISSUE THREAD

**Issue by andreancardona** [carbon-design-system/carbon-platform#572]
### Summary

- [x] Update spacing tokens throughout the app to follow Carbon guidelines (i.e. remove spacing tokens from unnecessary uses - width & height)
- [x] Include rem mixin

For context: https://ibm-studios.slack.com/archives/C02H44VRGQP/p1649883085903599

**Comment by mattrosno** [comment]
@andreancardona I remove the enhancement label cause it's not a feature enhancement but more of a refactor. I added dev label so it shows up in the dev ZenHub workspace. I moved it to the "ready for estimates" pipeline.

**Comment by mattrosno** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-624c3fc8b7972e001130fef7/issues/carbon-design-system/carbon-platform/572?planning-poker) with ZenHub @alisonjoseph @andreancardona @francinelucca
