### ISSUE TITLE
web-app: collpasible frameworks: Aspect Ratio - ghost framework (+1)

### ISSUE THREAD

**Issue by francinelucca** [carbon-design-system/carbon-platform#574]
### Description

aspect ratio displaying "react+1" on frameworks but when filtering by every framework but `react`, it's showing up as blank, where's that extra +1 coming from?
Ideas:  could it be styles? are we not taking into account `noIndex`?  🤔 
<img width="412" alt="image" src="https://user-images.githubusercontent.com/40550942/163603238-4cc52ad9-0e0e-4428-8042-cee730a07818.png">
<img width="1217" alt="image" src="https://user-images.githubusercontent.com/40550942/163603285-3beb5ee9-2974-4caa-b8df-6be904dd90e2.png">

### Steps to reproduce

1 - Go into app components view, search for "aspect ratio" , note 1 result showing "react +1" on card on framework 
2 - Filter by every framework but react, note no results

Where's the extra framework coming from?

**Comment by mattrosno** [comment]
@francinelucca I don't see this on production. Is this still an issue if you disable `INDEX_ALL=1`?

**Comment by francinelucca** [comment]
> @francinelucca I don't see this on production. Is this still an issue if you disable `INDEX_ALL=1`?

I tested this on `451-index-carbon-react`, we don't have carbon-react on prod yet; but you're right, it's an `INDEX_ALL` thing 🐵 😅 😳 ... Closing hehe
