### ISSUE TITLE
Add resource links to library detail page

### ISSUE THREAD

**Issue by mattrosno** [carbon-design-system/carbon-platform#578]
After talking with @aubrey-oneal - I confirmed that we don't need the body copy (D) in the design reference below for now.

**Inheritance**
- [x] Instead of showing "Depends on", let's keep it simple with "Inherits" if the library uses the `inherits` schema key
- [x] Only show the version if specified in the inherits key (see https://github.com/carbon-design-system/carbon-platform/blob/main/docs/resource-schemas.md#library-inheritance)
- [x] The library icon is available here and needs added it to the platform icons package https://ibm.ent.box.com/file/887827201496

**Source**
- [x] Instead of "Source", use "GitHub" or "IBM GitHub" to dual-purpose and the label and the host

**Package**
- [x] Only show if the package.json does not have `private: true` (see comment below)
- [x] The package icon is available here and needs added to the platform icons package https://ibm.ent.box.com/file/887827201496

**Design ref**
<img width="1025" alt="image" src="https://user-images.githubusercontent.com/1691245/163821900-7e386eeb-ea98-4455-821f-f1b9d3649309.png">

**Internal code packages**

We'll be indexing IBM Internal libraries that don't publish packages to npm. Instead, they often publish to artifactory or some other internal registry.

Looking at CloudPal for example, the package.json doesn't specify anywhere that it publishes to artifactory. If this package.json had `private: true` (as it should), then we know to not try to link out to npm. https://github.ibm.com/ibmcloud/pal/blob/master/patterns/package.json

**Comment by mattrosno** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-624c3fc8b7972e001130fef7/issues/carbon-design-system/carbon-platform/578?planning-poker) with ZenHub @alisonjoseph @andreancardona @francinelucca @jdharvey-ibm

**Comment by kingtraceyj** [comment]
Library redlines: https://ibm.box.com/s/s6btwm637udnek3pbjtfem412kgw83hp

**Comment by mattrosno** [comment]
After discussing with @francinelucca, link to npm if:

1. Library has package.json
2. package.json isn't private: true
3. Use package.json name and version to construct an npm URL like: https://www.npmjs.com/package/@carbon/vue/v/2.44.0

We'll have a separate issue to discuss options for GitHub Packages and Artifactory for inner source code packages.

**Comment by mattrosno** [comment]
@francinelucca the post-v1 issue linked above so we can figure out those unknowns later.

**Comment by mattrosno** [comment]
@francinelucca re-opening to fix:

- [ ] h5 color
- [ ] h4 font size and line claping
- [ ] Inherits library display name
