### ISSUE TITLE
PageTabs: currently selected tab and navigation

### ISSUE THREAD

**Issue by francinelucca** [carbon-design-system/carbon-platform#587]
### Description

PageTabs doesn't take into account what's the currently selected tab: either determine programatically (from url) or accept as a props

PageTabs is not performing navigation on nav click

### Steps to reproduce

Render a pageTabs component with tabs with valid paths, click on one and see no navigation happening

**Comment by mattrosno** [comment]
@francinelucca @alisonjoseph let chat through this one. I think we'll be able to ignore frontmatter data for page tabs and instead have the existence of files determine page tabs.

**Comment by francinelucca** [comment]
@mattrosno I think this is a component-level issue regardless of if we're using frontmatter or not. If you just render a pageTab component in a react component and try to actually link the tabs to routes it doesn't do anything on click

**Comment by mattrosno** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-624c3fc8b7972e001130fef7/issues/carbon-design-system/carbon-platform/587?planning-poker) with ZenHub @jdharvey-ibm @alisonjoseph @francinelucca @andreancardona
