### ISSUE TITLE
Update asset detail redlines with overview tab

### ISSUE THREAD

**Issue by kingtraceyj** [carbon-design-system/carbon-platform#589]
[Asset detail page redlines](https://ibm.box.com/s/x72jtusuu91nab1usgmk4kbya1c2x2cm) need to be updated with the latest designs from #485 discussion.

- [x] Add overview tab
- [x] Get feedback on related assets cards
- [x] Add feedback section (should slack be mini cards or just listed out? we should follow the pattern in library contacts as well)
- [x] Schedule Design review

**Comment by jeanservaas** [comment]
Related:
https://github.com/carbon-design-system/carbon-platform/issues/817
