### ISSUE TITLE
Environment Logging: test env logging prod env errors

### ISSUE THREAD

**Issue by francinelucca** [carbon-design-system/carbon-platform#593]
### Description

the test logger is logging the production errors in addition to the prod logger 

from @jdharvey-ibm:
"I think this line 111 is the reason for the duplicate logging:
The name of the exchange should be environment-specific like the way that the queues are. It'd involve a cascading change in the messaging-client.ts too everywhere either an EventMessage or QueryMessage are used."
![image](https://user-images.githubusercontent.com/40550942/164315932-0c3a1593-283c-409a-811d-0fce4d0e7ba2.png)

### Steps to reproduce

-

**Comment by mattrosno** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-624c3fc8b7972e001130fef7/issues/carbon-design-system/carbon-platform/593?planning-poker) with ZenHub @alisonjoseph @andreancardona @francinelucca @jdharvey-ibm
