### ISSUE TITLE
Render markdown code blocks and inline code

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon-platform#595]
https://gatsby-theme-carbon.vercel.app/components/markdown#code-blocks

Render inline and block code using out of the box Carbon components. 

Additional functionality tracked here https://github.com/carbon-design-system/carbon-platform/issues/363

**Comment by mattrosno** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-624c3fc8b7972e001130fef7/issues/carbon-design-system/carbon-platform/595?planning-poker) with ZenHub @alisonjoseph @andreancardona @francinelucca
