### ISSUE TITLE
ColorTokenTable  MDX component

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon-platform#611]
`<ColorTokenTable />`

https://carbondesignsystem.com/guidelines/color/usage
https://github.com/carbon-design-system/carbon-website/tree/main/src/components/ColorTokenTable

**Comment by mattrosno** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-624c3fc8b7972e001130fef7/issues/carbon-design-system/carbon-platform/611?planning-poker) with ZenHub @alisonjoseph @andreancardona @francinelucca
