### ISSUE TITLE
GlossaryComponent  MDX component

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon-platform#612]
https://carbondesignsystem.com/guidelines/content/action-labels

`<GlossaryComponent />`

**Comment by mattrosno** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-624c3fc8b7972e001130fef7/issues/carbon-design-system/carbon-platform/612?planning-poker) with ZenHub @alisonjoseph @andreancardona @francinelucca
