### ISSUE TITLE
IconLibrary & PictogramLibrary  MDX components

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon-platform#614]
https://carbondesignsystem.com/guidelines/icons/library/
https://carbondesignsystem.com/guidelines/pictograms/library/

https://github.com/carbon-design-system/carbon-website/tree/main/src/components/SVGLibraries

**Comment by mattrosno** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-624c3fc8b7972e001130fef7/issues/carbon-design-system/carbon-platform/614?planning-poker) with ZenHub @alisonjoseph @andreancardona @francinelucca
