### ISSUE TITLE
TypeScaleTable & TypeWeight MDX components

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon-platform#615]
https://carbondesignsystem.com/guidelines/typography/overview#scale
`<TypeScaleTable />`

https://carbondesignsystem.com/guidelines/typography/overview#weights
```
<TypeWeight type="types" />
<TypeWeight />
<TypeWeight type="italic" />
```

**Comment by mattrosno** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-624c3fc8b7972e001130fef7/issues/carbon-design-system/carbon-platform/615?planning-poker) with ZenHub @alisonjoseph @andreancardona @francinelucca
