### ISSUE TITLE
Migrate "Guidelines" section of content from Carbon website

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon-platform#687]
Migrate over guidelines content from current Carbon website and document any issues found.
- Copy/paste mdx
- Move images to public folder
- Update image paths

Document process for future content migration.

Not blocked, but related to #687 and #587, these issues will need to be completed to fully click through the pages in the same way as you can currently. 

![Screen Shot 2022-05-05 at 7 57 08 AM](https://user-images.githubusercontent.com/2753488/166927523-d39977b1-faba-4619-b9f0-e3ebcb8d25b7.png)

**Question**

What should the nav structure be? @jeanservaas @kingtraceyj @aubrey-oneal ?
`/guidelines/2x-grid/overview`
`/assest/guidelines/2x-grid/overview`

- [x]  2x Grid
  - [x] Overview
  - [x] Implementation
- [x]  Accessibility
  - [x] Overview
  - [x] Color
  - [x] Developers
  - [x] Keyboard
- [x]  Content
  - [x] Overview
  - [x] Writing style
  - [x] Action labels
- [x]  Color
  - [x] Overview
  - [x] Usage
  - [x] Code
  - [x] Implemenation 
- [x]  Icons
  - [x] Library
  - [x] Usage
  - [x] Code
  - [x] Contribute
- [x]  Pictograms
  - [x] Library
  - [x] Usage
  - [x] Code
  - [x] Contribute
- [x]  Motion
  - [x] Overview
  - [x] Choreography
  - [x] Code
- [x]  Spacing
  - [x] Overview
  - [x] Code
- [x]  Themes
  - [x] Overview
  - [x] Code
- [x]  Typography
  - [x] Overview
  - [x] Styling strategies
  - [x] Type sets
  - [x] Code

**Comment by alisonjoseph** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-624c3fc8b7972e001130fef7/issues/carbon-design-system/carbon-platform/687?planning-poker) with ZenHub @andreancardona @francinelucca @jdharvey-ibm

**Comment by jdharvey-ibm** [comment]
@alisonjoseph  I debated 3 vs 8. I'm totally fine with 8!
