### ISSUE TITLE
Scrub remote MDX content to remove imports and unsupported MDX components

### ISSUE THREAD

**Issue by mattrosno** [carbon-design-system/carbon-platform#692]
Take the test page a step further by using a file that has unsupported MDX components that need scrubbed out prior to rendering. Same with imports that need removed. See remote MDX library constraints. Consider using React error boundaries to catch MDX rendering errors.

E.g.: https://github.com/carbon-design-system/carbon-website/blob/main/src/pages/components/accordion/usage.mdx

Example of imports that we need to discard: https://github.com/carbon-design-system/carbon-website/blob/main/src/pages/components/dropdown/usage.mdx

**Comment by mattrosno** [comment]
MDX content -> AST (abstract syntax tree) -> filter out nodes that we don't want -> return response.

**Comment by mattrosno** [comment]
Also investigate options to parse MDX.

**Comment by francinelucca** [comment]
Closing, not doing this as per technical design: https://github.com/carbon-design-system/carbon-platform/issues/952
