### ISSUE TITLE
Optimize images used in remote markdown

### ISSUE THREAD

**Issue by mattrosno** [carbon-design-system/carbon-platform#693]
When rendering remote MDX content:

1. Find all images in the content
2. Construct absolute URLs to each image
3. Run each image through the plaiceholder library to generate placeholder base 64-encoded images and get image dimensions

THEN

1. Pass the placeholder image data into the page
1. When the page renders, do a lookup for each image and use the placeholder data where there's a match

OR

1.  Modify at the AST level so the returned markdown uses Next.js `Image` component with the plaiceholder props merged in

So the Next.js `Image` component can optimize the image because there are knowns heights and widths and blur datas.

See: https://github.com/carbon-design-system/carbon-platform/pull/551

And: https://github.com/carbon-design-system/carbon-platform/issues/547

Implement remote images option B from that issue/PR using plaiceholder.

The good stuff: https://github.com/carbon-design-system/carbon-platform/issues/547#issuecomment-1097297125

**Comment by mattrosno** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-624c3fc8b7972e001130fef7/issues/carbon-design-system/carbon-platform/693?planning-poker) with ZenHub @alisonjoseph @andreancardona @francinelucca @jdharvey-ibm

**Comment by mattrosno** [comment]
What safeguards do we need to put in place to prevent malicious behavior? (E.g. verify that all images are actually coming from that library's repo? Etc.)

**Comment by francinelucca** [comment]
Closing, new media mapper issues defined in https://github.com/carbon-design-system/carbon-platform/issues/989 after technical design
