### ISSUE TITLE
Determine how we're going to build and host Storybook

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon-platform#694]
Can we use GitHub pages for this?

What do we use to build Storybook?

Can this be done in PRs as deploy previews as well?

What do we want the URL to be?

**Acceptance criteria**
- [ ] New development issue created with steps to build / deploy storybook outlined.

**Comment by mattrosno** [comment]
Follow-up issue will be doing it.

**Comment by mattrosno** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-624c3fc8b7972e001130fef7/issues/carbon-design-system/carbon-platform/694?planning-poker) with ZenHub @alisonjoseph @andreancardona @francinelucca @jdharvey-ibm

**Comment by jdharvey-ibm** [comment]
Related to #519 in terms of the investigation and requirements

**Comment by francinelucca** [comment]
Created a test project https://github.com/francinelucca/storybook-test and added storybook to it.
> confirmed can build and deploy to github pages through github actions both when merged to main and when pr is opened: https://francinelucca.github.io/storybook-test/?path=/story/example-newstory--default 
...
from #320:  `Can't use GH actions to build Storybook in PRs because of forks and secrets` does this stand? we're currently not using forks and we're able to build our app through GH actions without much issues, not sure what the secrets part is about?

> if we go PR previews for this we'd definitely have to host somewhere else 'cause gh pages won't work for multiple prs open at once? 🤔  so  IBM Cloud Object Storage (dotcom hosts here according to #320), code engine, kubernetes cluster, vercel... 👀

**Comment by alisonjoseph** [comment]
Another option is to mirror what system squad is doing and use Netlify.
https://github.com/carbon-design-system/carbon/pull/11570

![Screen Shot 2022-06-10 at 9 15 34 AM](https://user-images.githubusercontent.com/2753488/173085222-85c15716-85cc-4033-86f2-51acfabab4fa.png)

**Comment by francinelucca** [comment]
> Another option for PR previews is to mirror what system squad is doing and use Netlify. [carbon-design-system/carbon#11570](https://github.com/carbon-design-system/carbon/pull/11570)
> 
yes! I understand that'd work. I know we had previous concerns about third party hosting due to having to set environment secrets but that wouldn't be a concern for storybook (or the web-app anymore for that matter I think because from my understanding from https://github.com/carbon-design-system/carbon-platform/issues/519#issuecomment-1093191028 it'd all be static data so I don't even think we'd need secrets)

**Comment by alisonjoseph** [comment]
Using GitHub pages for our deployed storybook seems like the best idea, now we need to decide on a url. 

What about `platform.carbondesignsystem.com`? any other ideas?

**Comment by francinelucca** [comment]
I know we're using GH pages for our dev docs already (https://carbon-design-system.github.io/carbon-platform/), does that mean we can't use them also for SB?
 I'm thinking we can probably have storybook as a sub-route there and have them co-exist, is that a thing 👀 ? 
or would the idea  be we'd bring all of that info over to SB as well and stop using just-the-docs? 
CC: @jdharvey-ibm

**Comment by jdharvey-ibm** [comment]
@francinelucca I'd recommend chatting with @joshblack on that to see if what he did for system squad could work to host multiple sites out on github pages. If it will, then that's definitely the best option. If not, then hosting on netlify seems like a close second.

**Comment by francinelucca** [comment]
Could also have a subroute for each PR so https://carbon-design-system.github.io/carbon-platform/deploy-previews/322 would contain storybook for PR #322

**Comment by mattrosno** [comment]
Since our community will be using our Storybook for MDX docs, is there a subdomain fitting for that?

- platform
- docs

Kindof makes me think we'd want two storybooks maybe? One is just the MDX documentation for platform at using something like:

- mdx
- mdx-docs
- docs

For subdomain, and then we have a different Storybook that includes those MDX components plus our platform private components and pages and we use that full Storybook for development and testing.

Just something to think through.

**Comment by jdharvey-ibm** [comment]
Neat! Might be worth testing what happens if you try to make a page in the docs called "storybook". I'm guessing it'll be fine because one will end up as storybook.html and the other will be `storybook/`, but it might be good to test just to make sure they won't collide.

**Comment by francinelucca** [comment]
@jdharvey-ibm did that and basically the docs take precedence, so https://francinelucca.github.io/storybook-test/storybook will take you to the docs and to get to the storybook you'll have to use a more specific url like https://francinelucca.github.io/storybook-test/storybook/ (the extra / makes the difference) or a path. I'm guessing it won't matter tho' cause we're using a CNAME for the storybook and will we even have a storybook.md? 

The only thing about this approach is everytime storybook builds I'm storing the build in /docs/storybook so everytime I push to main I have to pull first 'cause it's outdated, there's a couple workarounds for that like:
- We could serve github pages out of a separate 'gh-pages' branch, we'd have to host the docs there tho', or create a workflow that copies them over everytime they change
- We could see if there's a way to ignore that folder for branch syncing purposes?
- We could do the CI through Jenkins
- IDK if there's a way to build/deploy storybook to github pages without having to actually host the files somewhere, I can't find much on this

**Comment by francinelucca** [comment]
Will solve this with github actions:
1 - Create a separate repository on carbon-design-system branch for the purpose of hosting storybook/PR deployment files
2 - set up gh pages inside repo (main/docs or gh-pages/docs)
3 - Build and deploy storybook to docs/storybook
4 - Setup custom domain
5 - Create github action inside carbon-platform repo with the following specifications:
Every time a pr is opened, reopened or pushed to and storybook files are changed:
build storybook , output to docs-build folder
commit output folder to repo from step 1 (docs/pr/{PR_NUMBER}) (might or might not need a github token for this, TBD)
6 - create a github action inside carbon-platform repo with the following specifications:
Every time main is pushed to and storybook files are changed:
build storybook, output to docs-build folder
commit output folder to repo from step 1 (docs/storybook) (might or might not need a github token for this, TBD)

**Comment by francinelucca** [comment]
Optional but recommended: github action to delete PR folder in separate repo when PR is merged in or closed so that deployment gets deleted.

in the future: s3 or netlify shine because you can set up auto-delete policies
