### ISSUE TITLE
Identify MDX AST parsing strategy

### ISSUE THREAD

**Issue by mattrosno** [carbon-design-system/carbon-platform#698]
What's the best way for us to take MDX content, parse it as an AST, so then in a different issue we can filter out nodes that would throw errors (e.g. import statements, unsupported MDX components, etc.)

Are we able to continue using remark for this?

**Comment by mattrosno** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-624c3fc8b7972e001130fef7/issues/carbon-design-system/carbon-platform/698?planning-poker) with ZenHub @alisonjoseph @andreancardona @francinelucca @jdharvey-ibm

**Comment by mattrosno** [comment]
Nice! In https://github.com/carbon-design-system/carbon-platform/issues/692, it will be a good test to try to catch errors when a valid MDX component is trying to use something like `items` that we scrubbed out when sanitizing. The React component will error out, so maybe we can use an Error Boundary to catch that nicely and either discard the MDX component all together or show an error MDX component with the stack trace.

**Comment by mattrosno** [comment]
LGTM. [unist-util-remove](https://www.npmjs.com/package/unist-util-remove) license looks good.

**Comment by alisonjoseph** [comment]
Awesome! LGTM! We should create an issue to implement this approach, along with error handling.

**Comment by mattrosno** [comment]
@alisonjoseph we have that queued up for https://github.com/carbon-design-system/carbon-platform/issues/692, as the next step.
