### ISSUE TITLE
Registered library with specified packageJsonPath not being retrieved correctly

### ISSUE THREAD

**Issue by francinelucca** [carbon-design-system/carbon-platform#699]
### Description

See carbon-components-vue example, version expected to be `2.43.1` : https://github.com/carbon-design-system/carbon-components-vue/blob/main/packages/core/package.json

### Steps to reproduce

-

**Comment by francinelucca** [comment]
ahh you're right! @mattrosno , created a pr to add the packageJsonPath : https://github.com/carbon-design-system/carbon-components-vue/pull/1333

But I also hardcoded it locally and tested it and this won't work. Basically, it's trying to query for `https://api.github.com/repos/carbon-design-system/carbon-components-vue/contents/packages/core/src/../package.json?ref=main` and it's coming up as 404.
We need to do something like `${path.join(libraryParams.path, packageJsonPath)}` to create the request path here:
<img width="630" alt="image" src="https://user-images.githubusercontent.com/40550942/168655389-190e9d06-0e90-4f14-b68d-0195d81ab635.png">

**Comment by mattrosno** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-624c3fc8b7972e001130fef7/issues/carbon-design-system/carbon-platform/699?planning-poker) with ZenHub @alisonjoseph @francinelucca @jdharvey-ibm
