### ISSUE TITLE
Asset detail — how to get kit

### ISSUE THREAD

**Issue by kingtraceyj** [carbon-design-system/carbon-platform#702]
how do we want to lead users to get design kits?

currently, there is a button on the dashboard to lead to design kit page but will want to explore a few versions:
1. do we just want to send people to the kits on the library kit via CTA
2. or do we want specific kit resource card on asset overview? how detailed to we need to get? figma only?
3. 
other open questions:
what should the CTA be if it doesn't link to kits?

**Comment by aubrey-oneal** [comment]
Option: the button could be a download (for any orphan assets) or a link button (library page)

**Comment by kingtraceyj** [comment]
related: #589

**Comment by jeanservaas** [comment]
https://www.figma.com/file/vtmHnw9ACgnksFg7ZvEsZC/Component_asset_page_redline?node-id=0%3A1
