### ISSUE TITLE
Outline all type in SVGs

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/carbon-platform#703]
### Browser

Chrome, Safari, Firefox

### Description

newly added SVGs displaying type should be outlined otherwise they will display in “Times New Roman.”

<img width="356" alt="Screen Shot 2022-05-09 at 10 23 05 AM" src="https://user-images.githubusercontent.com/32881239/167461205-6323820b-942f-4850-9a17-04a4c5a739c3.png">

<img width="682" alt="Screen Shot 2022-05-09 at 10 23 13 AM" src="https://user-images.githubusercontent.com/32881239/167461209-2a354f44-85d7-48c9-90cf-30f53e3d90cd.png">

<img width="341" alt="Screen Shot 2022-05-09 at 10 23 24 AM" src="https://user-images.githubusercontent.com/32881239/167461210-95e645d3-7d9b-4bc7-aa73-c043f45ba08a.png">

<img width="339" alt="Screen Shot 2022-05-09 at 10 23 41 AM" src="https://user-images.githubusercontent.com/32881239/167461211-007c0f53-cf5c-4ec0-8a8c-101b16124700.png">

<img width="351" alt="Screen Shot 2022-05-09 at 12 09 11 PM" src="https://user-images.githubusercontent.com/32881239/167461980-5b3228da-b235-4a75-b5a8-54c810c54ed3.png">

<img width="351" alt="Screen Shot 2022-05-09 at 12 09 24 PM" src="https://user-images.githubusercontent.com/32881239/167461983-67b8b232-ac2e-4822-b9cd-45349e36bf00.png">

<img width="344" alt="Screen Shot 2022-05-09 at 12 09 32 PM" src="https://user-images.githubusercontent.com/32881239/167461985-aa34b0c9-4b5d-4c0d-b017-c1e41d55f55b.png">

<img width="339" alt="Screen Shot 2022-05-09 at 12 09 47 PM" src="https://user-images.githubusercontent.com/32881239/167461988-11fde3eb-185d-41aa-a111-06b0e456818b.png">

<img width="684" alt="Screen Shot 2022-05-09 at 12 09 53 PM" src="https://user-images.githubusercontent.com/32881239/167461989-8d2b51bf-6fc0-42a5-b377-246fb404961b.png">

### Steps to reproduce

Visit https://next.carbondesignsystem.com/assets/components and view any SVG thumbnail image displaying real “type” or “letter forms”

**Comment by mjabbink** [comment]
Looks like @jeanservaas resolved

**Comment by jeanservaas** [comment]
Here are the outlined thumbnails that include type @andreancardona — so any machine that doesn't have Plex installed won't render if different fonts.

ALL thumbnails with type (with the exception of a couple that were already outlined) are saved in this folder, regardless of what library they're in (i.e. React, Svelte, Angular, .com)

[thumbnails_outlined_type.zip](https://github.com/carbon-design-system/carbon-platform/files/8663429/thumbnails_outlined_type.zip)

**Comment by mjabbink** [comment]
@jeanservaas Don’t outline the source files though!

**Comment by mjabbink** [comment]
Another.

<img width="357" alt="Screen Shot 2022-09-14 at 9 35 22 PM" src="https://user-images.githubusercontent.com/32881239/190301436-e4b19c29-551e-41ed-a578-cb424a4dbf90.png">

**Comment by mattrosno** [comment]
@mjabbink thanks! I documented here, which we're using for the next week before we convert found bugs to GitHub issues.

https://github.com/carbon-design-system/carbon-platform/discussions/1268#discussioncomment-3656075
