### ISSUE TITLE
Fix query appending latest to all urls

### ISSUE THREAD

**Issue by andreancardona** [carbon-design-system/carbon-platform#723]
### Description
Currently when switching tabs you will see `latest` appended to all urls strings

Our nextjs "rewrite" strategy is making it so that if you try to navigate to:

http://localhost:3000/assets/carbon-components/latest/accordion/design

it is getting redirected to:

http://localhost:3000/assets/carbon-components/latest/accordion/design/latest

### Steps to reproduce

Nav between the different tabs:

http://localhost:3000/assets/carbon-components/latest/accordion#glance

<img width="1153" alt="Screen Shot 2022-05-13 at 11 24 53 AM" src="https://user-images.githubusercontent.com/32720851/168327729-d5bd84fb-a51f-4adf-9a40-940071c84eab.png">

**Comment by mattrosno** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-624c3fc8b7972e001130fef7/issues/carbon-design-system/carbon-platform/723?planning-poker) with ZenHub @alisonjoseph @andreancardona @francinelucca @jdharvey-ibm

**Comment by mattrosno** [comment]
Could be fixed by blocking issue?
