### ISSUE TITLE
Design - Local system, team, and resource naming principles

### ISSUE THREAD

**Issue by mattrosno** [carbon-design-system/carbon-platform#725]
Design issue for https://github.com/carbon-design-system/carbon-platform/issues/661.

- [ ] Try out naming across website content to ensure content snippets make sense where the language will show up (how Carbon works, design getting started, etc.)

Acceptance criteria:

- Could be an additional proposal
- Or response to proposal A
- Or something to facilitate a discussion, and facilitate the discussion

**Comment by ljcarot** [comment]
https://twitter.com/kjbeavers/status/1528821487251165188?s=12&t=ZwmmiDBhNrAcRpn02PcPBg. Sharing this conversation going in Twitter by a design system team regarding names.

**Comment by mattrosno** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-624ca8ad03d709001dc542bf/issues/carbon-design-system/carbon-platform/725?planning-poker) with ZenHub @aubrey-oneal @kingtraceyj
