### ISSUE TITLE
Need to support "image--fixed" class from Carbon website

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon-platform#742]
If you go here and look at the image under Structure https://carbondesignsystem.com/components/accordion/style#structure you can see images with the image--fixed class. This class is used across the Carbon website to prevent images from scaling up larger than they should. 

Need to either support this class with custom styles inside the Platform, or ensure remote images display correctly. 

<img width="1288" alt="Screen Shot 2022-05-18 at 9 34 15 AM" src="https://user-images.githubusercontent.com/2753488/169067431-cff4d278-8e5b-4a99-840e-3e51a9b0c4de.png">

```
<div className="image--fixed"></div>
```

Styles from Carbon website
```
.image--fixed {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  background: $layer-01;
}

.image--fixed span.gatsby-resp-image-wrapper {
  background: $layer-01;
  display: flex !important;
  align-items: center;
  justify-content: center;
  margin-right: 0 !important;
  width: 70% !important;
  max-width: 100% !important;
}

.image--fixed img.gatsby-resp-image-image {
  max-width: 736px;
  width: 736px !important;
  height: auto !important;
  position: relative !important;
}
```

**Comment by mattrosno** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-624c3fc8b7972e001130fef7/issues/carbon-design-system/carbon-platform/742?planning-poker) with ZenHub @alisonjoseph @francinelucca @jdharvey-ibm

**Comment by alisonjoseph** [comment]
@carbon-design-system/carbon-platform-devs  looking for feedback on best approach 😄 

1. Add `.image--fixed` styles to global stylesheet
2. Create specific component only for ImageFixed
 `<ImageFixed> ![](/image.png) </ImageFixed>`
3. Create flexible component, with fixed prop, allows for future image variants?
 `<ImageType fixed> ![](/image.png) </ImageType>` 
4. `<ImageWrapper type="fixed"> ![](/image.png) </ImageWrapper>`
