### ISSUE TITLE
v1 Research

### ISSUE THREAD

**Issue by kingtraceyj** [carbon-design-system/carbon-platform#745]
User testing v1 interactions a user flows

### **Objectives:**

Does our design match our user's mental model?
Does our design match intended user flows? 
Does a user understand the relationship between objects? 
Can a user find assets to solve their problem?
Can a user use assets to solve their problem?

**Comment by mattrosno** [comment]
@kingtraceyj @aubrey-oneal closing this epic as all issues are closed!
