### ISSUE TITLE
Design - Get Started page

### ISSUE THREAD

**Issue by kingtraceyj** [carbon-design-system/carbon-platform#754]
Development issue for Design getting started page.
Design issue: #545

Mostly Gatsby components except for the data table and in the inline filter. 

We are still updating the video so that will be delivered in a following sprint. 

[Figma redlines](https://www.figma.com/file/KZ6SWR2abIniIJY4RewDeA/Getting-Started-Design---Redline?node-id=10%3A13436)

[Links for cards and data table](https://ibm.box.com/s/v687a4c86xbr69j59j1llpaevw2gwu96)

Images:![CarbonEcosystem.png](https://images.zenhubusercontent.com/579a6affe40e5714b16cabd9/20615f43-e6b2-4948-94b2-23c0ec867dda)![KitDependancy.png](https://images.zenhubusercontent.com/579a6affe40e5714b16cabd9/3ced7295-e366-4342-a061-8ffa4412254c)

**Comment by andreancardona** [comment]
giving it a higher value - just because there is a _lot_ going on with this page

**Comment by alisonjoseph** [comment]
@andreancardona I split out the components into separate issues blocking this one, because I thought the same thing. Once the components are built (minicard, not sure how we missed this one, and the filterable table) this issue is just putting it all together and copying the content in.

**Comment by andreancardona** [comment]
@alisonjoseph ohh gotcha okay changing mine then lol

**Comment by kingtraceyj** [comment]
@andreancardona updated copy to replace video: https://www.figma.com/file/KZ6SWR2abIniIJY4RewDeA/Getting-Started-Design---Redline?node-id=10%3A13436

> The diagram below shows the relationships of design assets and guidance across IBM.
> 
> The IBM Design Language governs IBM’s brand story and visual expression, and Carbon’s role is to translate the design language into resources for building digital experiences. 
> 
> This is manifested through elements such as a color palettes, text type face, and spatial relationships that are meant to be applied to all sorts of things like websites, banners at conferences, and email templates. 
> 
> Carbon also applies the IBM Design Language to product UI through guidance, tooling, and components.
> 
> Product teams can apply common Carbon components as a starting point for their UI. This brings consistency and speed, allowing teams to focus on solving more specific users’ problems. 
> 
> Teams also create product systems that include guidance and components that extend Carbon for their specific use cases. Because designers and developers rely on common Carbon assets in addition to those teams create, Carbon is a robust system of systems.
