### ISSUE TITLE
Sidenav active / open state needs to work with additional nesting

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon-platform#759]
Need to support one more level deep of nesting in the left nav. It currently "works" but doesn't set an active class or keep the nav open. This will be for the Case studies section

**Comment by mattrosno** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-624c3fc8b7972e001130fef7/issues/carbon-design-system/carbon-platform/759?planning-poker) with ZenHub @alisonjoseph @francinelucca @jdharvey-ibm

**Comment by kingtraceyj** [comment]
selected items should be `$heading-compact-01`
![image](https://user-images.githubusercontent.com/20582179/171732779-a11d7093-4c7a-4819-8e76-87a0a07878f9.png)
