### ISSUE TITLE
Content switcher animation not right

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/carbon-platform#765]
page: https://next.carbondesignsystem.com/assets/guidelines/color/usage

Looks like the content switcher animation moves vertically from the center of the button but it could start at the bottom and move up.

current
![next_content_switcher](https://user-images.githubusercontent.com/32881239/169670119-414f7098-a136-407e-b10d-2c1315976645.gif)

expected
![carbon_content_switcher](https://user-images.githubusercontent.com/32881239/169670131-c00515f9-d273-4e32-ba9f-e2d8a8ae98eb.gif)

**Comment by mattrosno** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-624c3fc8b7972e001130fef7/issues/carbon-design-system/carbon-platform/765?planning-poker) with ZenHub @alisonjoseph @andreancardona @francinelucca @jdharvey-ibm
