### ISSUE TITLE
Left nav spacing after section is off

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon-platform#766]
![Screen Shot 2022-05-23 at 10 43 53 AM](https://user-images.githubusercontent.com/2753488/169857186-865100ed-588b-495a-a530-d822b79f1aac.png)

FAQ and Contact aren't part of the Collections section, there needs to be `margin-top: spacing.$spacing-08;` above nav items following a group of items.

Sample nav data

 ```
 {
    title: 'Collections',
    isSection: true,
    items: [
      {
        path: '/assets/data-visualization',
        title: 'Data visualization'
      }
    ]
  },
  {
    path: '/assets/faq',
    title: 'FAQ'
  },
  {
    path: '/assets/contact',
    title: 'Contact'
  }
```

**Comment by mattrosno** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-624c3fc8b7972e001130fef7/issues/carbon-design-system/carbon-platform/766?planning-poker) with ZenHub @alisonjoseph @francinelucca @jdharvey-ibm

**Comment by mattrosno** [comment]
Or adjacent sibling selector?
