### ISSUE TITLE
SVGs don't work when loading remote MDX pages

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon-platform#767]
Test page with svgs

```
 const mdxSource = await getRemoteMdxData(
    {
      host: 'github.com',
      org: 'carbon-design-system',
      repo: 'carbon-website',
      library: 'carbon-website',
      ref: 'main'
    },
    '/src/pages/guidelines/2x-grid/overview.mdx'
  )
```
![Screen Shot 2022-05-23 at 10 52 57 AM](https://user-images.githubusercontent.com/2753488/169858848-3edbde9a-531a-4870-8e97-9678fcce2475.png)

**Comment by mattrosno** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-624c3fc8b7972e001130fef7/issues/carbon-design-system/carbon-platform/767?planning-poker) with ZenHub @alisonjoseph @francinelucca @jdharvey-ibm

**Comment by francinelucca** [comment]
we might need to configure an svg loader: https://frontend-digest.com/how-to-import-svgs-into-nextjs-8ec6100e613f
