### ISSUE TITLE
Update header text to be 16px

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon-platform#770]
![Screen Shot 2022-05-23 at 1 22 54 PM](https://user-images.githubusercontent.com/2753488/169882905-56512398-fd03-4493-ae19-0f110d82e9dc.png)

Update header text and top nav to be 16px.

**Comment by mattrosno** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-624c3fc8b7972e001130fef7/issues/carbon-design-system/carbon-platform/770?planning-poker) with ZenHub @alisonjoseph @francinelucca @jdharvey-ibm
