### ISSUE TITLE
Create new page - Developing

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon-platform#779]
Left nav reference https://github.com/carbon-design-system/carbon-platform/issues/439

Figma file  https://www.figma.com/file/uQXFGSKSJRr0l8CDd3cRGw/v1-prototype?node-id=0%3A1

![Screen Shot 2022-05-25 at 9 27 22 AM](https://user-images.githubusercontent.com/2753488/170286248-a77474e2-00c3-4003-84df-3b44e1bc74d3.png)

**Comment by mattrosno** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-624c3fc8b7972e001130fef7/issues/carbon-design-system/carbon-platform/779?planning-poker) with ZenHub @alisonjoseph @francinelucca @jdharvey-ibm
