### ISSUE TITLE
Decide were v11 and v10 migration pages live

### ISSUE THREAD

**Issue by aubrey-oneal** [carbon-design-system/carbon-platform#782]
The Releases page references migration guides and currently links out to the CDS website. We will need to house this content, which has nested pages and tabs. 

We need to house V11:
https://carbondesignsystem.com/migrating/guide/overview/

Link out to V10 site, not housing this.
https://v10.carbondesignsystem.com/help/migration-guide/overview/

**Comment by mattrosno** [comment]
Closing this, as we brought in migration docs via https://github.com/carbon-design-system/carbon-platform/issues/907 and https://github.com/carbon-design-system/carbon-platform/pull/1225.
