### ISSUE TITLE
Clean up Contacts throughout the site

### ISSUE THREAD

**Issue by aubrey-oneal** [carbon-design-system/carbon-platform#783]
- Decide which pages should have contacts (individuals, slack, emails). No twitter, discord. 
- Airtable audit where everything shows up.
- Decide on a uniform way of presenting contacts (i.e. button, mini cards, or links)
- Delete lingering contacts (many are throughout remote MDX pages)
- Related: maintain people's roles and where they show up

**Comment by mattrosno** [comment]
Related:
https://github.com/carbon-design-system/carbon-platform/issues/1044
https://github.com/carbon-design-system/carbon-platform/issues/295

**Comment by aubrey-oneal** [comment]
Where contacts show up:

- Footer: 
    - IBM Design Medium ( https://medium.com/design-ibm)
    - Twitter (https://twitter.com/ibmdesign)
- [Case studies](https://next.carbondesignsystem.com/about-carbon/case-studies/overview)
    - Email: [carbon@us.ibm.com](mailto:carbon@us.ibm.com)
- [Meetups](https://next.carbondesignsystem.com/about-carbon/meetups): All IBMer only
    - Carbon and IDL playbacks: Subscribe on Your Learning
    - Data viz playbacks: email
    - Design pin-ups: email
- [Contact Page](https://next.carbondesignsystem.com/about-carbon/contact):
    - Github issues
    - Discord (https://discord.gg/SYjvP8epkM)
    - Slack channels: #carbon-design-system #carbon-components, #carbon-react, 
    - Email: [carbon@us.ibm.com](mailto:carbon@us.ibm.com)
    - Twitter: @carbondesign
- [Designing>Figma:](https://next.carbondesignsystem.com/designing/figma) #figma-guild
- Contributing
    - [Overview](https://next.carbondesignsystem.com/contributing/overview) and [Bugs](https://next.carbondesignsystem.com/contributing/bugs-and-requests#need-more-help) pages should redirect to [Contact](https://next.carbondesignsystem.com/about-carbon/contact), but need updated link (current: https://next.carbondesignsystem.com/help/contact-us)
- [Data viz get started](https://next.carbondesignsystem.com/data-visualization/get-started)
    - Links to [Carbon Charts core team in GitHub](https://github.com/carbon-design-system/carbon-charts#core-team) (also shows contributors) 


Aubrey’s suggestions (let’s start the conversation here)
- Decrease sprawl of contacts throughout the site by directing everyone to the Contact page for any case involving email, social media, opening bug/suggestion issues, or general slack/discord channels. For example, replace the Medium and Twitter links in our footer with the Contact page. Same goes for various contacts on the Case studies and Contributing pages.
- Other pages can still have contact links, but we will unify how they look. I.e. We can retain the #figma-guild slack channel on the Figma page and channels on the Library pages (issue #[1044](https://github.com/carbon-design-system/carbon-platform/issues/1044)). I’m uncertain about the Carbon Charts Github link, which goes to a directory of current and past members as well as contributors. 
- Re-work the Contact page a little. I.e. Only link to the Carbon Medium and Twitter (not IBM Design)
- Defer adding contributors on library page until post v1 (issue #[295](https://github.com/carbon-design-system/carbon-platform/issues/295))

**Comment by kingtraceyj** [comment]
@jeannie ok. i'll add the blue to the file and redlines.

**Comment by kingtraceyj** [comment]
@aubrey-oneal 

I think that funneling people to the contacts page is great. I think things get a little tricky with opening bug/suggestion ideas. With so many libraries, we'll have to think about which repos to surface and where people can open general bugs. We should probably stop pointing people to our twitter. No one really maintains it. I do wonder if there is any benefit in directing people to our medium (@mattrosno do we have any data if people click the medium link in our footer?)

Agreed that we should unify how we are presenting contacts—links verses cards. Are you seeing any patterns or is it sort of random how they are presented? I don't think that we need cards for everything and that links, like you mentioned in the Figma page, do work well in some scenarios. 

Agreed on the contact page needing some work. Again, it get a little tricky on which contacts show up here—do we want to include carbon core things as well as other local systems? only carbon core? do we want to keep it even more general?

**Comment by mattrosno** [comment]
@aubrey-oneal we spoke with our open source manager this week, and for now, we aren't listing individual names on the site for contributors/maintainers. That's something that we can explore post-v1, but that's why https://github.com/carbon-design-system/carbon-platform/issues/295 is deferred for later.

Like @kingtraceyj said, some Slack channels are library-specific, like how `#carbon-charts` should be linked to from the Carbon Charts libraries. We determined that this issue is also post-v1, as it's an enhancement to the library and asset overview pages, to list the best contact channels for that library (e.g. Slack, Discord, etc.) https://github.com/carbon-design-system/carbon-platform/issues/1044

**Comment by mattrosno** [comment]
If we have to choose between showing two equivalent links like https://medium.com/carbondesign or https://medium.com/design-ibm (it could be an "and", but if we have to choose...), I'd choose the option that's most relevant to our users, which in this example would be Carbon's Medium, Carbon's Twitter, etc. I'd choose the higher-signal option.

**Comment by aubrey-oneal** [comment]
Design decisions are finished. After the code freeze there will be dev work (already started by my me) to:
- Redo Contacts page based on Figma design. This is done on my local branch save for icons for discord, slack, and twitter.https://www.figma.com/file/ZOILKMMO2LCrSeUYIBHi7C/Contacts?node-id=6%3A2474
- Delete medium/twitter in footer and insert contacts page link
- Add medium link to 'Articles' page

**Comment by aubrey-oneal** [comment]
- Link case study contact to contact page: https://github.com/carbon-design-system/carbon-platform/discussions/1270#discussioncomment-3684307
