### ISSUE TITLE
Determine how we want to use Percy

### ISSUE THREAD

**Issue by mattrosno** [carbon-design-system/carbon-platform#785]
Per these discussions:

https://ibm-studios.slack.com/archives/C02H44VRGQP/p1653490369963069

https://ibm-studios.slack.com/archives/C03468NQVLJ/p1653571983829429

Let't determine how we want to use Percy, and expected (rough ballpark) monthly snapshot requirements.

**Comment by alisonjoseph** [comment]
Start with storybook, test each story in PR.

Estimated 10,000 snapshots per month to start
(46 stories x 50 PRs/month x 3 (account for commits to each PR after opening)
