### ISSUE TITLE
Authentication and authorization

### ISSUE THREAD

**Issue by jdharvey-ibm** [carbon-design-system/carbon-platform#80]
As a user of the carbon platform, I want to be able to log in with my IBMid so that I can see non-public, protected content that is relevant to me.

- [x] #118
- [x] #119
- [x] #120
- [x] #121
- [x] #122
- [x] #123
- [x] #125
- [x] #212

**Comment by francinelucca** [comment]
@jdharvey-ibm was this supposed to close with the messaging api PR?

**Comment by mattrosno** [comment]
@francinelucca @jdharvey-ibm I moved this epic to the private beta milestone because we'll need authentication (even if temporarily enforced through Next.js middleware). Can you move tasks not needed for the private beta to a separate issue?

**Comment by jdharvey-ibm** [comment]
Now tracking #124 in epic #244
