### ISSUE TITLE
[Mobile] Spacing needs to be 32px after image/caption Do Not’s throughout.

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/carbon-platform#806]
**Description**

There are missing 32px spacers after captions under “Do Not’s” though out the guidance pages.

This occurs in many of the Guidelines pages

<img width="356" alt="Screen Shot 2022-06-01 at 4 26 08 PM" src="https://user-images.githubusercontent.com/32881239/171504844-592ccb97-5f04-4b1d-834a-1a1931cb9a8d.png">

Some of the occurrences:
https://next.carbondesignsystem.com/assets/guidelines/color/overview
https://next.carbondesignsystem.com/assets/guidelines/2x-grid/overview
https://next.carbondesignsystem.com/assets/guidelines/2x-grid/implementation
https://next.carbondesignsystem.com/assets/guidelines/pictograms/usage
https://next.carbondesignsystem.com/assets/guidelines/motion/choreography

In this case some of the “Do not” cards without captions touch each other
https://next.carbondesignsystem.com/assets/guidelines/typography/overview

**Comment by mattrosno** [comment]
Could be fixed by #811. If not, re-estimate.
