### ISSUE TITLE
[Mobile] The nav should collapse after selection (like current Carbon site)

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/carbon-platform#807]
**Description**

In mobile, once you make selection the left nav menu stays open until one closes it by touching the close icon

**Steps to reproduce**

Any mobile device

**Comment by francinelucca** [comment]
is this a duplicate of #504? if so should be fixed on next deployment

**Comment by mjabbink** [comment]
@francinelucca yes, this is a duplicate. Will close this one.
