### ISSUE TITLE
[Mobile] Code snippet under grid implementation samples should bleed to right edge of screen

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/carbon-platform#810]
**Description**

The snippet is stopping where the grid example above stops but it should continue to the far right edge as other snippets do not under the live grid examples
https://next.carbondesignsystem.com/assets/guidelines/2x-grid/implementation

visual

<img width="354" alt="Screen Shot 2022-06-01 at 5 00 11 PM" src="https://user-images.githubusercontent.com/32881239/171509095-c627f367-36fe-4488-987e-97712a6c71a0.png">

But should go to edge like below
<img width="356" alt="Screen Shot 2022-06-01 at 5 00 28 PM" src="https://user-images.githubusercontent.com/32881239/171509126-0efd2d04-1b23-4d14-a768-6b0f03bba7da.png">

**Comment by mjabbink** [comment]
Seems to break at the tablet break point and through mobile



large is good
<img width="872" alt="Screen Shot 2022-06-01 at 5 02 01 PM" src="https://user-images.githubusercontent.com/32881239/171509449-de1ba0ec-fcf7-41b7-8fb2-ecdf400f1b24.png">

<img width="1120" alt="Screen Shot 2022-06-01 at 5 02 51 PM" src="https://user-images.githubusercontent.com/32881239/171509452-92bd49cb-219d-4660-9107-3dc59f12b9cb.png">

**Comment by alisonjoseph** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-624c3fc8b7972e001130fef7/issues/carbon-design-system/carbon-platform/810?planning-poker) with ZenHub @andreancardona @francinelucca @jdharvey-ibm
