### ISSUE TITLE
In some places there is too much space between caption and image

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/carbon-platform#811]
The space between caption and image should be 16px I believe and in some cases, I’m finding it at 32px in some places like shown below. It should be 16px.

example
<img width="356" alt="Screen Shot 2022-06-01 at 4 30 16 PM" src="https://user-images.githubusercontent.com/32881239/171510641-f1bcdd4d-dafa-40b1-af47-1211b29ef66b.png">

**Comment by mjabbink** [comment]
An additional spacing issue here

https://next.carbondesignsystem.com/assets/guidelines/accessibility/overview#low-vision
<img width="1041" alt="Screen Shot 2022-06-01 at 5 15 54 PM" src="https://user-images.githubusercontent.com/32881239/171510935-7d28c181-5ab4-4beb-a116-b7dd2c3db14a.png">

**Comment by mjabbink** [comment]
https://next.carbondesignsystem.com/assets/guidelines/accessibility/overview#resources
<img width="357" alt="Screen Shot 2022-06-01 at 5 22 33 PM" src="https://user-images.githubusercontent.com/32881239/171511744-9a69b273-3fc1-4f52-adff-9f69e2ea5bdc.png">

**Comment by mattrosno** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-624c3fc8b7972e001130fef7/issues/carbon-design-system/carbon-platform/811?planning-poker) with ZenHub @alisonjoseph @andreancardona @francinelucca @jdharvey-ibm
