### ISSUE TITLE
MDX error handling UI/UX

### ISSUE THREAD

**Issue by mattrosno** [carbon-design-system/carbon-platform#818]
When there are remote MDX errors, how do we handle those in the page? For example:

1. Entire page breaks and nothing can be rendered
1. Page attempts to use an unsupported MDX component
1. Page uses an MDX component that's supported but has errors and can't be rendered

# Joe's Notes

## Possible Errors
- Component used that is not recognized by the platform (regardless of whether or not it has a corresponding import)
	- can modify
	- can remove
- An import (or export) statement being used (we don't allow any)
	- possibly can modify (needs testing to be sure)
	- can remove
- 	A usage of an imported value someplace in the mdx
	- cannot modify (since we don't know the intended behavior)
	- can remove
- Inline styles that are strings instead of objects
	- cannot modify (at best, we will only cover some of the total possibilities)
	- can remove
- Inclusion of HTML comments
	- possibly can modify (needs testing to be sure)
	- can remove
- General Markdown parsing errors
	- this is a non-recoverable error
	- cannot modify
	- cannot remove
- General JSX parsing errors
	- this is a non-recoverable error
	- cannot modify
	- cannot remove

## Options
- Modify content - replace part of the AST with something else
- Remove content - remove the affected tree nodes entirely
- Replace full page with error text (as opposed to the actual MDX content)

## Consolidated error categories for design consideration
1. Errors propagated from the underlying MDX library (i.e. parsing errors)
	1. markdown parsing errors
	2. jsx parsing errors
	3. usage of an unknown token somewhere in the markdown
2. Unsupported things
	1. import statements
	2. unsupported/unknown components
	3. comments
	4. unsupported frontmatter
3. "This" versus "that" preferences
	1. using string styles on components instead of object styles
	2. using a "wrong" type of image component
	3. using tabs frontmatter instead of schema file docs definitions

**Comment by mattrosno** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Product-Management-624ca9397d28730018df40c2/issues/carbon-design-system/carbon-platform/818?planning-poker) with ZenHub @aubrey-oneal @kingtraceyj

**Comment by kingtraceyj** [comment]
@jdharvey-ibm and @alisonjoseph do you mind sharing some screenshots of a few examples? maybe one of an inline error and then one of a full page error?

**Comment by jdharvey-ibm** [comment]
@francinelucca may be able to help out with the error texts. At the moment, I don't think we have any UI demonstrating the errors, but we can definitely get you some of the error text we'd expect to get emitted for each type of error.

**Comment by kingtraceyj** [comment]
sample error text would be great!

**Comment by francinelucca** [comment]
will gather info and update here by EOD
