### ISSUE TITLE
platform-microservice: log bind calls

### ISSUE THREAD

**Issue by jdharvey-ibm** [carbon-design-system/carbon-platform#830]
Currently, when bind is called when a service comes up, it is not logged, so there's no real indication of the messaging queues and exchanges that are being created.

This is a request to add a log call to that method so that it can be seen in the ffdc data.

The logging service will have to do this by hand by calling the log-dna-service.
All other services can just call logging normally.

**Comment by mattrosno** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-624c3fc8b7972e001130fef7/issues/carbon-design-system/carbon-platform/830?planning-poker) with ZenHub @alisonjoseph @andreancardona @francinelucca @jdharvey-ibm
