### ISSUE TITLE
Update index library names

### ISSUE THREAD

**Issue by mattrosno** [carbon-design-system/carbon-platform#832]
**Description**

We haven't aligned on naming [proposal A](https://github.com/carbon-design-system/carbon-platform/issues/661) yet and the library names aren't in conflict with proposal A, but they should be updated to be more consistent.

| Before | After |
| --- | --- |
| Carbon React | Carbon React |
| Carbon Components | Carbon Vanilla |
| Carbon Components Angular | Carbon Angular |
| Carbon Components Svelte | Carbon Svelte |
| Carbon Components Vue | Carbon Vue |
| Carbon Web Components | Carbon Web Components |

Justification:

1. These libraries don't only include components. For example Carbon React also includes React hooks (functions), Carbon Angular also includes some coded patterns, etc.
1. It prevents confusion between vanilla and React libraries.
1. The naming is aligned with how we now name code packages in the Carbon scope, like `@carbon/react`.

There's a related design issue to specify library descriptions: https://github.com/carbon-design-system/carbon-platform/issues/559

**Steps to reproduce**

How do we reproduce the error? Please be as specific as you can.

1. View the libraries list https://next.carbondesignsystem.com/assets/libraries

**Comment by mattrosno** [comment]
@kingtraceyj @aubrey-oneal can you review the table above and justification?

**Comment by mattrosno** [comment]
@carbon-design-system/carbon-platform-designers can you review the table and justification above?

**Comment by mattrosno** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-624c3fc8b7972e001130fef7/issues/carbon-design-system/carbon-platform/832?planning-poker) with ZenHub @alisonjoseph @andreancardona @francinelucca @jdharvey-ibm

**Comment by andreancardona** [comment]
@aubrey-oneal 

| Before | After |
| --- | --- |
| ~Carbon React~ | ~Carbon React~ |
| Carbon Components | Carbon Vanilla - Carbon no longer supports Vanilla @aubrey-oneal  thoughts on this? |
| Carbon Components Angular | Carbon Angular PR: https://github.com/IBM/carbon-components-angular/pull/2202 |
| Carbon Components Svelte | Carbon Svelte |
| Carbon Components Vue | Carbon Vue |
| Carbon Web Components | Carbon Web Components |

**Comment by mattrosno** [comment]
@andreancardona Carbon Vanilla isn't deprecated or sunset; it's just community maintained. It still needs indexed (for now at least.)

**Comment by andreancardona** [comment]
> @andreancardona Carbon Vanilla isn't deprecated or sunset; it's just community maintained. It still needs indexed (for now at least.)

Here is the original PR - I cannot seem to find the `carbon.yml` to save my life 👀 do you see it? 

https://github.com/carbon-design-system/carbon/pull/11265/files

**Comment by francinelucca** [comment]
@andreancardona https://github.com/carbon-design-system/carbon/blob/v10/packages/components/carbon.yml you have to do it in v10 branch
