### ISSUE TITLE
Web app crashes when its connection to the message broker drops

### ISSUE THREAD

**Issue by jharvey10** [carbon-design-system/carbon-platform#848]
The fix is to tolerate disconnects in the messaging client and re-connect instead of bubbling an exception up to the caller.

**Comment by mattrosno** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-624c3fc8b7972e001130fef7/issues/carbon-design-system/carbon-platform/848?planning-poker) with ZenHub @alisonjoseph @andreancardona @francinelucca @jdharvey-ibm

**Comment by jdharvey-ibm** [comment]
Fixed in bfe11fa053859ce41c411e68071df433901f4499
