### ISSUE TITLE
web-app container cannot detect when one of its two starting processes have crashed

### ISSUE THREAD

**Issue by jdharvey-ibm** [carbon-design-system/carbon-platform#849]
**Description**

The web app service starts two processes right now when it comes up: An express proxy and a nextjs application.

Currently, `concurrently` is used to run both of those node processes, but the problem is that if one of the two of those processes exits or crashes, there's no logic in place to detect that and respond to it.

This issue is to remove the use of concurrently and to instead create a small node script which spins up both of those two processes. The node script can monitor those two processes for exiting, and if either is discovered to have exited, the script should forcefully exit the other of the two so that the entire container stops running.

**Comment by mattrosno** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-624c3fc8b7972e001130fef7/issues/carbon-design-system/carbon-platform/849?planning-poker) with ZenHub @alisonjoseph @andreancardona @francinelucca @jdharvey-ibm

**Comment by jdharvey-ibm** [comment]
concurrently has a flag to detect crashing. this should be as simple as adding that flag to the run command in package.json and the Dockerfile.
