### ISSUE TITLE
Assets in schema explorations

### ISSUE THREAD

**Issue by francinelucca** [carbon-design-system/carbon-platform#852]
Moving discussion from #805 over to here:

> Should we have separate .yml files for a library and an asset? 
> Should we move `assets` to be a key inside of `library`? 

----

"Us using carbon.yml for an entire library seems like a short term thing. That file's going to get too big to manage. I think we'll eventually want a Carbon config file for the library and per asset in subdirectories." - Matt

"It'd be nice for us to keep support so a library can have one or many config files. I think it's reasonable to only support asset docs defaults if the Carbon config files are used on a per-asset basis?" - Matt

"Something to consider (outside the scope of this issue): are we moving away from an assets L0 (at least back-end-wise)? If so, it probably doesn't make sense for the schema definition to have an assets L0; it'd be better suited inside of the library object itself. That would enable us to do a top-level asset key for the one-carbon.yml-per-asset model, and libraries.assets as the multiple-assets-per-carbon.yml model, and then enforce that you only specify one or the other of those two." - Joe

"I think if we-re going the one-asset-per-carbon.yml way it'd probably make morse sense to have a separate carbon-asset.yml file like we used to with a separate asset schema instead of having a top-level asset ket on top of library.assets within the same file schema" - Francine

"a constraint to keep in mind (just a reminder) - it's common for some libraries to have a components folder where each component has its own JS file like a-component.js and another-component.js to both live in the /components directory.
We don't want to require libraries to move files around so it's "one asset per directory". That's why our current carbon.yml structure works well to handle this scenario of multiple assets in same directory." - Matt

**Comment by mattrosno** [comment]
@francinelucca I think we can close this now that we know how we want to use asset `$ref`s so an asset can be defined directly in a library, instead of having directory structure assumptions.
