### ISSUE TITLE
Convert heading elements into components

### ISSUE THREAD

**Issue by francinelucca** [carbon-design-system/carbon-platform#859]
**Summary**
Example:
Use `<H2 />` component instead of `h2` element in the web-app.
This will come pre-styled, support anchor-links, and will overall cleanup the code a bit. there's ~30 instances of this

**Job stories**

What value will this deliver?

1. cleanup unnecessary CSS
2. support anchor links
3. standardize

**Acceptance criteria**

What requirements must be met to complete this request?

1. There are no heading elements on the page, we're using components instead
2. Most custom styling on these headings is removed since it'll come from the component. (remove class on element and also on scss)
3. No visual regressions on the app, should look the same

**Comment by mattrosno** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-624c3fc8b7972e001130fef7/issues/carbon-design-system/carbon-platform/859?planning-poker) with ZenHub @alisonjoseph @jdharvey-ibm
