### ISSUE TITLE
Invalid href passed to next/router: //tab-one, repeated forward-slashes (//) or backslashes \ are not valid in the href

### ISSUE THREAD

**Issue by jdharvey-ibm** [carbon-design-system/carbon-platform#871]
https://github.com/carbon-design-system/carbon-platform/runs/6841059709?check_suite_focus=true#step:6:270

I'm not sure which page is throwing this error/warning. I did a quick search in the repo for `//tab-one`, and 'tab-one', but didn't find anything.

The solution here is likely either to add a protocol to the front of the route (i.e. `https://example.com` instead of `//example.com`) or to check if `/` is being prepended to a path which already starts with `/`.

**Comment by mattrosno** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-624c3fc8b7972e001130fef7/issues/carbon-design-system/carbon-platform/871?planning-poker) with ZenHub @alisonjoseph @jdharvey-ibm
