### ISSUE TITLE
Update copy [How Carbon works]

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/carbon-platform#879]
The current page is very choppy reading. It’s not far from bullets.

I consolidated text into paragraphs where there was no reason for new paragraphs. A new paragraph should start a new idea or point.

I recommend the following:

——————

**The Carbon ecosystem**

Carbon is s system of systems. At the epicenter lies Carbon’s universal system, with assets that can be used as a base for the widest variety of situations. Moreover, these components, patterns, elements, and code are open source and can easily be extended or adapted. 

Additionally, teams throughout IBM have been able to abstract components and create their own “specific” product and digital systems. Examples include Carbon for IBM.com and Carbon for IBM Products. If you’re ready to get started with Carbon, check out our guidance for [designers](https://next.carbondesignsystem.com/designing/get-started) and [developers](https://next.carbondesignsystem.com/developing). 

Today, we are platforming this system of systems, giving makers global visibility and local lenses. Our goal is to help makers find assets that comply with platform requirements, are convenient to implement and are consistent with design patterns across the company. For the first time, makers can find and re-use assets across all IBM teams, regardless of who maintains them and discover assets compliant with their product or team through local lenses.

Head to the [component catalog](https://next.carbondesignsystem.com/assets/components) to see the many assets shared between product and digital teams. Progress on the new platform can be found in our [roadmap](https://next.carbondesignsystem.com/about-carbon/platform-roadmap).

———————

**Creating consistency**

The Carbon Design System now follows a [schema](https://github.com/carbon-design-system/carbon-platform/blob/main/docs/resource-schemas.md) to document each resource in a standardized way. This structured information is indexed by Carbon’s new underlying platform to use in this website and other services. This allows us to consistently classify reusable components and patterns — regardless of who maintains them — helping designers and developers find and access components, patterns, functions, and templates across all IBM teams. 

More importantly, we’re giving IBM makers confidence in what they see in Carbon: to understand who maintains what, see how often each asset is used and where, and ultimately make informed decisions with Carbon to advance design excellence within their teams.

**Comment by mjabbink** [comment]
I also tweaked the copy a bit.

**Comment by mjabbink** [comment]
e.g. current with many line breaks. 

——————

**The Carbon ecosystem**

Carbon is s system of systems. At the epicenter lies Carbon’s universal system, with assets that can be used as a base for the widest variety of situations. These components, patterns, elements, and code are also open source and can easily be extended or adapted.

Additionally, teams throughout IBM have been able to abstract components out and create their own product and digital systems. Examples include Carbon for IBM.com and Carbon for IBM Products.

If you’re ready to get started with Carbon, check out our guidance for designers and developers.

Today, we are platforming this system of systems, giving makers both global visibility and local lenses. Our goal is to help makers find assets that comply with platform requirements, are convenient to implement, and are consistent with design patterns across the company.

For the first time, makers will be able to find and re-use assets across all IBM teams, regardless of who maintains them.

Additionally, makers can quickly find assets that are compliant with their own product or team through local lenses.

Head over to the component catalog to see the many assets shared between product and digital teams. Progress on the new platform can be found in our roadmap.

**Comment by mjabbink** [comment]
FYI @jeanservaas

**Comment by mattrosno** [comment]
Hi @mjabbink - we're actively working on this to describe Carbon's system of systems. We have this issue in the v1.0 release to make sure it gets done in the first release.

**Comment by mjabbink** [comment]
current

`Carbon maintainers`

Carbon core and local systems have maintainers that administer governance over content and resource visibility.

Each resource cites a maintaining team if an IBM team primarily maintains the resource. If an individual or informal group is responsible for a resource, it will be listed as community maintained.

Maintainers can control content and resource visibility through a metadata file that follows a clear schema. The [schema](https://next.carbondesignsystem.com/about-carbon/contribute/documentation) helps us document each resource in a standardized way and enables everything to be indexed by Carbon’s new underlying platform.

The Carbon platform and website is maintained by the Carbon team. Progress on the new platform can be found in our [roadmap](https://next.carbondesignsystem.com/about-carbon/platform-roadmap).

**Comment by mjabbink** [comment]
`Carbon maintainers`

Carbon core and local systems have maintainers that administer governance over content and resource visibility. Each resource cites a maintaining team if an IBM team maintains the resource. If an individual or informal group is responsible for a resource, it will be listed as community maintained. 

Maintainers can control content and resource visibility through a metadata file that follows a clear schema. The [schema](https://next.carbondesignsystem.com/about-carbon/contribute/documentation) helps us document each resource in a standardized way and enables everything to be indexed by Carbon’s new underlying platform.

The Carbon platform and website is maintained by the Carbon team. Progress on the new platform can be found in our [roadmap](https://next.carbondesignsystem.com/about-carbon/platform-roadmap).

**Comment by mjabbink** [comment]
@aubrey-oneal and @jeanservaas See my change just above.
