### ISSUE TITLE
Update copy [Releases] page

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/carbon-platform#880]
https://next.carbondesignsystem.com/about-carbon/releases. I nudged the copy and consolidated it into one paragraph.

(expected)

**Releases**
Each Carbon Design System release includes independently versioned package releases following the industry-standard [semantic versioning](https://semver.org/) specification. The team also ships minor package releases every other week and patch releases between minor versions to address bugs when necessary. Read more in Carbon’s [release radar](https://github.com/carbon-design-system/carbon/wiki/Release-radar).
.
.
.
.
.
(current)

**Releases**
Each Carbon Design System release includes package releases that are independently versioned following the industry-standard [semantic versioning](https://semver.org/) specification.

The Carbon team also ships package minor releases every other week and when necessary, patch releases between minor versions to address bugs. Read more in Carbon's [release radar](https://github.com/carbon-design-system/carbon/wiki/Release-radar).

**Comment by mjabbink** [comment]
@aubrey-oneal I forgot to mention to update an apostrophe in “Carbon’s release radar.”

**Comment by mattrosno** [comment]
Hi @mjabbink, just an FYI, we have this issue still open, planned for v1.

https://github.com/carbon-design-system/carbon-platform/issues/721

Like the Gatsby solution, this issue is to automated all straight quotes into "curly" quotes. So even if the source code is `'` and `"`, the correct characters get used in the website.

**Comment by mjabbink** [comment]
OK cool but still a good practice to type those correctly in text from the start.
