### ISSUE TITLE
Storybook embed design spec

### ISSUE THREAD

**Issue by kingtraceyj** [carbon-design-system/carbon-platform#882]
**What different size do we need to offer for our components**

- small, medium, large
- 8 column, 12 column

dev exploration issue: #763

demo:
https://user-images.githubusercontent.com/2753488/173480154-033a30bb-f10f-41f9-8c68-aa5b947fa0eb.mov

**Comment by mattrosno** [comment]
@kingtraceyj let's also consider this (the version disclaimer and linking out to the full demo.)

https://github.com/carbon-design-system/carbon-platform/issues/763#issuecomment-1155456233

**Comment by alisonjoseph** [comment]
Design explorations https://www.figma.com/file/Cs94zXOUUEizXNdDz263OA/Component-demo?node-id=0%3A1

**Comment by mattrosno** [comment]
Closing because the design spec is complete: https://www.figma.com/file/Cs94zXOUUEizXNdDz263OA/Component-demo?node-id=114%3A169975
