### ISSUE TITLE
Review landing page for v1

### ISSUE THREAD

**Issue by kingtraceyj** [carbon-design-system/carbon-platform#883]
Current design: https://www.figma.com/file/uQXFGSKSJRr0l8CDd3cRGw/v1-prototype?node-id=0%3A1

- [x] Update imagery for the v1 release (light theme hero image and image design for breakpoints)
- [x] Add .com web components to featured libraries - will need image
- [x] Include more basic information about Carbon and clearer information about the ecosystem
- [x] Add crosslinks on the homepage to help users get started from there (Potentially—How Carbon Works, Get started designing, Developing)
- [ ] Populate the dev issue #905 with changes then remove the blocked label

**Comment by mattrosno** [comment]
@kingtraceyj @jeanservaas we should consider changing "Asset catalog" to "Asset catalogs" if we end up using the side nav "Assets" grouping.

Also, renaming "Asset collections" to just "Collections" because collections can include pages too (e.g. the data viz get started, chart anatomy, color palettes.)

<img width="1392" alt="image" src="https://user-images.githubusercontent.com/1691245/174834592-cc8537b2-1bcc-416a-af08-eda626519184.png">

**Comment by mjabbink** [comment]
Not sure if this is the issue to add this but mobile images should be created for lead space banner, Collections, and Featured Libraries.


I also think having Featured libraries above Collections is a stronger hierarchy no? What is your logic to have Collections first?

**Comment by mattrosno** [comment]
@mjabbink thanks for the comment. We can be sure to review content order, and mobile images when doing this issue.

**Comment by kingtraceyj** [comment]
Notes from user testing:

- Review upfront copy and headings. Include more basic information about Carbon and clearer information about the ecosystem, (maybe add ecosystem image?—could also just link here)
- Add crosslinks on the homepage to help users get started from there (Potentially—How Carbon Works, Get started designing, Developing)

**Comment by aubrey-oneal** [comment]
Updates to the landing page will be mocked up in Figma this sprint: https://www.figma.com/file/uQXFGSKSJRr0l8CDd3cRGw/v1-prototype?node-id=0%3A1

I can implement these changes next sprint.

**Comment by jeanservaas** [comment]
Here is the updated landing spec and the artwork assets. @aubrey-oneal some of the copy is not quite final.

https://www.figma.com/file/M1UolPMDngdACDMMLU7WpX/v1_landing_pg_redlines?node-id=0%3A1


## Artwork

[V1_landing_pg_artwork.zip](https://github.com/carbon-design-system/carbon-platform/files/9352948/V1_landing_pg_artwork.zip)

**Comment by alisonjoseph** [comment]
@jeanservaas @kingtraceyj question around the feature cards on the homepage, looks like the top one (How Carbon works) is on a narrow grid (hangs left) and the bottom two (featured libraries) are wide grid (flush with the text). Just wanted to double check that the top one should hang left/narrow before updating the component to allow for that.

**Comment by jeanservaas** [comment]
Here are the leadspace assets... like I said, mobile might be tricky and the artwork is a little different so we'll want to have a look at it. I'm going to add the mobile one here in a second.

<img width="2626" alt="Assets_hero_revised" src="https://user-images.githubusercontent.com/43144260/185149442-28be0cfe-16cd-4ccf-9911-6d783254bcd0.png">

**Comment by alisonjoseph** [comment]
Thanks @jeanservaas I'll add the new images in 😄 

I was actually questioning this, does this image hang left?
![Screen Shot 2022-08-17 at 11 24 14 AM](https://user-images.githubusercontent.com/2753488/185192246-7f844323-ddf0-47b6-83e2-8cb074faaf43.png)
