### ISSUE TITLE
Deploy Storybook

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon-platform#885]
Everytime something is pushed to `main`, Storybook is deployed to [platform.carbondesignsystem.com](http://platform.carbondesignsystem.com) 

Will solve this with github actions: From #694 

1. Create a separate repository on carbon-design-system branch for the purpose of hosting storybook/PR deployment files
2. set up `gh pages` inside repo (`main/docs` or `gh-pages/docs`)
3. Build and deploy storybook to `docs/storybook`
4. Setup custom domain (platform.carbondesignsystem.com) 
9. Create a github action inside carbon-platform repo with the following specifications:
     - Every time main is pushed to and storybook files are changed:
     - build storybook, output to docs-build folder
     - commit output folder to repo from step 1 (docs/storybook) (might or might not need a github token for this, TBD)

**Comment by mattrosno** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-624c3fc8b7972e001130fef7/issues/carbon-design-system/carbon-platform/885?planning-poker) with ZenHub @alisonjoseph @jdharvey-ibm

**Comment by francinelucca** [comment]
Confirmed will need a token, working example: https://github.com/francinelucca/storybook-test/blob/main/.github/workflows/storybook.yml
