### ISSUE TITLE
Remove thumbnails from functions catalog & update mobile view for all catalogs

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon-platform#886]
Design issue #449 

Redlines for functions catalog 
https://ibm.box.com/s/w6xjolukzbiv9jhqa8di207d7rfy96j4

Note: these changes need made at the functions catalog level, not at the catalog item level if type function, because when there are catalogs with mixed types (e.g. collections), we'll still display placeholder thumbnails for functions so there is visual consistency.
- [x] Remove grid/list switcher so it's only list view
- [x] Remove thumbnail from list view
- [x] When removing thumbnail, set height of the rows
- [x] Still use aspect ratio at `sm` breakpoint

Update for ALL catalogs
- [x] For both tiles with a thumbnail and without a thumbnail, small break points are the same. The status moves to upper right and tags move to lower left.
- [x] For a tile with a thumbnail, at medium breakpoints, the status moves to upper right and tags move to lower left.
- [x] For a tile without a thumbnail, at medium breakpoints, the status and tags stay in place. There is room for the tags to stay in the upper right.

### Here are the specs for a catalog with a thumbnail:

**medium:**
![image](https://user-images.githubusercontent.com/20582179/173854248-78fca766-783d-4f24-903f-d41acafb2ade.png)

**small breakpoint:**
content section same as medium but remove thumbnail
![image](https://user-images.githubusercontent.com/20582179/173854424-99546c3b-afb4-45a3-ba9f-f190fd017bb3.png) 

### Catalog tile without a thumbnail:

**medium break point:**
![image](https://user-images.githubusercontent.com/20582179/173854065-0d151922-ac7d-4f36-bd07-6ea5f3442be8.png)

**small break point:**
![image](https://user-images.githubusercontent.com/20582179/173854140-f9a29513-d79c-4c42-8c7b-547dbccb4838.png)

**Comment by alisonjoseph** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-624c3fc8b7972e001130fef7/issues/carbon-design-system/carbon-platform/886?planning-poker) with ZenHub @andreancardona @francinelucca @jdharvey-ibm

**Comment by francinelucca** [comment]
Added refactor dependency , it'll be much +++ easier to get this in if we have the refactor in first
