### ISSUE TITLE
Carbon for dotcom and Carbon for ibm products sponsor team icons need to pull from @carbon/icons

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon-platform#895]
Carbon for dotcom and Carbon for IBM Product Icons should be sourced directly from` @carbon/icons-react` package

- [ ] ~Update Carbon icons package first?~
- [x] Remove `packages/icons/src/main/svg/24-carbon-for-ibm-dotcom.svg`
- [x] Remove `packages/icons/src/main/svg/24-carbon-for-ibm-product.svg`
- [x] Replace with icons from `@carbon/icons-react` inside teams https://github.com/carbon-design-system/carbon-platform/blob/main/services/web-app/data/teams.js
  - `<CarbonForIbmDotcom /> <CarbonForIbmProduct />`

![Screen Shot 2022-06-16 at 2 39 46 PM](https://user-images.githubusercontent.com/2753488/174151402-b14308ba-826b-42b8-9f10-310cc98e24c2.png)

**Comment by mattrosno** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-624c3fc8b7972e001130fef7/issues/carbon-design-system/carbon-platform/895?planning-poker) with ZenHub @alisonjoseph @andreancardona @jdharvey-ibm

**Comment by jdharvey-ibm** [comment]
Since we're removing icons from the `@carbon-platform/icons` package, the commit that does this should be flagged as a `BREAKING CHANGE` so that the major version bumps on this package.
