### ISSUE TITLE
Mobile nav top spacing bug

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon-platform#913]
The space for the L0 header navigation is still showing on mobile. 2rem of extra space needs to be removed.

![Screen Shot 2022-06-22 at 3 17 04 PM](https://user-images.githubusercontent.com/2753488/175128367-a8adb5d6-8f27-4cd6-b0da-916916e9c3a7.png)

**Comment by mattrosno** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-624c3fc8b7972e001130fef7/issues/carbon-design-system/carbon-platform/913?planning-poker) with ZenHub @alisonjoseph @andreancardona @jdharvey-ibm
