### ISSUE TITLE
Add data viz collection pages

### ISSUE THREAD

**Issue by mattrosno** [carbon-design-system/carbon-platform#916]
**Summary**

Each collection has a list of resources, and also pages for supporting guidance. In a future release, we'll want to make this configurable so collections (specific to each system, global and local) can define its resources and also its pages through a `navData` construct.

For this first release, let's keep it simple and just add these three pages like our other static content.

![image.png](https://images.zenhubusercontent.com/546f60da7c6ccc6277a5fd78/a00fd0a2-9fe2-4f26-bc9f-09358d1c8bba)

In the future, we can give this more structure so collections can scale and not be hardcoded in this repo.

**Job stories**

What value will this deliver?

1. When browsing a collection, I want to view supporting documentation, so I can properly use the resources in the collection.

**Acceptance criteria**

What requirements must be met to complete this request?

1. All data viz content currently in https://carbondesignsystem.com is available through library or collection pages

**Comment by mattrosno** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-624c3fc8b7972e001130fef7/issues/carbon-design-system/carbon-platform/916?planning-poker) with ZenHub @alisonjoseph @andreancardona @jdharvey-ibm

**Comment by alisonjoseph** [comment]
@mattrosno Should we also add the following pages?

https://carbondesignsystem.com/data-visualization/axes-and-labels/
https://carbondesignsystem.com/data-visualization/legends/
https://carbondesignsystem.com/data-visualization/dashboards/
