### ISSUE TITLE
Design kit catalog page

### ISSUE THREAD

**Issue by mattrosno** [carbon-design-system/carbon-platform#919]
Spec: https://www.figma.com/file/I4Hryi0b79gU469AcZ3gkm/V1-Design-kit-Catalog?node-id=0%3A1

**Design**

- [x] External link redlines @kingtraceyj 
- [x] Specify body copy @kingtraceyj @aubrey-oneal 
- [x] Adobe Ace icon @kingtraceyj 

**Dev**

- [x] Route: `/design-kits`
- [x] Create reusable design kit tags in the data folder - [Matt's notes](https://ibm-studios.slack.com/archives/C035K6YM34Z/p1661974948885219)
- [x] Description that includes a link to the design getting started page
- [x] Search
- [x] Filter by maintainer, tool, type, status
- [x] Results bar
- [x] Catalog items
- [x] Pagination
- [x] External link hover treatment
- [ ] Make sure this link is added to the `Designing / get-started.mdx` line `184`

**Preview**

![image.png](https://images.zenhubusercontent.com/546f60da7c6ccc6277a5fd78/de29109b-4fc2-41b4-86fc-e6fc85f62251)

**Comment by mattrosno** [comment]
@kingtraceyj can you provide specs for the external link hover arrow that is positioned over the sponsor icon? We need that, because the all design kits catalog items take you to external destinations, right?

**Comment by mattrosno** [comment]
@francinelucca is this blocked by catalog refactors?

**Comment by francinelucca** [comment]
> @francinelucca is this blocked by catalog refactors?

It would be but refactor is in main already so we're good!
