### ISSUE TITLE
Add design kit descriptions

### ISSUE THREAD

**Issue by mattrosno** [carbon-design-system/carbon-platform#922]
We need descriptions for all design kits.

Contact @mattrosno for the latest list but the time of this writing, that means adding descriptions for these design kits:

https://github.com/carbon-design-system/carbon-platform/blob/3b96f324f83cc31d00064e2d0da718f0f2f5630b/services/web-app/data/carbon.yml

**Comment by kingtraceyj** [comment]
+ best practices

**Comment by aubrey-oneal** [comment]
Airtable with working descriptions:

https://airtable.com/appyxEkZZl7YQRGDF/tbldsudusc0bxnbLY/viwwXMOknhZYQjeLr?blocks=hide
