### ISSUE TITLE
Pictogram library grid should be 4-columns

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/carbon-platform#924]
https://next.carbondesignsystem.com/elements/pictograms/library

current
<img width="1487" alt="Screen Shot 2022-06-23 at 2 20 41 PM" src="https://user-images.githubusercontent.com/32881239/175380417-937154b7-d6d7-4b81-a3d0-b618a0127ba7.png">

Expected (https://carbondesignsystem.com/guidelines/pictograms/library/)
<img width="1493" alt="Screen Shot 2022-06-23 at 2 20 58 PM" src="https://user-images.githubusercontent.com/32881239/175380459-8fb43d04-dda5-4e49-986f-93c0188429ca.png">

**Comment by mattrosno** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-624c3fc8b7972e001130fef7/issues/carbon-design-system/carbon-platform/924?planning-poker) with ZenHub @andreancardona @francinelucca
