### ISSUE TITLE
[mobile] Style bug - Remove white line on the right side of the leadspace banner

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/carbon-platform#937]
In mobile (safari and Chrome) a 1–2px white line shows up o the right edge of the G100 leadspace banner.
![IMG_3262](https://user-images.githubusercontent.com/32881239/176333810-d363337b-6ef7-414c-a9bd-df4253e104de.PNG)

**Comment by alisonjoseph** [comment]
Also in footer
![image](https://user-images.githubusercontent.com/2753488/176428604-c2bdfd90-4cd8-40e6-ab68-fbb9a60351ea.png)

**Comment by mattrosno** [comment]
@alisonjoseph we should consider a pseudo-element that's positioned above the page header, same color as the page header, so as you pull down to refresh on mobile, you see that pseudo-element instead of the white site background.

**Comment by mjabbink** [comment]
Two separate things going on here. The right side of the banner & footer has little vertical line and the white gap/space that shows up “under” lead banner on certain scroll moments. Both are indicated in the topmost image.
