### ISSUE TITLE
Update pages with new naming convention

### ISSUE THREAD

**Issue by aubrey-oneal** [carbon-design-system/carbon-platform#941]
Finalize discussions with Matt-- and share with broader Carbon for feedback.

There are 4 pages that will need to be updated on our first go at naming principles, outlined in Figma:
https://www.figma.com/file/3zTomtMk9JGI0IwcUlqInh/Naming-Convention-%26-Content-Guidelines?node-id=0%3A1

- Landing page (Updates are in [Figma](https://www.figma.com/file/KZ6SWR2abIniIJY4RewDeA/Getting-Started-Design---Redline?node-id=10%3A13436) 
- How Carbon works (merged #1029 )
- Designing (updates are in [Figma](https://www.figma.com/file/uQXFGSKSJRr0l8CDd3cRGw/v1-prototype?node-id=0%3A1))
- Developing (merged #1058 )

**Comment by kingtraceyj** [comment]
Stakeholders to touch base with: Anna, Taylor, Josh, Scott, Kenny, Olivia

**Comment by aubrey-oneal** [comment]
Aligned with Mirko, David, Tom W, Morgana, Linda, Scott, Josh, and Anna on a naming convention. We also word-smithed the 'how carbon works pages'

Now we can move forward with updating content.
