### ISSUE TITLE
Synthesize and prioritize user feedback

### ISSUE THREAD

**Issue by aubrey-oneal** [carbon-design-system/carbon-platform#942]
Aubrey and Tracey will meet and synthesize the research. From this, we hope to get a priority list for feature requests and areas that need further design exploration.

**Comment by kingtraceyj** [comment]
Sythesis: https://ibm.box.com/s/q0gcjfipgdwv1trzz5zpl1baxzirp8iy

Issue list draft: https://ibm.box.com/s/bo2t4po3cu3hoie0o5435saycyh1m8qw
