### ISSUE TITLE
Update ecosystem image

### ISSUE THREAD

**Issue by aubrey-oneal** [carbon-design-system/carbon-platform#943]
We will need to consider:
- New naming convention, after discussing with squad (Carbon Design System has two objects underneath it)
- Finesse images (include Carbon charts?)

**Comment by kingtraceyj** [comment]
does the dependency image need updating? i'm thinking, as matt as slated, that we just change `Carbon design system` to `carbon core system` or `core system`. also change `product and digital systems` to `carbon local systems` or `local systems`

![image](https://user-images.githubusercontent.com/20582179/179053345-f3f3e47b-2758-424b-b919-a95c99b37052.png)

**Comment by aubrey-oneal** [comment]
Yes, it does need to be updated. Let's talk about prioritization.

**Comment by jeanservaas** [comment]
After talking to @aubrey-oneal we wanted to test a version two of this design with a few people to see which resonates more. Aubrey had the impression that the first one emphasized more of a hierarchy, with local systems under core system.

<img width="928" alt="ecosystem_revised_v2" src="https://user-images.githubusercontent.com/43144260/179251970-0c85b119-132a-4bbd-ad18-6f628bbafc8c.png">

**Comment by aubrey-oneal** [comment]
Keeping this open because we haven't made a finalized decision, though I've published a temporary ecosystem to the site.

**Comment by aubrey-oneal** [comment]
See our Figma page, Final ecosystem images or download the following files:
<img width="928" alt="16_9 12 column" src="https://user-images.githubusercontent.com/47198241/187494791-145192a4-5afb-42da-b680-41414c017ca0.png">
<img width="320" alt="Mobile" src="https://user-images.githubusercontent.com/47198241/187494807-0dd05543-077d-4eaf-bba8-856e05245035.png">

**Comment by aubrey-oneal** [comment]
Devs will need to add the mobile image for the following pages:
- How Carbon Works
- Designing>Get started
- Developing
