### ISSUE TITLE
Convert library sidenav pages to ISR

### ISSUE THREAD

**Issue by francinelucca** [carbon-design-system/carbon-platform#944]
Currently generating library sidenav pages at build time, let's switch to ISR when remote MDX epic is complete so that we can have library versioning work

**Comment by mattrosno** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-624c3fc8b7972e001130fef7/issues/carbon-design-system/carbon-platform/944?planning-poker) with ZenHub @andreancardona @francinelucca @jdharvey-ibm
