### ISSUE TITLE
Convert AnchorLinks from remote Usage, Style, Code, A11y, Orverview mdx pages to use PageNav component

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon-platform#950]
AnchorLinks displayed on current website for Overview, Usage, Style, Code, A11y pages **only**
<img width="915" alt="Screen Shot 2022-07-01 at 8 48 08 AM" src="https://user-images.githubusercontent.com/2753488/176907724-d2698a35-5b6d-490b-b845-8733c31e0a17.png">

Need to use PageNav in the Platform
<img width="838" alt="Screen Shot 2022-07-01 at 8 49 17 AM" src="https://user-images.githubusercontent.com/2753488/176907721-1a6d249b-ccc1-463e-b8be-4bd6b77696a7.png">

* Headings rendered by 'overviewPath' in overview tab should also be taken into account

**Comment by francinelucca** [comment]
Could do this by slugifying the anchor link "title" and using that as an Id that the pageNav will use?

**Comment by mattrosno** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-624c3fc8b7972e001130fef7/issues/carbon-design-system/carbon-platform/950?planning-poker) with ZenHub @alisonjoseph @andreancardona

**Comment by francinelucca** [comment]
Usage, Style, Code and Accessibility anchorlinks in #1192 

Overview h2s in #1179
