### ISSUE TITLE
z-index bug on icon/pictogram search

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon-platform#958]
![Screen Shot 2022-07-06 at 10 46 09 AM](https://user-images.githubusercontent.com/2753488/177591182-b4fd0315-8189-4c8b-8582-fb18ebe24147.png)

**Comment by mattrosno** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-624c3fc8b7972e001130fef7/issues/carbon-design-system/carbon-platform/958?planning-poker) with ZenHub @alisonjoseph @andreancardona
