### ISSUE TITLE
Update maintaining teams

### ISSUE THREAD

**Issue by mattrosno** [carbon-design-system/carbon-platform#963]
After https://github.com/carbon-design-system/carbon-platform/issues/951 is completed, we should consider these updates.

We currently have 7 maintaining teams specified here: https://github.com/carbon-design-system/carbon-platform/blob/main/services/web-app/data/teams.js#L29

**Update**

- [x] `Carbon` to `Carbon System Squad`
- [x] `IBM.com` to `Carbon Dotcom Squad`

**Add**

- [x] `IBM Accessibility` for the two design kits that team maintains (we'd also need a icon and pictogram)

**Justification**

The five indexed IBM.com libraries are maintained by the Carbon team but it just reads "IBM.com" so it's not extremely clear what that means. Hill 1A is about having confidence in using assets by knowing who maintains. Being more specific here should help instill confidence. Plus, when you view library details, we'll list out maintainers on a per-name basis to provide even more specificity.

E.g.:
<img width="1290" alt="image" src="https://user-images.githubusercontent.com/1691245/177629130-14346cf0-112e-426c-a8bb-c7b301c7831f.png">

**Comment by francinelucca** [comment]
Agree! 🚀

**Comment by mattrosno** [comment]
@kingtraceyj @jeanservaas thoughts on the 2 proposed updates and 1 addition?

**Comment by jeanservaas** [comment]
Looks good to me @mattrosno

**Comment by mattrosno** [comment]
@jeanservaas to look into Accessibility team icon and pictogram, to render in the design kits catalog.

**Comment by mattrosno** [comment]
@kingtraceyj thanks for sketching it up. I defer to @jeanservaas!

**Comment by kingtraceyj** [comment]
We can use this pictogram until we get brand approval (could take up to a month)

![AccessibilityAlt](https://user-images.githubusercontent.com/20582179/187519528-ef3c9061-7114-47fd-ac4a-8fe2b9949094.svg)
[AccessibilityAlt.svg.zip](https://github.com/carbon-design-system/carbon-platform/files/9455767/AccessibilityAlt.svg.zip)

**Comment by mattrosno** [comment]
On it. PR incoming.
