### ISSUE TITLE
Replace image with higher resolution version

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/carbon-platform#968]
This image is low quality.
https://next.carbondesignsystem.com/developing#understand-the-ecosystem

Current:
<img width="1144" alt="Screen Shot 2022-07-06 at 7 12 56 PM" src="https://user-images.githubusercontent.com/32881239/177663021-6548c1cd-aff8-4c4e-811c-159ce15565e0.png">

The one used on this page is significantly better.
https://next.carbondesignsystem.com/about-carbon/how-carbon-works#the-carbon-ecosystem

**Comment by francinelucca** [comment]
let's maybe eliminate the low quality and use the same one (route) for both? I don't see a reason to have them duplicated at separate routes? 👀

**Comment by alisonjoseph** [comment]
Agreed, we don't need to duplicate.
