### ISSUE TITLE
Web App: Can't run proxy server on dev mode

### ISSUE THREAD

**Issue by francinelucca** [carbon-design-system/carbon-platform#969]
**Description**

Error running proxy server on dev environment

**Steps to reproduce**

from services/web-app:

1. `npm run start:proxy`
See error:
<img width="855" alt="image" src="https://user-images.githubusercontent.com/40550942/177850327-a15a0e70-77da-4d65-ae85-1753a3551629.png">

**Comment by mattrosno** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-624c3fc8b7972e001130fef7/issues/carbon-design-system/carbon-platform/969?planning-poker) with ZenHub @andreancardona @francinelucca @jdharvey-ibm
