### ISSUE TITLE
Library page for compatible design kits

### ISSUE THREAD

**Issue by mattrosno** [carbon-design-system/carbon-platform#973]
Every library needs a `Design kits` page.

Redline: https://www.figma.com/file/K6HobXD4KXUIdkLrVjUzwK/LibraryDetail_CarbonReact?node-id=0%3A1

- [x] Body copy that says how these are "compatible" or "related" design kits that contain the design counterpart to coded assets in this library, with a link out to the design kits catalog to view all @aubrey-oneal 
- [x] Empty state for when there are no related design kits @kingtraceyj 
- [x] New resource card (MDX component for design kit resource card?) with data that comes from indexed design kits

![image](https://user-images.githubusercontent.com/20582179/179025686-dd629cb0-d3ed-4fe7-9ec7-dd9b270ed22a.png)

**Comment by mattrosno** [comment]
@aubrey-oneal can you provide body copy for this page?

@kingtraceyj can you provide an empty state for when there are no related design kits?

**Comment by mattrosno** [comment]
@kingtraceyj to update this image and make sure this issue links to the latest design spec for this page.

**Comment by mattrosno** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-624c3fc8b7972e001130fef7/issues/carbon-design-system/carbon-platform/973?planning-poker) with ZenHub @alisonjoseph @andreancardona @francinelucca

**Comment by kingtraceyj** [comment]
update redline link and the screenshot above. will add the empty state to the redline today.

**Comment by aubrey-oneal** [comment]
Standardized design kit page description. Note that we'll insert the library name as a variable.

The following design kits are compatible with the Carbon React library. Explore all design kits (here)[catalog link].
