### ISSUE TITLE
[catalog] Button set: Type in buttons is rendering Times— should be Plex.

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/carbon-platform#986]
https://next.carbondesignsystem.com/assets/components?view=grid
The type in the button is rendering times in Safari. Chrome seems to be displaying Plex.

<img width="460" alt="Screen Shot 2022-07-10 at 3 05 11 PM" src="https://user-images.githubusercontent.com/32881239/178160443-5d605f91-fabc-4719-83b0-0c9d47e28aaf.png">

**Comment by jeanservaas** [comment]
I noticed a few more that may not have been outlined and also updated them.

[mike_issue.zip](https://github.com/carbon-design-system/carbon-platform/files/9339292/mike_issue.zip)

**Comment by mattrosno** [comment]
This should have auto-closed with that PR.
