### ISSUE TITLE
Mdx-Media-Mapper media with prohibited url design/UX

### ISSUE THREAD

**Issue by francinelucca** [carbon-design-system/carbon-platform#993]
**Summary**

if an mdx file has an image/video with an unsupported url , what should the feedback to the user be?
- Should the image be ignored (removed)?
- Should we display an inline notification instead that let's the user know that that image can't be rendered due to an unsupported url (if so, what should the message say?)
- Other UX?

Example:

File in github.com/organization/repo/path has image with src = '../../other-org/other-repo/other-path'. This will result in a combined url of:
`github.com/other-org/other-repo/other-path` which we do not support since it'd be getting information from a different repository from a relative URL

Use inline notif:
<img width="682" alt="image" src="https://user-images.githubusercontent.com/40550942/179087839-58c097d1-97bc-4b42-974b-e5669cc34cf1.png">

**Comment by kingtraceyj** [comment]
@francinelucca @andreancardona  First draft is here in this figma: https://www.figma.com/file/WyfqQh9R1VXYZErfmsNDVH/MDX-errors?node-id=0%3A1

**Comment by francinelucca** [comment]
LGTM! thanks @kingtraceyj
