### ISSUE TITLE
MdxSanitizer - Create UI components

### ISSUE THREAD

**Issue by francinelucca** [carbon-design-system/carbon-platform#995]
**Summary**

Designs: https://www.figma.com/file/WyfqQh9R1VXYZErfmsNDVH/MDX-errors?node-id=9%3A4035
In order to build the spec defined in #952 we'll need to introduce a couple new UI components:

- FullPageError
       - imports/exports
<img width="725" alt="image" src="https://user-images.githubusercontent.com/40550942/178346230-83940de5-0354-44c5-9b0b-3706308b439d.png">

- InlineError (UnknownComponent)
       - UnknownComponent
       - parsing error
       - jsx error 
<img width="621" alt="image" src="https://user-images.githubusercontent.com/40550942/178346315-3ed4a4ee-1807-4324-826b-af73fad73116.png">
<img width="641" alt="image" src="https://user-images.githubusercontent.com/40550942/178346579-c9c8299c-e197-42a2-a8d6-12128a4b32e9.png">

Can include code snippet:
<img width="1218" alt="image" src="https://user-images.githubusercontent.com/40550942/179088534-5b1bd180-7ec8-4d8b-b75c-3d15b7680b0d.png">

These should be dynamic enough to handle different title/content as there can be multiple types of inline and fullPage errors.
Inlines should support link out as well for list of components or any other action

**Acceptance criteria**

What requirements must be met to complete this request?

1. New Components Are developed according to specs

**Comment by francinelucca** [comment]
Added #997 as a blocker since that might results in new UI comps needed

**Comment by alisonjoseph** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-624c3fc8b7972e001130fef7/issues/carbon-design-system/carbon-platform/995?planning-poker) with ZenHub @andreancardona @francinelucca
