### ISSUE TITLE
Create MdxSanitizerPackage

### ISSUE THREAD

**Issue by francinelucca** [carbon-design-system/carbon-platform#996]
**Summary**

Related #952

1 - Create a [PUBLIC] "MdxSanitizer" package that exports an unified attacher that can be injected into the mdx processor, this attacher will be thorough enough to cover all of platform's use cases but be general enough that can still be valuable for projects outside of the carbon ecosystem to use.

The attacher will:

- Receive a config param object including:
     - allowedComponents: array of allowed tags and custom component keys, defaults to []
     - fallbackComponent: component that will replace the content when a component that isn't allowed is identified, defaults to undefined
     - allowImports: whether import statements should be allowed in parsed mdx content, default to true
     - allowExports: whether export statements should be allowed in parsed mdx content, defaults to true
     - stripHTMLComments: whether HTML comments should be removed from parsed mdx content, defaults to true
     - tagReplacements: object containing entries of html or component tags that should be replaced, accompanied by a replace function that returns the content these tags should be replaced with, defaults to {}
     - onError: function to be called everytime an operation is performed on the AST as a result of the supplied configuration
- if config.stripHTMLComments, rewrite the processor "parse" function to remove comments for the string mdx source, using the [html-comment-regex lib](https://www.npmjs.com/package/html-comment-regex)
- Return a transformer function that will:
     - Find any component that isn't listed in the supplied in the allowedComponents array and replace it's content with fallbackComponent
     - if !config.allowImports throw a ImportFoundException; this exception should include info on the content and line position of the import statement found
     - if !config.allowExports throw a ExportFoundException; this exception should include info on the content and line position of the export statement found
     - if config.tagReplacements, for each entry:
          - Find all (if any) components whose tag matches the entry key name
          - Replace content with output of calling the function supplied in the entry value and parsing it to an mdast tree
          
OFF THE PLUGIN:

2 - Catch serialize errors on the web-app, display inline error with parser error data
3 - If there’s a JSX error, display inline error with error as well.
4 - If content cannot be retrieved, display a full page “The page you’re looking for cannot be found” info page
5 - Create a "Common Errors" page inside platform with each of the possible MDX errors as an entry and troubleshooting explanations

Package:
 - @carbon-platform/mdx-sanitizer
         Exports:
          - mdxSanitizerPlugin(config): Function (mdxPlugin type)

Structure: 
- packages/mdx-sanitizer
     - /src/
        -main/
            - mdx-sanitizer-plugin.ts
            - index.ts
            - interfaces.ts
            - exceptions/*
        -test/
           - mdx-sanitizer-plugin.test.js
           - test-files/*

- services/web-app/utils/mdx.js <- will be used to create a function that will generate the mdx-processor that injects and consumes the plugin (this logic needs to be taken out of github.js in the web-app)

**Comment by alisonjoseph** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-624c3fc8b7972e001130fef7/issues/carbon-design-system/carbon-platform/996?planning-poker) with ZenHub @andreancardona @francinelucca
