### ISSUE TITLE
MdxSanitizer - Contents Not Found + Scripts tags UI/UX

### ISSUE THREAD

**Issue by francinelucca** [carbon-design-system/carbon-platform#997]
**Summary**

1 - If the application fails to retrieve the contents of a given github mdx page, what should happen in the UI? (this is a full page error). 
- this can just be a page not found
Example: supplied github route doesn't exist, requested resource is not allowed (authentication error...)
2 - If a remote mdx contains a script tag, we cannot allow that script for security concerns reasons, what should the feedback to the user be?
Options:
- Remove script tag
- Replace with inline notification error, what should that say?
- Full page error
- some other UX?
Example:
```mdx
# Hi

<div>Hello</div>

<script>alert(Date.now());</script>
```

Replace this with an inline notification :
(Replace import with script)
<img width="1020" alt="image" src="https://user-images.githubusercontent.com/40550942/179086629-4905f9d6-7b3b-4415-8dbc-9a8e0ce225ab.png">
<img width="1055" alt="image" src="https://user-images.githubusercontent.com/40550942/179087080-bd6290b3-e32c-4348-8b8b-711a285587f3.png">

**Job stories**

What value will this deliver?

1. When my remote mdx content has some type of error or defect, I want the app to handle it gracefully, so I can have the best user experience.

**Acceptance criteria**

What requirements must be met to complete this request?

1.  Design specs for detailed cases

**Comment by kingtraceyj** [comment]
@francinelucca @andreancardona  First draft is here in this figma: https://www.figma.com/file/WyfqQh9R1VXYZErfmsNDVH/MDX-errors?node-id=0%3A1
